"""Page config for: Administration Statistics (UK)

Insolvency-page slim config — only the fields the Bernstein pipeline
and runtime-pack router actually read. Page-class routing for this
slug (data_reference) sits in scripts/page_runtime_metadata.py.
Draft generated by scripts/datahub/pages/procedure_stats.py.
"""

PAGE_CONFIG = {
    'slug': 'administration-statistics',
    'page_type': 'data_reference',
    'wp_page_id': 79854,
    'title': 'Administration Statistics (UK)',
    'verification_date': '19 June 2026',
}
