"""Page config for: Company Insolvencies by Sector (UK Data)

Insolvency-page slim config. Page-class routing for this slug
(data_reference) sits in scripts/page_runtime_metadata.py.
Draft generated by scripts/datahub/pages/sector_pages.py.
"""

PAGE_CONFIG = {
    'slug': 'company-insolvencies-by-sector',
    'page_type': 'data_reference',
    'wp_page_id': 79855,
    'title': 'Company Insolvencies by Sector (UK Data)',
    'verification_date': '19 June 2026',
}
