"""Page config for: Compare American Express Business Credit Cards.

Five Amex products across two structural categories: charge cards and credit cards.
The charge/credit distinction is the most important decision variable &mdash;
most buyers don't realise three of the five are charge cards until they apply.
Capital on Tap and Barclaycard listed as separate alternatives for businesses
where Amex acceptance is a practical barrier.
"""

PAGE_CONFIG = {
    'slug': 'compare-american-express-business-credit-cards',
    'page_type': 'brand_compare',
    'wp_page_id': 54934,
    'title': 'Compare American Express Business Credit Cards (2026)',
    'meta_description': (
        'Compare all five Amex business cards: Gold, Platinum, Basic, BA Accelerating, '
        'and Amazon. Charge cards vs credit cards explained. March 2026.'
    ),
    'verification_date': '20 March 2026',

    'info_gain': {
        'Charge Cards vs Credit Cards in the Amex Range': [
            'Three of five Amex business cards are charge cards — most buyers miss this',
            'Pay Over Time now on Gold/Platinum at 29.1% APR with GBP 50 minimum',
            'Seasonal cash flow test: can you clear GBP 15k in a slow month?',
        ],
        'Which Amex Card?': [
            'Decision table matching five business situations to specific Amex card',
        ],
        'Annual Fee Break-Even: What You Need to Spend': [
            'Original break-even calc: Gold needs GBP 2,500/month to justify GBP 195 fee',
            'MR point valuation at 0.8p mid-range with redemption method sensitivity',
            'CoT 1% cashback overtakes Gold at lower spend if MR redeemed poorly',
            'Late payment fee detail: GBP 12 charge, GBP 95 reinstatement after 60 days',
        ],
        'The Amex Acceptance Problem': [
            '15-minute supplier acceptance audit method before committing to Amex',
            'Acceptance still not universal: smaller UK suppliers and trade merchants excluded',
            'Below GBP 2,500/month Amex-eligible spend, fee is hard to earn back',
        ],
        "If Amex Doesn&rsquo;t Work": [
            'Capital on Tap and Barclaycard positioned as Visa/MC exit routes',
        ],
        'American Express Business Card FAQs': [
            'Business Basic flexible payment option clarified — sits between charge and credit',
        ],
    },

    # Editorial layout CSS now generated by generate_editorial_css() in css.py.
    # Page-specific overrides only (if any) go here.
    'page_css': '',

    'hero': {
        'top_pick_card_id': 'amex_business_gold',
        'top_pick_label': 'Best Amex',
        'top_pick_tagline': 'The best Amex rewards programme for businesses',
        'top_pick_features': [
            'Membership Rewards points on all spend',
            'No pre-set spending limit',
            'Travel insurance included',
            'Airport lounge access (with annual fee)',
            'Airport transfers included',
        ],
        # also_consider removed — revisiting design later
    },

    'card_ids': [
        'amex_business_gold', 'amex_business_platinum', 'amex_business_basic',
        'ba_amex_accelerating', 'amazon_amex',
    ],
    'separate_card_ids': [
        'capital_on_tap', 'barclaycard',
    ],

    'card_overrides': {
        'amex_business_gold': {
            'fit_label': 'Best for Membership Rewards points',
            'summary_strip': '&pound;0 yr 1, then &pound;195/yr &middot; Membership Rewards &middot; Charge card',
            'verdict': 'The most popular Amex business card for a reason: 1 MR point per &pound;1 on all spend, flexible redemption across airlines and hotels, and broad sole trader eligibility. The charge card structure means the full balance clears monthly.',
            'editorial_heading': 'The benchmark Amex business card &mdash; rewards-led, charge card structure',
            'best_for': 'High-spend businesses that clear monthly and want flexible points',
            'watch_out': 'Full balance due monthly &mdash; no option to carry. Check Amex acceptance with your key suppliers.',
            'not_ideal': 'You need to carry a balance, or key suppliers reject Amex',
            'eligibility': 'Sole traders, partnerships, LTDs, LLPs',
        },
        'amex_business_platinum': {
            'fit_label': 'Best for travel benefits and high spend',
            'summary_strip': '&pound;650/yr &middot; Membership Rewards &middot; Charge card &middot; Travel perks',
            'verdict': 'The premium tier: higher earn rate, airport lounge access, and travel insurance. The fee only makes sense at high spend levels or with regular business travel.',
            'editorial_heading': 'Premium travel benefits at a premium fee &mdash; the maths only work at high spend',
            'best_for': 'Frequent business travellers with high monthly card spend',
            'watch_out': 'Highest fee in the Amex range. Calculate break-even against your actual spend.',
            'not_ideal': 'You don&rsquo;t travel often, or monthly spend won&rsquo;t cover the fee',
            'eligibility': 'Sole traders, partnerships, LTDs, LLPs',
        },
        'amex_business_basic': {
            'fit_label': 'Entry-level Amex with flexible payment',
            'summary_strip': '&pound;0 annual fee &middot; No Membership Rewards &middot; Pay Over Time option',
            'verdict': 'No annual fee, no Membership Rewards. A starting point if you want Amex infrastructure without rewards or high fees, with a Pay Over Time option for eligible purchases.',
            'editorial_heading': 'Lower fee, lower earn rate, and more payment flexibility than the Gold',
            'best_for': 'Low-cost Amex entry with occasional payment flexibility',
            'watch_out': 'Payment structure has changed &mdash; confirm current terms at americanexpress.com/uk.',
            'not_ideal': 'You want any rewards programme (Gold or Platinum instead)',
            'eligibility': 'Sole traders, partnerships, LTDs, LLPs',
        },
        'ba_amex_accelerating': {
            'fit_label': 'Best for British Airways Avios',
            'summary_strip': '&pound;250/yr &middot; Avios per &pound;1 &middot; Credit card',
            'verdict': 'The only Amex business card earning Avios directly. Converts card spend into BA flights without a transfer step. No value if you don&rsquo;t fly BA.',
            'editorial_heading': 'Direct Avios earn for BA flyers &mdash; no transfer needed, no value if you don&rsquo;t fly BA',
            'best_for': 'Regular BA flyers who want direct Avios earning',
            'watch_out': 'Avios only valuable if you fly BA. Amex acceptance gaps still apply.',
            'not_ideal': 'You don&rsquo;t fly BA or prefer flexible Membership Rewards',
            'eligibility': 'Sole traders, partnerships, LTDs, LLPs',
        },
        'amazon_amex': {
            'fit_label': 'Best for Amazon business spend',
            'summary_strip': '&pound;50/yr &middot; Amazon cashback &middot; Credit card',
            'verdict': 'Designed for businesses with significant Amazon spend. Earn rate drops outside Amazon, so the value is concentrated in one channel.',
            'editorial_heading': 'Up to 2% back on Amazon spend, limited value elsewhere',
            'best_for': 'Heavy Amazon Business buyers wanting cashback on that spend',
            'watch_out': 'Rewards are Amazon-specific. Diversified spend earns more on Gold or Platinum.',
            'not_ideal': 'Low Amazon spend or you want rewards redeemable elsewhere',
            'eligibility': 'Sole traders, partnerships, LTDs, LLPs. Amazon Business account required.',
        },
        'capital_on_tap': {
            'fit_label': 'Visa acceptance, high limits',
            'summary_strip': 'From 13.86% APR &middot; Up to &pound;250k limit &middot; Visa &middot; Limited companies only',
            'verdict': 'Solves the Amex acceptance problem: Visa, higher credit limits, no bank account required. Limited companies only.',
            'editorial_heading': 'Solves the Amex acceptance problem &mdash; if you run a limited company',
            'best_for': 'Limited companies whose suppliers don&rsquo;t accept Amex',
            'watch_out': 'Limited companies and LLPs only. Sole traders cannot apply.',
            'not_ideal': 'You&rsquo;re a sole trader, or Amex acceptance works for your suppliers',
            'eligibility': 'UK limited companies and LLPs only. No bank account required.',
        },
        'barclaycard': {
            'fit_label': 'Visa cashback, open eligibility',
            'summary_strip': '25.5% APR &middot; No annual fee &middot; Up to 1% cashback &middot; Credit card',
            'verdict': 'Broadest-access alternative to Amex. Visa acceptance, cashback, open to sole traders. Higher APR than most.',
            'editorial_heading': 'Broad access and Visa acceptance &mdash; the fallback if Amex doesn&rsquo;t fit',
            'best_for': 'Businesses needing Visa acceptance with cashback',
            'watch_out': '25.5% APR. Cashback not transferable to airline programmes.',
            'not_ideal': 'You want premium rewards or can handle Amex acceptance',
            'eligibility': 'Sole traders, partnerships, LTDs. &pound;10k&ndash;&pound;6.5m turnover.',
        },
    },

    'sections': [
        {'type': 'css'},
        {'type': 'toc'},

        {'type': 'verdict_box',
         'text': 'American Express has five business card products, but they split into two distinct categories: charge cards (full balance due monthly) and credit cards (balance can be carried). We checked the latest terms on americanexpress.com/uk: Gold and Platinum are charge cards. BA Accelerating and Amazon are credit cards. Business Basic sits in the middle with a flexible payment option. Most buyers don&rsquo;t realise this until after they apply.'},

        {'type': 'hero_zone'},

        {'type': 'comparison_table', 'cards': 'main', 'config': {
            'badge_map': {
                'amex_business_gold': {'text': 'Top Pick', 'color': 'top'},
                'amex_business_platinum': {'text': 'Premium', 'color': 'gold'},
                'ba_amex_accelerating': {'text': 'Avios', 'color': 'pink'},
                'amex_business_basic': {'text': 'No Fee', 'color': 'teal'},
            },
            'feature_keys': ['reward_type', 'card_type'],
            'footer_text': (
                'Fees and rates verified March 2026 where available from public sources. '
                'Always confirm current terms at americanexpress.com/uk before applying.'
            ),
        }},

        {'type': 'toc_start'},

        {'type': 'prose', 'paragraphs': [
            'The card type distinction matters more than the rewards difference. Gold and Platinum are charge cards &mdash; full balance due monthly. BA Accelerating and Amazon are credit cards. Business Basic now has a flexible payment option. Your supplier mix and cash flow pattern decide which structure works, not the rewards headline.',
        ]},

        {'type': 'heading', 'level': 2, 'text': 'Charge Cards vs Credit Cards in the Amex Range'},

        {'type': 'prose', 'paragraphs': [
            'We verified the card types against americanexpress.com/uk: Gold and Platinum are charge cards. The full balance is due each month. There is no minimum payment option and no way to carry a balance. Interest doesn&rsquo;t apply because you&rsquo;re expected to pay in full.',
            'That distinction matters more than most comparison sites suggest. If you run a seasonal business &mdash; say a landscaping company that bills &pound;15k in summer and &pound;3k in January &mdash; a charge card forces you to clear &pound;15k in a single payment. A credit card lets you spread it. You need to be honest about whether your cash flow can absorb that monthly clearance in every month, not just the good ones.',
            'BA Accelerating and Amazon are credit cards. You can carry a balance and pay interest, or clear in full. Standard credit card structure. This is worth knowing because you might assume all Amex business cards work the same way. They do not.',
            'Business Basic has shifted: Amex introduced a &ldquo;Pay Over Time&rdquo; flexible payment option that allows partial payment on eligible purchases. Check current terms at americanexpress.com/uk &mdash; the classification has changed from its original charge card designation. If you want Amex card infrastructure with no annual fee and occasional payment flexibility, Business Basic is the option &mdash; but note it does not earn Membership Rewards points.',
            'Pay Over Time is also available on the Gold and Platinum charge cards for standard purchases up to the card&rsquo;s Flexible Payment Option credit limit. The interest rate is 29.1% variable APR. Any standard purchase qualifies, but the minimum payment each month is the higher of &pound;50 or the total FPO balance. That rate makes it expensive to carry &mdash; treat it as a short-term buffer, not a financing tool.',
        ]},

        {'type': 'heading', 'level': 2, 'text': 'Which Amex Card?'},

        {'type': 'table', 'html':
            '<table><thead><tr><th>Your Situation</th><th>Best Fit</th></tr></thead>'
            '<tbody>'
            '<tr><td>High spend, clear monthly, want flexible rewards</td><td>Business Gold</td></tr>'
            '<tr><td>Frequent business travel, high spend, want lounge access</td><td>Business Platinum</td></tr>'
            '<tr><td>New to Amex, want lower fee commitment or occasional flexibility</td><td>Business Basic</td></tr>'
            '<tr><td>Fly British Airways regularly</td><td>BA Amex Accelerating</td></tr>'
            '<tr><td>High Amazon Business spend</td><td>Amazon Amex</td></tr>'
            '</tbody></table>'},

        {'type': 'divider', 'label': 'Card-by-card detail'},

        {'type': 'tabbed_side_by_side'},

        {'type': 'heading', 'level': 2, 'text': 'Annual Fee Break-Even: What You Need to Spend'},

        {'type': 'prose', 'paragraphs': [
            'The Gold card costs &pound;195/year after the first year. Whether that fee earns its keep depends on how you value Membership Rewards points and how much spend you actually put on the card. The break-even at different spend levels shows where the maths tips.',
            'Membership Rewards points have no fixed cash value &mdash; they depend on how you redeem. Transfer to Avios and use them for a short-haul flight, and each point is worth roughly 1p. Redeem through the Amex shopping portal, and the value drops to 0.4&ndash;0.5p. We used 0.8p per point as a reasonable mid-range estimate for a business traveller who redeems thoughtfully.',
            'At &pound;2,000/month (&pound;24,000/year), you earn roughly 24,000 Membership Rewards points. At 0.8p per point that is &pound;192 in value &mdash; barely covering the &pound;195 fee. You break even, but you have earned nothing net. At &pound;3,000/month (&pound;36,000/year), you earn around 36,000 points worth roughly &pound;288 &mdash; a net gain of &pound;93 after the fee. At &pound;5,000/month (&pound;60,000/year), the return is approximately &pound;480 &mdash; a net gain of &pound;285.',
            'Compare that to Capital on Tap&rsquo;s 1% cashback with no annual fee. At &pound;3,000/month you earn &pound;360 in cashback &mdash; no fee to offset, no points to manage. The Amex Gold only overtakes Capital on Tap&rsquo;s raw cashback value at the upper end of spend, and only if you redeem Membership Rewards well. If you cash out MR points through Amex&rsquo;s weakest redemption options, the Gold card never catches up.',
            'The Platinum card has a higher fee and a higher earn rate, but the break-even is steeper. We would recommend you calculate your personal break-even before applying for any fee-bearing card. Your actual earn rate depends on your spend categories and Amex&rsquo;s current bonus multipliers &mdash; check americanexpress.com/uk for the latest.',
            'One cost that catches people out: late payment fees. If you miss the minimum payment on any Amex business card, the charge is &pound;12. If the balance goes 60 days overdue, Amex can suspend the card entirely, and reinstatement costs &pound;95. On a charge card where the full balance is due monthly, suspension is a real disruption &mdash; it is not just a fee, it is loss of access to the card while you resolve it.',
        ]},

        {'type': 'heading', 'level': 3, 'text': 'Can You Earn Enough Points to Justify Two Amex Cards?'},
        {'type': 'prose', 'paragraphs': [
            'Some businesses consider pairing the Gold with the BA Accelerating card. This is not worth it unless your monthly spend exceeds &pound;8,000 and you have clear, separate use cases for Membership Rewards and Avios. Running two fee-bearing cards doubles your break-even threshold and splits your spend across two programmes. For most businesses, concentrating spend on one card maximises your return.',
        ]},

        {'type': 'heading', 'level': 3, 'text': 'What Travel Benefits Does the Platinum Actually Include?'},
        {'type': 'prose', 'paragraphs': [
            'The Business Platinum&rsquo;s travel insurance is underwritten by Chubb and covers &pound;2m in medical expenses, &pound;7,500 in cancellation, and &pound;2,000 in baggage (&pound;500 per item, &pound;50 excess). The per-trip limit is 120 days. There is no cover for cardholders aged 80 or over. Those are reasonable limits for most business travel, but check Chubb&rsquo;s full policy document for exclusions before relying on it as your only travel cover.',
            'Priority Pass lounge access comes with two cards &mdash; the main card and one supplementary card. Each card admits the holder plus one guest. Amex also offers free pre-booking for select UK lounges, which removes the walk-up queue risk at busier airports. If you travel with a colleague regularly, the two-card setup covers both of you without a per-visit fee.',
        ]},

        {'type': 'heading', 'level': 3, 'text': 'Does the First-Year Fee Waiver Change the Calculation?'},
        {'type': 'prose', 'paragraphs': [
            'Yes &mdash; but it can also trap you. The &pound;0 first year is a genuine saving, and if your spend is moderate (&pound;1,500&ndash;&pound;2,500/month), you will earn a reasonable return in year one. The risk is that you commit to the card, set up supplier payments around it, and then face the &pound;195 fee in year two when your actual return does not justify it. We recommend running the break-even calculation at the post-waiver fee before you apply, not after.',
        ]},

        {'type': 'heading', 'level': 2, 'text': 'The Amex Acceptance Problem'},

        {'type': 'prose', 'paragraphs': [
            'Amex acceptance in the UK has improved significantly, but it&rsquo;s not universal. We reviewed acceptance across common business spend categories: major supermarkets, most online retailers, and large suppliers generally accept it. Smaller UK businesses, some professional services firms, and certain trade suppliers don&rsquo;t.',
            'Before committing to any Amex card, we recommend checking your three or four largest regular suppliers. If even one of them doesn&rsquo;t accept Amex, you will need a Visa or Mastercard alongside it &mdash; which reduces the value of consolidating spend on the Amex. See our <a href="/business-credit-cards/best-business-credit-cards/">full business credit card comparison</a> for Visa and Mastercard options.',
            'Here is a practical test you can run in fifteen minutes. Pull up your last three months of business bank statements. Identify your top ten suppliers by spend. Phone or email each one and ask whether they accept American Express. If more than three say no, your effective Amex spend is capped at 70% of your total &mdash; and the annual fee break-even calculation above needs adjusting downward. Businesses have signed up for Gold, discovered the acceptance gap after the first-year waiver ends, and ended up paying &pound;195 for a card they use on 40% of their transactions.',
            'The acceptance gap matters most for charge card holders. Because you cannot carry a balance, you need to use the card regularly to justify the fee. If your monthly Amex-eligible spend is below &pound;2,500, the fee is difficult to earn back through rewards alone. At that point, a no-fee Visa card with 1% cashback &mdash; like Capital on Tap &mdash; gives you a better net return with zero acceptance friction.',
        ]},

        {'type': 'heading', 'level': 2, 'text': 'If Amex Doesn&rsquo;t Work'},

        {'type': 'tabbed_card_list_separate'},

        {'type': 'heading', 'level': 2, 'text': 'American Express Business Card FAQs'},
        {'type': 'faq', 'items': [
            {
                'q': 'What is the difference between an Amex charge card and a credit card?',
                'a': [
                    'A charge card requires you to pay the full balance every month. There is no option to carry debt or pay a minimum. Gold and Platinum are charge cards.',
                    'A credit card lets you carry a balance and pay interest. BA Accelerating and Amazon Amex are credit cards. Business Basic now sits between the two with a flexible payment option &mdash; check current terms on americanexpress.com/uk.',
                ],
            },
            {
                'q': 'Which Amex business card is best for Membership Rewards points?',
                'a': 'The Business Gold Card. It earns 1 MR point per &pound;1 on all spend, with no pre-set spending limit. The Platinum earns at a higher rate on certain categories but costs &pound;650/year, so the Gold is the better starting point unless your monthly spend consistently exceeds &pound;8,000.',
            },
            {
                'q': 'Which Amex business card earns Avios?',
                'a': 'The BA Amex Accelerating Business Card earns Avios directly &mdash; not Membership Rewards. It costs &pound;250/year. If you fly BA regularly and want Avios without converting from another programme, this is the only Amex business card that does it.',
            },
            {
                'q': 'Is the Amex Business Gold Card free?',
                'a': 'The first year is &pound;0. After that it costs &pound;195/year. Our break-even analysis on this page shows you need roughly &pound;2,500/month in Amex-eligible spend to justify the fee through rewards alone. If your spend is lower, a no-fee card may give you a better net return.',
            },
            {
                'q': 'Can sole traders apply for an Amex business card?',
                'a': 'Yes. Sole traders are eligible for all five Amex business cards. You apply as an individual with your business details. Amex will run a personal credit check. There is no requirement to be a limited company.',
            },
            {
                'q': 'Do Amex business cards let you carry a balance?',
                'a': 'Only the credit cards: BA Accelerating, Amazon Amex, and Business Basic (with its flexible payment option). The Gold and Platinum are charge cards &mdash; the full balance is due monthly. If cash flow flexibility matters, you need a credit card, not a charge card.',
            },
            {
                'q': 'Are Amex business cards widely accepted in the UK?',
                'a': 'Acceptance has improved but is not universal. Most large retailers, supermarkets, and online merchants accept Amex. Some smaller suppliers, trade businesses, and professional services firms do not. We recommend checking your top suppliers before committing to an Amex card as your primary business card.',
            },
            {
                'q': 'Which Amex business card is best for travel perks?',
                'a': 'The Business Platinum Card. It includes airport lounge access, travel insurance, and hotel benefits. However, the &pound;650/year fee is steep. The Gold card also includes travel insurance and airport transfers at &pound;195/year, making it the better choice unless you travel frequently enough to use the Platinum&rsquo;s lounge access regularly.',
            },
        ]},

        {'type': 'heading', 'level': 2, 'text': 'Related Pages'},
        {'type': 'prose', 'paragraphs': [
            'Explore more of our credit card coverage:'
            '<ul>'
            '<li><a href="/business-credit-cards/best-business-credit-cards/">Best business credit cards compared</a></li>'
            '<li><a href="/business-credit-cards/best-business-charge-cards/">Best business charge cards</a></li>'
            '<li><a href="/business-credit-cards/best-cards-with-air-miles-avios/">Best cards for air miles and Avios</a></li>'
            '<li><a href="/business-credit-cards/what-are-the-best-business-credit-cards-for-travel/">Best business credit cards for travel</a></li>'
            '<li><a href="/business-credit-cards/capital-on-tap-vs-amex/">Capital on Tap vs Amex head-to-head</a></li>'
            '<li><a href="/business-credit-cards/business-credit-cards-vs-charge-cards/">Credit cards vs charge cards explained</a></li>'
            '</ul>',
        ]},

        {'type': 'heading', 'level': 2, 'text': 'Methodology and Disclosure'},
        {'type': 'methodology', 'paragraphs': [
            '<strong>Sources:</strong> We verified card types, fees, and rewards structures against americanexpress.com/uk on 20 March 2026. We update these figures quarterly. Some details may have changed since verification.',
            '<strong>Affiliate disclosure:</strong> Company Debt may receive referral fees from some providers listed on this page. This does not affect our assessments or the order in which products appear.',
            '<strong>Regulatory note:</strong> This page is editorial content, not regulated financial advice. Check your eligibility and current terms directly with the provider before applying.',
            '<a href="/editorial-policy/">Read our full editorial policy</a>',
        ]},

        {'type': 'spacer'},
        {'type': 'toc_js'},
    ],
}
