"""Page config for: Construction Insolvency Statistics (UK)

Insolvency-page slim config. Page-class routing for this slug
(data_reference) sits in scripts/page_runtime_metadata.py.
Draft generated by scripts/datahub/pages/sector_pages.py.
"""

PAGE_CONFIG = {
    'slug': 'construction-insolvency-statistics',
    'page_type': 'data_reference',
    'wp_page_id': 79856,
    'title': 'Construction Insolvency Statistics (UK)',
    'verification_date': '19 June 2026',
}
