"""Page config for: UK Creative, Arts and Entertainment Insolvency Statistics

Insolvency-page slim config. Page-class routing for this slug
(data_reference) sits in scripts/page_runtime_metadata.py.
Draft generated by scripts/datahub/pages/sic_group_stats.py.
"""

PAGE_CONFIG = {
    'slug': 'creative-arts-entertainment-insolvency-statistics',
    'page_type': 'data_reference',
    'wp_page_id': 80596,
    'title': 'UK Creative, Arts and Entertainment Insolvency Statistics',
    'verification_date': '22 July 2026',
}
