"""Page config for: CVL Statistics (UK)

Insolvency-page slim config — only the fields the Bernstein pipeline
and runtime-pack router actually read. Page-class routing for this
slug (data_reference) sits in scripts/page_runtime_metadata.py.
Draft generated by scripts/datahub/pages/procedure_stats.py.
"""

PAGE_CONFIG = {
    'slug': 'cvl-statistics',
    'page_type': 'data_reference',
    'wp_page_id': 79852,
    'title': 'CVL Statistics (UK)',
    'verification_date': '19 June 2026',
}
