"""Page config for: Estate Agency Insolvency Statistics (UK)

Insolvency-page slim config. Page-class routing for this slug
(sector_statistics) sits in scripts/page_runtime_metadata.py.
Draft generated by scripts/datahub/pages/sic_group_stats.py.
"""

PAGE_CONFIG = {
    'slug': 'estate-agency-insolvency-statistics',
    'page_type': 'data_reference',
    'wp_page_id': 80260,
    'title': 'Estate Agency Insolvency Statistics (UK)',
    'verification_date': '15 July 2026',
}
