"""Page config for: Furniture Manufacturing Insolvency Statistics (UK)

Insolvency-page slim config. Page-class routing for this slug
(data_reference) sits in scripts/page_runtime_metadata.py.
Draft generated by scripts/datahub/pages/sic_group_stats.py.
"""

PAGE_CONFIG = {
    'slug': 'furniture-insolvency-statistics',
    'page_type': 'data_reference',
    'wp_page_id': 80098,
    'title': 'Furniture Manufacturing Insolvency Statistics (UK)',
    'verification_date': '13 July 2026',
}
