"""Page config for: UK Hair, Beauty and Personal Care Insolvency Statistics

Insolvency-page slim config. Page-class routing for this slug
(data_reference) sits in scripts/page_runtime_metadata.py.
Draft generated by scripts/datahub/pages/sic_group_stats.py.
"""

PAGE_CONFIG = {
    'slug': 'personal-care-services-insolvency-statistics',
    'page_type': 'data_reference',
    'wp_page_id': 80587,
    'title': 'UK Hair, Beauty and Personal Care Insolvency Statistics',
    'verification_date': '22 July 2026',
}
