<?php
/**
 * CTA page map — GENERATED, do not hand-edit.
 *
 * Source: a completed copy of docs/cta-review-list.csv, one reviewed decision per
 * page, per docs/cta-insolvency-test-wording-plan.md.
 * Rebuild: python scripts/build_cta_page_map.py <completed.csv>
 *
 * Each entry is: slug => array( variant, urgency, block size, alternative primary CTA ).
 * 338 pages reviewed.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

return array(
	''                                                                                => array( 'none', '', 'none', '' ), // /
	'about-us'                                                                        => array( 'none', '', 'none', '' ), // /about-us/
	'advice'                                                                          => array( 'early_check', '', 'compact', 'Direct advice' ), // /advice/
	'are-directors-personally-liable-for-company-debts'                               => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/are-directors-personally-liable-for-company-debts/
	'business-restructuring'                                                          => array( 'early_check', '', 'large', '' ), // /advice/business-restructuring/
	'can-a-director-be-made-bankrupt-if-a-business-fails'                             => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/can-a-director-be-made-bankrupt-if-a-business-fails/
	'can-director-criminal-record'                                                    => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/can-director-criminal-record/
	'can-personal-assets-of-directors-be-seized-from-a-ltd-company'                   => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/can-personal-assets-of-directors-be-seized-from-a-ltd-company/
	'debt-management-guide'                                                           => array( 'early_check', '', 'large', '' ), // /advice/debt-management-guide/
	'directors-disqualification'                                                      => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/directors-disqualification/
	'directors-duties-to-creditors'                                                   => array( 'serious_position', '', 'large', '' ), // /advice/directors-duties-to-creditors/
	'directors-personal-guarantees'                                                   => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/directors-personal-guarantees/
	'frozen-bank-account'                                                             => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /advice/frozen-bank-account/
	'funding-options-for-smes-in-the-uk'                                              => array( 'none', '', 'none', '' ), // /advice/funding-options-for-smes-in-the-uk/
	'get-free-business-debt-advice'                                                   => array( 'early_check', '', 'compact', 'Direct advice' ), // /advice/get-free-business-debt-advice/
	'hmrcs-ir35-investigations-different'                                             => array( 'none', '', 'none', 'HMRC affordability' ), // /advice/hmrcs-ir35-investigations-different/
	'how-to-legally-take-money-out-of-a-limited-company'                              => array( 'none', '', 'none', '' ), // /advice/how-to-legally-take-money-out-of-a-limited-company/
	'insolvency-advice-for-directors'                                                 => array( 'serious_position', '', 'large', '' ), // /advice/insolvency-advice-for-directors/
	'losing-house-if-company-goes-bust'                                               => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/losing-house-if-company-goes-bust/
	'misfeasance'                                                                     => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/misfeasance/
	'overdrawn-directors-loan-accounts'                                               => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/overdrawn-directors-loan-accounts/
	'personal-guarantee-insurance'                                                    => array( 'none', '', 'none', 'Personal-liability guidance' ), // /advice/personal-guarantee-insurance/
	'personal-liability-for-cbils-loans'                                              => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/personal-liability-for-cbils-loans/
	'preventing-company-director-disputes'                                            => array( 'none', '', 'none', '' ), // /advice/preventing-company-director-disputes/
	'the-risks-of-signing-a-personal-guarantee'                                       => array( 'none', '', 'none', 'Personal-liability guidance' ), // /advice/the-risks-of-signing-a-personal-guarantee/
	'unenforceable-personal-guarantee'                                                => array( 'none', '', 'none', 'Personal-liability guidance' ), // /advice/unenforceable-personal-guarantee/
	'what-are-a-company-directors-duties-to-avoid-and-disclose-conflicts-of-interest' => array( 'none', '', 'none', '' ), // /advice/what-are-a-company-directors-duties-to-avoid-and-disclose-conflicts-of-interest/
	'what-are-fixed-and-floating-charges'                                             => array( 'none', '', 'none', '' ), // /advice/what-are-fixed-and-floating-charges/
	'what-are-phoenix-companies'                                                      => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/what-are-phoenix-companies/
	'what-are-the-duties-and-responsibilities-of-a-company-director'                  => array( 'none', '', 'none', '' ), // /advice/what-are-the-duties-and-responsibilities-of-a-company-director/
	'what-is-a-directors-responsibility-for-accountancy-errors'                       => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/what-is-a-directors-responsibility-for-accountancy-errors/
	'what-is-limited-liability'                                                       => array( 'none', '', 'none', '' ), // /advice/what-is-limited-liability/
	'what-is-the-companies-act-2006'                                                  => array( 'none', '', 'none', '' ), // /advice/what-is-the-companies-act-2006/
	'writing-off-a-directors-loan-account'                                            => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /advice/writing-off-a-directors-loan-account/
	'articles'                                                                        => array( 'none', '', 'none', '' ), // /articles/
	'124-pints-to-save-the-pub'                                                       => array( 'none', '', 'none', '' ), // /articles/124-pints-to-save-the-pub/
	'35-of-charities-fear-insolvency-due-to-cost-of-living-crisis'                    => array( 'none', '', 'none', '' ), // /articles/35-of-charities-fear-insolvency-due-to-cost-of-living-crisis/
	'can-heathrow-survive-covid-19'                                                   => array( 'none', '', 'none', '' ), // /articles/can-heathrow-survive-covid-19/
	'debt-charities-for-consumers'                                                    => array( 'none', '', 'none', '' ), // /articles/debt-charities-for-consumers/
	'how-will-carillions-insolvency-effect-its-supply-chain'                          => array( 'none', '', 'none', '' ), // /articles/how-will-carillions-insolvency-effect-its-supply-chain/
	'managing-debt-related-stress'                                                    => array( 'none', '', 'none', '' ), // /articles/managing-debt-related-stress/
	'paradise-papers'                                                                 => array( 'none', '', 'none', '' ), // /articles/paradise-papers/
	'pub-closures-in-the-uk'                                                          => array( 'none', '', 'none', '' ), // /articles/pub-closures-in-the-uk/
	'tescos-rated-worst-payer-uk-small-businesses'                                    => array( 'none', '', 'none', '' ), // /articles/tescos-rated-worst-payer-uk-small-businesses/
	'the-orla-kiely-fashion-brand-shuts-up-shop'                                      => array( 'none', '', 'none', '' ), // /articles/the-orla-kiely-fashion-brand-shuts-up-shop/
	'bounce-back-loan-support-hub'                                                    => array( 'none', '', 'none', '' ), // /bounce-back-loan-support-hub/
	'bounce-back-loan-fraud'                                                          => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /bounce-back-loan-support-hub/bounce-back-loan-fraud/
	'can-i-lose-my-house-with-a-bounce-back-loan'                                     => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /bounce-back-loan-support-hub/can-i-lose-my-house-with-a-bounce-back-loan/
	'cant-pay-coronavirus-business-interruption-loan-cbils'                           => array( 'early_check', '', 'large', '' ), // /bounce-back-loan-support-hub/cant-pay-coronavirus-business-interruption-loan-cbils/
	'directors-liability-for-bounce-back-loans'                                       => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /bounce-back-loan-support-hub/directors-liability-for-bounce-back-loans/
	'dissolving-a-company-with-bounce-back-loan'                                      => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /bounce-back-loan-support-hub/dissolving-a-company-with-bounce-back-loan/
	'what-happens-if-i-default'                                                       => array( 'early_check', '', 'large', '' ), // /bounce-back-loan-support-hub/what-happens-if-i-default/
	'business-insolvency'                                                             => array( 'none', '', 'none', '' ), // /business-insolvency/
	'articles-insights-hub'                                                           => array( 'none', '', 'none', '' ), // /business-insolvency/articles-insights-hub/
	'care-home-insolvency'                                                            => array( 'early_check', '', 'large', '' ), // /care-home-insolvency/
	'case-studies-hub'                                                                => array( 'none', '', 'none', '' ), // /case-studies-hub/
	'case-studies'                                                                    => array( 'none', '', 'none', '' ), // /case-studies/
	'chinese-takeaway'                                                                => array( 'none', '', 'none', '' ), // /case-studies/chinese-takeaway/
	'charity-non-profit-insolvency'                                                   => array( 'serious_position', '', 'compact', 'Specialist advice' ), // /charity-non-profit-insolvency/
	'close-my-company'                                                                => array( 'early_check', '', 'large', '' ), // /close-my-company/
	'closing-a-limited-company'                                                       => array( 'none', '', 'none', 'Solvent closure' ), // /closing-a-limited-company/
	'company-administration'                                                          => array( 'serious_position', '', 'large', '' ), // /company-administration/
	'light-touch-administration'                                                      => array( 'serious_position', '', 'compact', 'Direct advice' ), // /company-administration/light-touch-administration/
	'notice-of-intention-to-appoint-administrators'                                   => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /company-administration/notice-of-intention-to-appoint-administrators/
	'vs-administrative-receivership'                                                  => array( 'serious_position', '', 'compact', 'Direct advice' ), // /company-administration/vs-administrative-receivership/
	'vs-cva'                                                                          => array( 'serious_position', '', 'large', '' ), // /company-administration/vs-cva/
	'company-cash-flow-problems'                                                      => array( 'early_check', '', 'large', '' ), // /company-cash-flow-problems/
	'biggest-struggles-for-small-business-owners'                                     => array( 'early_check', '', 'compact', 'Direct advice' ), // /company-cash-flow-problems/biggest-struggles-for-small-business-owners/
	'cant-afford-to-pay-suppliers-what-are-the-options'                               => array( 'early_check', '', 'large', '' ), // /company-cash-flow-problems/cant-afford-to-pay-suppliers-what-are-the-options/
	'cant-afford-to-repay-business-loan'                                              => array( 'early_check', '', 'large', '' ), // /company-cash-flow-problems/cant-afford-to-repay-business-loan/
	'cant-pay-a-commercial-lease-or-rent'                                             => array( 'early_check', '', 'large', '' ), // /company-cash-flow-problems/cant-pay-a-commercial-lease-or-rent/
	'cant-pay-a-company-mortgage'                                                     => array( 'early_check', '', 'large', '' ), // /company-cash-flow-problems/cant-pay-a-company-mortgage/
	'cant-pay-business-energy'                                                        => array( 'early_check', '', 'large', '' ), // /company-cash-flow-problems/cant-pay-business-energy/
	'cant-pay-business-rates'                                                         => array( 'early_check', '', 'large', '' ), // /company-cash-flow-problems/cant-pay-business-rates/
	'cant-pay-staff-wages'                                                            => array( 'serious_position', '', 'large', '' ), // /company-cash-flow-problems/cant-pay-staff-wages/
	'challenge-a-statutory-demand'                                                    => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /company-cash-flow-problems/challenge-a-statutory-demand/
	'company-is-having-financial-difficulties'                                        => array( 'early_check', '', 'large', '' ), // /company-cash-flow-problems/company-is-having-financial-difficulties/
	'what-is-a-statutory-demand-against-a-company'                                    => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /company-cash-flow-problems/what-is-a-statutory-demand-against-a-company/
	'when-employers-cant-afford-redundancy-payments'                                  => array( 'serious_position', '', 'compact', 'Direct advice' ), // /company-cash-flow-problems/when-employers-cant-afford-redundancy-payments/
	'why-debt-is-not-always-a-bad-thing-for-your-business'                            => array( 'none', '', 'none', '' ), // /company-cash-flow-problems/why-debt-is-not-always-a-bad-thing-for-your-business/
	'company-rescue-recovery-hub'                                                     => array( 'none', '', 'none', '' ), // /company-rescue-recovery-hub/
	'company-rescue-solutions'                                                        => array( 'early_check', '', 'large', '' ), // /company-rescue-solutions/
	'company-voluntary-arrangement'                                                   => array( 'serious_position', '', 'large', '' ), // /company-rescue-solutions/company-voluntary-arrangement/
	'director-guarantees-in-a-cva'                                                    => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /company-rescue-solutions/company-voluntary-arrangement/director-guarantees-in-a-cva/
	'making-employees-redundant-cva'                                                  => array( 'serious_position', '', 'compact', 'Direct advice' ), // /company-rescue-solutions/company-voluntary-arrangement/making-employees-redundant-cva/
	'pros-and-cons'                                                                   => array( 'serious_position', '', 'large', '' ), // /company-rescue-solutions/company-voluntary-arrangement/pros-and-cons/
	'use-a-cva-to-close-a-company'                                                    => array( 'serious_position', '', 'large', '' ), // /company-rescue-solutions/company-voluntary-arrangement/use-a-cva-to-close-a-company/
	'vs-liquidation'                                                                  => array( 'serious_position', '', 'large', '' ), // /company-rescue-solutions/company-voluntary-arrangement/vs-liquidation/
	'what-happens-if-a-cva-fails-mid-term'                                            => array( 'none', '', 'none', 'Process-specific advice' ), // /company-rescue-solutions/company-voluntary-arrangement/what-happens-if-a-cva-fails-mid-term/
	'when-a-cva-fails'                                                                => array( 'none', '', 'none', 'Process-specific advice' ), // /company-rescue-solutions/company-voluntary-arrangement/when-a-cva-fails/
	'partnership-voluntary-arrangements'                                              => array( 'none', '', 'none', 'Partnership advice' ), // /company-rescue-solutions/partnership-voluntary-arrangements/
	'pre-packs'                                                                       => array( 'serious_position', '', 'compact', 'Direct advice' ), // /company-rescue-solutions/pre-packs/
	'construction-insolvency'                                                         => array( 'early_check', '', 'large', '' ), // /construction-insolvency/
	'contact-us'                                                                      => array( 'none', '', 'none', '' ), // /contact-us/
	'cookie-policy'                                                                   => array( 'none', '', 'none', '' ), // /cookie-policy/
	'county-court-judgements'                                                         => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /county-court-judgements/
	'data'                                                                            => array( 'none', '', 'none', '' ), // /data/
	'administration-statistics'                                                       => array( 'none', '', 'none', '' ), // /data/administration-statistics/
	'amusement-recreation-insolvency-statistics'                                      => array( 'none', '', 'none', '' ), // /data/amusement-recreation-insolvency-statistics/
	'architectural-engineering-insolvency-statistics'                                 => array( 'none', '', 'none', '' ), // /data/architectural-engineering-insolvency-statistics/
	'cleaning-company-insolvency-statistics'                                          => array( 'none', '', 'none', '' ), // /data/cleaning-company-insolvency-statistics/
	'company-insolvencies-by-sector'                                                  => array( 'none', '', 'none', '' ), // /data/company-insolvencies-by-sector/
	'compulsory-liquidation-statistics'                                               => array( 'none', '', 'none', '' ), // /data/compulsory-liquidation-statistics/
	'construction-insolvency-statistics'                                              => array( 'none', '', 'none', '' ), // /data/construction-insolvency-statistics/
	'creative-arts-entertainment-insolvency-statistics'                               => array( 'none', '', 'none', '' ), // /data/creative-arts-entertainment-insolvency-statistics/
	'cvl-statistics'                                                                  => array( 'none', '', 'none', '' ), // /data/cvl-statistics/
	'dissolutions-vs-insolvencies'                                                    => array( 'none', '', 'none', '' ), // /data/dissolutions-vs-insolvencies/
	'estate-agency-insolvency-statistics'                                             => array( 'none', '', 'none', '' ), // /data/estate-agency-insolvency-statistics/
	'freight-forwarding-logistics-insolvency-statistics'                              => array( 'none', '', 'none', '' ), // /data/freight-forwarding-logistics-insolvency-statistics/
	'furniture-insolvency-statistics'                                                 => array( 'none', '', 'none', '' ), // /data/furniture-insolvency-statistics/
	'hotel-insolvency-statistics'                                                     => array( 'none', '', 'none', '' ), // /data/hotel-insolvency-statistics/
	'it-consultancy-insolvency-statistics'                                            => array( 'none', '', 'none', '' ), // /data/it-consultancy-insolvency-statistics/
	'management-consultancy-insolvency-statistics'                                    => array( 'none', '', 'none', '' ), // /data/management-consultancy-insolvency-statistics/
	'medical-dental-practice-insolvency-statistics'                                   => array( 'none', '', 'none', '' ), // /data/medical-dental-practice-insolvency-statistics/
	'motor-vehicle-repair-insolvency-statistics'                                      => array( 'none', '', 'none', '' ), // /data/motor-vehicle-repair-insolvency-statistics/
	'payment-practices-late-payment'                                                  => array( 'none', '', 'none', '' ), // /data/payment-practices-late-payment/
	'personal-care-services-insolvency-statistics'                                    => array( 'none', '', 'none', '' ), // /data/personal-care-services-insolvency-statistics/
	'real-estate-letting-investment-insolvency-statistics'                            => array( 'none', '', 'none', '' ), // /data/real-estate-letting-investment-insolvency-statistics/
	'recruitment-agency-insolvency-statistics'                                        => array( 'none', '', 'none', '' ), // /data/recruitment-agency-insolvency-statistics/
	'restaurant-insolvency-statistics'                                                => array( 'none', '', 'none', '' ), // /data/restaurant-insolvency-statistics/
	'retail-insolvency-statistics'                                                    => array( 'none', '', 'none', '' ), // /data/retail-insolvency-statistics/
	'road-haulage-insolvency-statistics'                                              => array( 'none', '', 'none', '' ), // /data/road-haulage-insolvency-statistics/
	'sports-facility-insolvency-statistics'                                           => array( 'none', '', 'none', '' ), // /data/sports-facility-insolvency-statistics/
	'temporary-staffing-agency-insolvency-statistics'                                 => array( 'none', '', 'none', '' ), // /data/temporary-staffing-agency-insolvency-statistics/
	'uk-insolvency-statistics'                                                        => array( 'none', '', 'none', '' ), // /data/uk-insolvency-statistics/
	'winding-up-petition-tracker'                                                     => array( 'none', '', 'none', '' ), // /data/winding-up-petition-tracker/
	'debt-charities-uk'                                                               => array( 'none', '', 'none', '' ), // /debt-charities-uk/
	'debt-creditor-pressure-hub'                                                      => array( 'none', '', 'none', '' ), // /debt-creditor-pressure-hub/
	'director-protection-hub'                                                         => array( 'none', '', 'none', '' ), // /director-protection-hub/
	'director-redundancy'                                                             => array( 'serious_position', '', 'compact', 'Direct advice' ), // /director-redundancy/
	'energy-provider-insolvency'                                                      => array( 'early_check', '', 'large', '' ), // /energy-provider-insolvency/
	'guides-resources-hub'                                                            => array( 'none', '', 'none', '' ), // /guides-resources-hub/
	'hmrc'                                                                            => array( 'early_check', '', 'compact', 'Direct advice' ), // /hmrc/
	'accelerated-payment-notices-apn'                                                 => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/accelerated-payment-notices-apn/
	'can-hmrc-shut-down-my-business'                                                  => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/can-hmrc-shut-down-my-business/
	'cant-pay-paye'                                                                   => array( 'early_check', '', 'large', '' ), // /hmrc/cant-pay-paye/
	'cant-pay-vat'                                                                    => array( 'early_check', '', 'large', '' ), // /hmrc/cant-pay-vat/
	'controlled-goods-agreement'                                                      => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/controlled-goods-agreement/
	'corporation-tax-penalties'                                                       => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/corporation-tax-penalties/
	'distraint-order-notice'                                                          => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/distraint-order-notice/
	'hmrc-compliance-checks'                                                          => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/hmrc-compliance-checks/
	'hmrc-criminal-investigations'                                                    => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/hmrc-criminal-investigations/
	'hmrc-debt-enforcement-hub'                                                       => array( 'none', '', 'none', '' ), // /hmrc/hmrc-debt-enforcement-hub/
	'hmrc-enforcement-action'                                                         => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/hmrc-enforcement-action/
	'hmrc-follower-notice'                                                            => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/hmrc-follower-notice/
	'hmrc-fraud-investigations'                                                       => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/hmrc-fraud-investigations/
	'hmrc-offices-contact-guide'                                                      => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/hmrc-offices-contact-guide/
	'hmrc-penalties-investigations'                                                   => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/hmrc-penalties-investigations/
	'hmrc-tax-investigations'                                                         => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/hmrc-tax-investigations/
	'hmrc-threatening-letters'                                                        => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/hmrc-threatening-letters/
	'joint-and-several-liability-for-unpaid-vat'                                      => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /hmrc/joint-and-several-liability-for-unpaid-vat/
	'notice-of-enforcement'                                                           => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/notice-of-enforcement/
	'pay-hmrc-or-suppliers-first'                                                     => array( 'serious_position', '', 'large', '' ), // /hmrc/pay-hmrc-or-suppliers-first/
	'personal-liability-notices'                                                      => array( 'personal_risk_secondary', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/personal-liability-notices/
	'problems-paying-corporation-tax-hmrc'                                            => array( 'early_check', '', 'large', '' ), // /hmrc/problems-paying-corporation-tax-hmrc/
	'security-bond-notices'                                                           => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/security-bond-notices/
	'security-bonds'                                                                  => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/security-bonds/
	'tax-penalties'                                                                   => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/tax-penalties/
	'time-to-pay-hmrc'                                                                => array( 'early_check', '', 'large', '' ), // /hmrc/time-to-pay-hmrc/
	'understanding-hmrc-debt-collection'                                              => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/understanding-hmrc-debt-collection/
	'vat-penalties'                                                                   => array( 'none', '', 'none', 'HMRC affordability' ), // /hmrc/vat-penalties/
	'what-can-hmrc-bailiffs-take'                                                     => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/what-can-hmrc-bailiffs-take/
	'what-happens-if-hmrc-freezes-your-business-bank-account'                         => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/what-happens-if-hmrc-freezes-your-business-bank-account/
	'what-happens-if-hmrc-rejects-your-time-to-pay-arrangement'                       => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/what-happens-if-hmrc-rejects-your-time-to-pay-arrangement/
	'what-happens-if-hmrc-sends-bailiffs-to-a-business'                               => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/what-happens-if-hmrc-sends-bailiffs-to-a-business/
	'what-happens-if-you-ignore-hmrc-letters'                                         => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /hmrc/what-happens-if-you-ignore-hmrc-letters/
	'hospitality-restaurant-insolvency'                                               => array( 'early_check', '', 'large', '' ), // /hospitality-restaurant-insolvency/
	'insolvency-calculator'                                                           => array( 'none', '', 'none', '' ), // /insolvency-calculator/
	'insolvency-news-commentary'                                                      => array( 'none', '', 'none', '' ), // /insolvency-news-commentary/
	'insolvency-practitioner'                                                         => array( 'serious_position', '', 'large', '' ), // /insolvency-practitioner/
	'insolvency'                                                                      => array( 'early_check', '', 'large', '' ), // /insolvency/
	'antecedent-transactions'                                                         => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /insolvency/antecedent-transactions/
	'business-recovery-services'                                                      => array( 'early_check', '', 'large', '' ), // /insolvency/business-recovery-services/
	'can-we-trade-out-of-insolvency'                                                  => array( 'serious_position', '', 'large', '' ), // /insolvency/can-we-trade-out-of-insolvency/
	'can-you-sell-your-insolvent-company'                                             => array( 'serious_position', '', 'large', '' ), // /insolvency/can-you-sell-your-insolvent-company/
	'cease-trading'                                                                   => array( 'serious_position', '', 'large', '' ), // /insolvency/cease-trading/
	'check-if-a-company-is-insolvent'                                                 => array( 'early_check', '', 'large', '' ), // /insolvency/check-if-a-company-is-insolvent/
	'creditor-negotiations'                                                           => array( 'serious_position', '', 'large', '' ), // /insolvency/creditor-negotiations/
	'creditors-guides-to-insolvency-practitioners-fees'                               => array( 'none', '', 'none', 'Creditor guidance' ), // /insolvency/creditors-guides-to-insolvency-practitioners-fees/
	'creditors-meeting'                                                               => array( 'none', '', 'none', 'Process-specific advice' ), // /insolvency/creditors-meeting/
	'dealing-with-creditor-pressure'                                                  => array( 'serious_position', '', 'large', '' ), // /insolvency/dealing-with-creditor-pressure/
	'find-a-liquidator-near-me'                                                       => array( 'serious_position', '', 'compact', 'Direct advice' ), // /insolvency/find-a-liquidator-near-me/
	'how-to-reduce-insolvency-risk'                                                   => array( 'early_check', '', 'large', '' ), // /insolvency/how-to-reduce-insolvency-risk/
	'how-to-save-a-struggling-business'                                               => array( 'early_check', '', 'large', '' ), // /insolvency/how-to-save-a-struggling-business/
	'insolvency-act-1986'                                                             => array( 'none', '', 'none', '' ), // /insolvency/insolvency-act-1986/
	'insolvency-test'                                                                 => array( 'early_check', '', 'large', '' ), // /insolvency/insolvency-test/
	'insolvent-company-investigations'                                                => array( 'none', '', 'none', 'Process-specific advice' ), // /insolvency/insolvent-company-investigations/
	'insolvent-company-owes-me-money'                                                 => array( 'none', '', 'none', 'Creditor guidance' ), // /insolvency/insolvent-company-owes-me-money/
	'limited-company-bankruptcy'                                                      => array( 'early_check', '', 'large', '' ), // /insolvency/limited-company-bankruptcy/
	'lpa-receivership'                                                                => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /insolvency/lpa-receivership/
	'personal-liability-spouses-business-debts'                                       => array( 'none', '', 'none', 'Personal-liability guidance' ), // /insolvency/personal-liability-spouses-business-debts/
	'personally-liabilty-of-company-secretary'                                        => array( 'none', '', 'none', 'Personal-liability guidance' ), // /insolvency/personally-liabilty-of-company-secretary/
	'preferential-non-preferential-creditors'                                         => array( 'none', '', 'none', 'Creditor guidance' ), // /insolvency/preferential-non-preferential-creditors/
	'preferential-payments-during-insolvency'                                         => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /insolvency/preferential-payments-during-insolvency/
	'rescue-your-business-from-insolvency'                                            => array( 'serious_position', '', 'large', '' ), // /insolvency/rescue-your-business-from-insolvency/
	'retail-industry-insolvency-trends'                                               => array( 'none', '', 'none', '' ), // /insolvency/retail-industry-insolvency-trends/
	'secured-vs-unsecured-creditors'                                                  => array( 'none', '', 'none', 'Creditor guidance' ), // /insolvency/secured-vs-unsecured-creditors/
	'shareholders-liable-company-debts'                                               => array( 'none', '', 'none', 'Personal-liability guidance' ), // /insolvency/shareholders-liable-company-debts/
	'statement-of-affairs'                                                            => array( 'none', '', 'none', 'Process-specific advice' ), // /insolvency/statement-of-affairs/
	'stop-or-avoid-insolvency'                                                        => array( 'early_check', '', 'large', '' ), // /insolvency/stop-or-avoid-insolvency/
	'transactions-at-undervalue'                                                      => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /insolvency/transactions-at-undervalue/
	'validation-order'                                                                => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /insolvency/validation-order/
	'what-are-the-warning-signs-of-an-insolvent-company'                              => array( 'early_check', '', 'large', '' ), // /insolvency/what-are-the-warning-signs-of-an-insolvent-company/
	'what-happens-if-a-company-cannot-pay-its-debts'                                  => array( 'serious_position', '', 'large', '' ), // /insolvency/what-happens-if-a-company-cannot-pay-its-debts/
	'what-is-a-creditor'                                                              => array( 'none', '', 'none', 'Creditor guidance' ), // /insolvency/what-is-a-creditor/
	'what-is-a-freezing-order-or-injunction'                                          => array( 'none', '', 'none', 'Direct advice' ), // /insolvency/what-is-a-freezing-order-or-injunction/
	'what-is-a-high-court-writ'                                                       => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /insolvency/what-is-a-high-court-writ/
	'what-is-an-individual-voluntary-arrangement'                                     => array( 'none', '', 'none', '' ), // /insolvency/what-is-an-individual-voluntary-arrangement/
	'what-is-an-insolvency-practitioner'                                              => array( 'none', '', 'none', '' ), // /insolvency/what-is-an-insolvency-practitioner/
	'what-is-the-insolvency-service'                                                  => array( 'none', '', 'none', '' ), // /insolvency/what-is-the-insolvency-service/
	'what-is-wrongful-trading'                                                        => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /insolvency/what-is-wrongful-trading/
	'what-to-do-about-customer-insolvency'                                            => array( 'none', '', 'none', 'Creditor guidance' ), // /insolvency/what-to-do-about-customer-insolvency/
	'liquidation'                                                                     => array( 'serious_position', '', 'large', '' ), // /liquidation/
	'alternatives-to-company-liquidation'                                             => array( 'serious_position', '', 'large', '' ), // /liquidation/alternatives-to-company-liquidation/
	'am-i-solvent'                                                                    => array( 'none', '', 'none', 'Solvent closure' ), // /liquidation/am-i-solvent/
	'bailiffs-high-court-enforcement-officers'                                        => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /liquidation/bailiffs-high-court-enforcement-officers/
	'business-bank-account-in-liquidation'                                            => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/business-bank-account-in-liquidation/
	'can-a-director-be-sued-personally-by-creditors'                                  => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /liquidation/can-a-director-be-sued-personally-by-creditors/
	'can-a-supplier-force-my-company-into-liquidation'                                => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /liquidation/can-a-supplier-force-my-company-into-liquidation/
	'can-directors-go-to-prison-for-company-debt'                                     => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /liquidation/can-directors-go-to-prison-for-company-debt/
	'can-directors-pay-themselves-before-liquidation'                                 => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /liquidation/can-directors-pay-themselves-before-liquidation/
	'can-i-choose-my-liquidator'                                                      => array( 'serious_position', '', 'compact', 'Direct advice' ), // /liquidation/can-i-choose-my-liquidator/
	'can-i-liquidate-a-dormant-company'                                               => array( 'none', '', 'none', 'Solvent closure' ), // /liquidation/can-i-liquidate-a-dormant-company/
	'can-i-liquidate-my-company-with-a-bounce-back-loan'                              => array( 'serious_position', '', 'large', '' ), // /liquidation/can-i-liquidate-my-company-with-a-bounce-back-loan/
	'can-i-start-a-new-company-after-liquidating-my-old-one'                          => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/can-i-start-a-new-company-after-liquidating-my-old-one/
	'can-you-liquidate-to-avoid-paying-suppliers'                                     => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /liquidation/can-you-liquidate-to-avoid-paying-suppliers/
	'cant-afford-to-liquidate'                                                        => array( 'serious_position', '', 'large', '' ), // /liquidation/cant-afford-to-liquidate/
	'ccj-when-going-insolvent'                                                        => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /liquidation/ccj-when-going-insolvent/
	'company-pensions-and-liquidation'                                                => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/company-pensions-and-liquidation/
	'company-property-and-real-estate-in-liquidation'                                 => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/company-property-and-real-estate-in-liquidation/
	'company-restoration-after-liquidation'                                           => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/company-restoration-after-liquidation/
	'company-strike-off-and-dissolution'                                              => array( 'none', '', 'none', 'Solvent closure' ), // /liquidation/company-strike-off-and-dissolution/
	'can-i-be-sued-after-my-company-is-dissolved'                                     => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/company-strike-off-and-dissolution/can-i-be-sued-after-my-company-is-dissolved/
	'directors-responsibilities-after-a-company-is-struck-off'                        => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/company-strike-off-and-dissolution/directors-responsibilities-after-a-company-is-struck-off/
	'company-vehicles-and-equipment-in-liquidation'                                   => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/company-vehicles-and-equipment-in-liquidation/
	'compulsory-liquidation'                                                          => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /liquidation/compulsory-liquidation/
	'creditor-meetings-in-liquidation'                                                => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/creditor-meetings-in-liquidation/
	'creditors-voluntary-liquidation'                                                 => array( 'serious_position', '', 'large', '' ), // /liquidation/creditors-voluntary-liquidation/
	'cva-vs-strike-off-vs-liquidation'                                                => array( 'early_check', '', 'large', '' ), // /liquidation/cva-vs-strike-off-vs-liquidation/
	'director-conduct-review'                                                         => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /liquidation/director-conduct-review/
	'directors-conduct-report-2'                                                      => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/directors-conduct-report-2/
	'hmrc-as-a-creditor-in-liquidation'                                               => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/hmrc-as-a-creditor-in-liquidation/
	'how-much-does-liquidation-cost'                                                  => array( 'serious_position', '', 'compact', 'Direct advice' ), // /liquidation/how-much-does-liquidation-cost/
	'how-to-challenge-a-liquidators-decisions-or-fees'                                => array( 'none', '', 'none', 'Creditor guidance' ), // /liquidation/how-to-challenge-a-liquidators-decisions-or-fees/
	'how-to-choose-the-right-insolvency-procedure'                                    => array( 'serious_position', '', 'large', '' ), // /liquidation/how-to-choose-the-right-insolvency-procedure/
	'how-to-prepare-for-company-liquidation'                                          => array( 'serious_position', '', 'large', '' ), // /liquidation/how-to-prepare-for-company-liquidation/
	'how-to-prove-your-debt-in-company-liquidation'                                   => array( 'none', '', 'none', 'Creditor guidance' ), // /liquidation/how-to-prove-your-debt-in-company-liquidation/
	'insolvency-checklist'                                                            => array( 'early_check', '', 'large', '' ), // /liquidation/insolvency-checklist/
	'insolvency-myths-debunked'                                                       => array( 'early_check', '', 'compact', 'Direct advice' ), // /liquidation/insolvency-myths-debunked/
	'insolvency-vs-bankruptcy'                                                        => array( 'early_check', '', 'compact', 'Direct advice' ), // /liquidation/insolvency-vs-bankruptcy/
	'intellectual-property-and-trading-assets-in-liquidation'                         => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/intellectual-property-and-trading-assets-in-liquidation/
	'leases-and-contracts-in-liquidation'                                             => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/leases-and-contracts-in-liquidation/
	'liquidating-a-charity-or-non-profit'                                             => array( 'serious_position', '', 'compact', 'Specialist advice' ), // /liquidation/liquidating-a-charity-or-non-profit/
	'liquidating-a-company-with-no-assets-or-bank-account-uk'                         => array( 'serious_position', '', 'large', '' ), // /liquidation/liquidating-a-company-with-no-assets-or-bank-account-uk/
	'liquidating-a-group-company-or-holding-company-in-the-uk'                        => array( 'serious_position', '', 'compact', 'Specialist advice' ), // /liquidation/liquidating-a-group-company-or-holding-company-in-the-uk/
	'liquidating-a-limited-liability-partnership'                                     => array( 'none', '', 'none', 'Partnership advice' ), // /liquidation/liquidating-a-limited-liability-partnership/
	'liquidation-deadlines-and-time-limits'                                           => array( 'serious_position', '', 'compact', 'Direct advice' ), // /liquidation/liquidation-deadlines-and-time-limits/
	'liquidation-hub'                                                                 => array( 'none', '', 'none', '' ), // /liquidation/liquidation-hub/
	'liquidation-vs-dissolution-strike-off'                                           => array( 'none', '', 'none', 'Closure options' ), // /liquidation/liquidation-vs-dissolution-strike-off/
	'liquidators-powers-and-duties'                                                   => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/liquidators-powers-and-duties/
	'list-of-liquidation-documents'                                                   => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/list-of-liquidation-documents/
	'members-voluntary-liquidation'                                                   => array( 'none', '', 'none', 'Solvent closure' ), // /liquidation/members-voluntary-liquidation/
	'paying-staff-but-not-hmrc-before-liquidation'                                    => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /liquidation/paying-staff-but-not-hmrc-before-liquidation/
	'redundancy-payments-for-directors-in-an-mvl'                                     => array( 'none', '', 'none', 'Solvent closure' ), // /liquidation/redundancy-payments-for-directors-in-an-mvl/
	'seek-insolvency-advice-before-missing-payments'                                  => array( 'early_check', '', 'large', '' ), // /liquidation/seek-insolvency-advice-before-missing-payments/
	'should-i-close-my-company-or-try-to-save-it'                                     => array( 'early_check', '', 'large', '' ), // /liquidation/should-i-close-my-company-or-try-to-save-it/
	'timeline'                                                                        => array( 'serious_position', '', 'compact', 'Direct advice' ), // /liquidation/timeline/
	'uk-insolvency-flowchart'                                                         => array( 'early_check', '', 'large', '' ), // /liquidation/uk-insolvency-flowchart/
	'uk-insolvency-glossary'                                                          => array( 'none', '', 'none', '' ), // /liquidation/uk-insolvency-glossary/
	'voluntary-vs-compulsory-liquidation'                                             => array( 'serious_position', '', 'large', '' ), // /liquidation/voluntary-vs-compulsory-liquidation/
	'what-happens-after-company-liquidation'                                          => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/what-happens-after-company-liquidation/
	'what-happens-if-a-creditor-takes-me-to-court'                                    => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /liquidation/what-happens-if-a-creditor-takes-me-to-court/
	'what-happens-if-a-director-hides-company-assets'                                 => array( 'none', '', 'none', 'Process-specific advice' ), // /liquidation/what-happens-if-a-director-hides-company-assets/
	'what-happens-if-a-director-resigns-before-liquidation'                           => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /liquidation/what-happens-if-a-director-resigns-before-liquidation/
	'what-happens-if-a-director-transfers-assets-before-insolvency'                   => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /liquidation/what-happens-if-a-director-transfers-assets-before-insolvency/
	'what-happens-if-i-stop-paying-company-debts'                                     => array( 'serious_position', '', 'large', '' ), // /liquidation/what-happens-if-i-stop-paying-company-debts/
	'what-happens-to-directors-in-liquidation'                                        => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /liquidation/what-happens-to-directors-in-liquidation/
	'what-happens-to-employees'                                                       => array( 'none', '', 'none', '' ), // /liquidation/what-happens-to-employees/
	'whats-the-risk-of-being-disqualified-as-a-director'                              => array( 'personal_risk_secondary', '', 'compact', 'Direct advice' ), // /liquidation/whats-the-risk-of-being-disqualified-as-a-director/
	'when-should-a-director-stop-trading'                                             => array( 'serious_position', '', 'large', '' ), // /liquidation/when-should-a-director-stop-trading/
	'which-creditors-get-paid-first'                                                  => array( 'none', '', 'none', 'Creditor guidance' ), // /liquidation/which-creditors-get-paid-first/
	'winding-up-petition-vs-compulsory-liquidation'                                   => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /liquidation/winding-up-petition-vs-compulsory-liquidation/
	'manufacturing-insolvency'                                                        => array( 'early_check', '', 'large', '' ), // /manufacturing-insolvency/
	'meet-the-team'                                                                   => array( 'none', '', 'none', '' ), // /meet-the-team/
	'mental-health-debt-stress-support'                                               => array( 'none', '', 'none', '' ), // /mental-health-debt-stress-support/
	'privacy-policy'                                                                  => array( 'none', '', 'none', '' ), // /privacy-policy/
	'professional-services-insolvency'                                                => array( 'early_check', '', 'large', '' ), // /professional-services-insolvency/
	'receivership-mean-business'                                                      => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /receivership-mean-business/
	'sample-letters'                                                                  => array( 'none', '', 'none', '' ), // /sample-letters/
	'cease-trading-template'                                                          => array( 'none', '', 'none', '' ), // /sample-letters/cease-trading-template/
	'hold-action-on-my-account'                                                       => array( 'none', '', 'none', '' ), // /sample-letters/hold-action-on-my-account/
	'i-cannot-afford-to-repay-my-debt'                                                => array( 'none', '', 'none', '' ), // /sample-letters/i-cannot-afford-to-repay-my-debt/
	'i-have-no-knowledge-of-this-debt'                                                => array( 'none', '', 'none', '' ), // /sample-letters/i-have-no-knowledge-of-this-debt/
	'i-need-more-information-about-this-debt'                                         => array( 'none', '', 'none', '' ), // /sample-letters/i-need-more-information-about-this-debt/
	'request-a-reduced-monthly-payment'                                               => array( 'none', '', 'none', '' ), // /sample-letters/request-a-reduced-monthly-payment/
	'tell-debt-collector-to-stop-contacting-you'                                      => array( 'none', '', 'none', '' ), // /sample-letters/tell-debt-collector-to-stop-contacting-you/
	'write-off-my-debt'                                                               => array( 'none', '', 'none', '' ), // /sample-letters/write-off-my-debt/
	'sector-insolvency-hub'                                                           => array( 'none', '', 'none', '' ), // /sector-insolvency-hub/
	'sector-specific-insolvency'                                                      => array( 'none', '', 'none', '' ), // /sector-specific-insolvency/
	'sectors'                                                                         => array( 'none', '', 'none', '' ), // /sectors/
	'automotive'                                                                      => array( 'none', '', 'none', '' ), // /sectors/automotive/
	'carehomes'                                                                       => array( 'none', '', 'none', '' ), // /sectors/carehomes/
	'charity'                                                                         => array( 'none', '', 'none', '' ), // /sectors/charity/
	'childcare'                                                                       => array( 'none', '', 'none', '' ), // /sectors/childcare/
	'cleaning-contractors'                                                            => array( 'none', '', 'none', '' ), // /sectors/cleaning-contractors/
	'construction'                                                                    => array( 'none', '', 'none', '' ), // /sectors/construction/
	'dry-cleaning-laundry'                                                            => array( 'none', '', 'none', '' ), // /sectors/dry-cleaning-laundry/
	'energy'                                                                          => array( 'none', '', 'none', '' ), // /sectors/energy/
	'entertainment'                                                                   => array( 'none', '', 'none', '' ), // /sectors/entertainment/
	'events'                                                                          => array( 'none', '', 'none', '' ), // /sectors/events/
	'gyms'                                                                            => array( 'none', '', 'none', '' ), // /sectors/gyms/
	'haulage'                                                                         => array( 'none', '', 'none', '' ), // /sectors/haulage/
	'hotels'                                                                          => array( 'none', '', 'none', '' ), // /sectors/hotels/
	'insolvency-rescue-fish-chip-sector'                                              => array( 'none', '', 'none', '' ), // /sectors/insolvency-rescue-fish-chip-sector/
	'insolvency-rescue-solutions-for-garden-centers'                                  => array( 'none', '', 'none', '' ), // /sectors/insolvency-rescue-solutions-for-garden-centers/
	'leisure'                                                                         => array( 'none', '', 'none', '' ), // /sectors/leisure/
	'manufacturing'                                                                   => array( 'none', '', 'none', '' ), // /sectors/manufacturing/
	'professional-services'                                                           => array( 'none', '', 'none', '' ), // /sectors/professional-services/
	'property'                                                                        => array( 'none', '', 'none', '' ), // /sectors/property/
	'recruitment'                                                                     => array( 'none', '', 'none', '' ), // /sectors/recruitment/
	'restaurants'                                                                     => array( 'none', '', 'none', '' ), // /sectors/restaurants/
	'retail'                                                                          => array( 'none', '', 'none', '' ), // /sectors/retail/
	'schools'                                                                         => array( 'none', '', 'none', '' ), // /sectors/schools/
	'taxi-companies'                                                                  => array( 'none', '', 'none', '' ), // /sectors/taxi-companies/
	'travel'                                                                          => array( 'none', '', 'none', '' ), // /sectors/travel/
	'services-to'                                                                     => array( 'none', '', 'none', '' ), // /services-to/
	'accountants'                                                                     => array( 'none', '', 'none', '' ), // /services-to/accountants/
	'asset-based-and-other-lenders'                                                   => array( 'none', '', 'none', '' ), // /services-to/asset-based-and-other-lenders/
	'banks'                                                                           => array( 'none', '', 'none', '' ), // /services-to/banks/
	'creditors'                                                                       => array( 'none', '', 'none', '' ), // /services-to/creditors/
	'solicitors'                                                                      => array( 'none', '', 'none', '' ), // /services-to/solicitors/
	'site-map'                                                                        => array( 'none', '', 'none', '' ), // /site-map/
	'terms-conditions'                                                                => array( 'none', '', 'none', '' ), // /terms-conditions/
	'testimonials'                                                                    => array( 'none', '', 'none', '' ), // /testimonials/
	'transport-haulage-insolvency'                                                    => array( 'early_check', '', 'large', '' ), // /transport-haulage-insolvency/
	'winding-up-petitions'                                                            => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /winding-up-petitions/
	'dealing-with-an-hmrc-winding-up-petition'                                        => array( 'serious_position', 'urgent_action', 'compact', 'Direct advice' ), // /winding-up-petitions/dealing-with-an-hmrc-winding-up-petition/
	'what-is-a-winding-up-order'                                                      => array( 'none', '', 'none', 'Process-specific advice' ), // /winding-up-petitions/what-is-a-winding-up-order/
);
