"""
Sector Data Audit — Pre-Publish Gate for /drafts single-SIC-sector pages
=========================================================================

The sibling gate to article_audit.py, calibrated for a different page shape:
the sector_statistics page_class (scripts/datahub/pages/sic_group_stats.py),
e.g. /data/furniture-insolvency-statistics/. These are data-reference pages
for an analytical audience (journalists, lenders, accountants, directors),
not procedural director-facing guides, so this gate does NOT reuse
article_audit.py's guide-shape checks (FAQ accordion, take-the-test template,
featured image, Chris Andersen authorship) — those checks assume a page shape
this family does not have.

What IS shared with article_audit.py (same prose-quality bar, same source of
truth): AI fingerprints, padded evaluation, generic anchor text, banned
openings. Imported directly from article_audit so the rules never drift.

What is NEW to this gate, purpose-built for the sector-statistics shape:
  - a per-sector practitioner-voice insight paragraph must be present
    (earned "we", not boilerplate) — the runtime-packs/stages/humanise.md
    Part C requirement, calibrated down from the full guide-page bar (no
    concrete-scene count, no reader-stress warmth — wrong register for a
    data page) to what DOES transfer: earned practitioner "we" + evaluative
    bite.
  - a data-driven sector-context fact (comparison to the parent SIC section)
    must be present, sourced from sector_series.json, not asserted.
  - the shared chrome markers (chart, KPI panel, methodology, citation) must
    all be present, since these pages are built from a generator and any one
    could silently go missing on a bad edit.

Usage:
    python scripts/sector_data_audit.py --drafts drafts/ [--slug some-slug] [--json out.json] [--gate-format]
"""

from __future__ import annotations
import argparse
import io
import json
import re
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from article_audit import (  # noqa: E402
    AI_FINGERPRINTS, PADDED_EVALUATION, GENERIC_ANCHOR_RE, BAD_OPENING_PATTERNS,
    _strip_tags, _strip_wp_comments,
)

SENTINEL_MARKER = "generated by\n    scripts/datahub/pages/sic_group_stats.py"
EARNED_WE_RE = re.compile(r"\b(we|our|us)\b", re.I)
PCT_RE = re.compile(r"\d+(\.\d+)?%")
INTERNAL_DATA_LINK_RE = re.compile(r'href=["\'](/data/[a-z0-9-]+/)["\']', re.I)


@dataclass
class CheckResult:
    id: str
    name: str
    tier: str
    passed: bool
    detail: str = ""
    hard_fail: bool = True


@dataclass
class SectorPageAudit:
    path: str
    slug: str
    word_count: int
    checks: list[CheckResult] = field(default_factory=list)

    @property
    def score(self) -> int:
        return sum(1 for c in self.checks if c.passed)

    @property
    def max_score(self) -> int:
        return len(self.checks)

    @property
    def gate_passed(self) -> bool:
        return all(c.passed for c in self.checks if c.hard_fail)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["score"] = self.score
        d["max_score"] = self.max_score
        d["gate_passed"] = self.gate_passed
        return d


def _prose_text(html: str) -> str:
    text = _strip_wp_comments(html)
    text = _strip_tags(text)
    return re.sub(r"\s+", " ", text).strip()


def _strip_style(html: str) -> str:
    """Every sector page inlines the shared DASHBOARD_CSS in a <style> block —
    a CSS comment or property value can coincidentally contain an em dash or
    match a prose regex. All prose/structure checks run on content with any
    <style> block removed."""
    return re.sub(r"<style\b[^>]*>.*?</style>", "", html, flags=re.S | re.I)


def _section(html: str, marker_class: str) -> str | None:
    m = re.search(rf'<p\b[^>]*class="[^"]*{re.escape(marker_class)}[^"]*"[^>]*>(.*?)</p>', html, re.S)
    return _strip_tags(m.group(1)).strip() if m else None


def check_sentinel(raw: str) -> CheckResult:
    passed = SENTINEL_MARKER in raw or "sic_group_stats.py" in raw
    return CheckResult(id="01", tier="T1", name="Registered sector-page sentinel present",
                        passed=passed, detail="clean" if passed else "no sic_group_stats.py sentinel found")


def check_single_h1(body: str) -> CheckResult:
    n = len(re.findall(r"<h1\b", body, re.I))
    return CheckResult(id="02", tier="T1", name="Exactly one <h1>", passed=n == 1, detail=f"{n} found")


def check_em_dashes(body: str) -> CheckResult:
    count = body.count("—")
    return CheckResult(id="03", tier="T1", name="Zero em dashes",
                        passed=count == 0, detail=f"{count} em dash(es)")


def check_ai_fingerprints(prose: str) -> CheckResult:
    found = [name for name, pat in AI_FINGERPRINTS.items() if re.search(pat, prose, re.I | re.M)]
    return CheckResult(id="04", tier="T1", name="AI fingerprints < 3 distinct",
                        passed=len(found) < 3, detail=f"{len(found)}: {', '.join(found) or 'none'}")


def check_padded_evaluation(prose: str) -> CheckResult:
    found = [p for p in PADDED_EVALUATION if p.lower() in prose.lower()]
    return CheckResult(id="05", tier="T1", name="Padded evaluation phrases ≤ 1",
                        passed=len(found) <= 1, detail=f"{len(found)}: {', '.join(found) or 'none'}")


def check_generic_anchors(raw: str) -> CheckResult:
    hits = GENERIC_ANCHOR_RE.findall(raw)
    return CheckResult(id="06", tier="T1", name="No generic anchor text",
                        passed=len(hits) == 0, detail=f"{len(hits)} generic anchor(s)")


def check_banned_opening(body: str) -> CheckResult:
    m = re.search(r"<p\b[^>]*>(.*?)</p>", body, re.S)
    lede = _strip_tags(m.group(1)).strip() if m else ""
    hit = next((pat for pat in BAD_OPENING_PATTERNS if re.search(pat, lede, re.I)), None)
    return CheckResult(id="07", tier="T1", name="Lede clear of banned opening patterns",
                        passed=hit is None, detail=hit or "clean")


def check_practitioner_insight(body: str) -> CheckResult:
    text = _section(body, "cd-side-note__insight")
    if not text:
        return CheckResult(id="08", tier="T1", name="Practitioner-voice insight present (humanise Part C)",
                            passed=False, detail="no .cd-side-note__insight block found")
    if len(text) < 80:
        return CheckResult(id="08", tier="T1", name="Practitioner-voice insight present (humanise Part C)",
                            passed=False, detail=f"only {len(text)} chars, looks like boilerplate")
    if not EARNED_WE_RE.search(text):
        return CheckResult(id="08", tier="T1", name="Practitioner-voice insight present (humanise Part C)",
                            passed=False, detail="no earned we/our/us — reads as generic, not practitioner voice")
    return CheckResult(id="08", tier="T1", name="Practitioner-voice insight present (humanise Part C)",
                        passed=True, detail=f"{len(text)} chars, earned we present")


def check_sector_fact(body: str) -> CheckResult:
    text = _section(body, "cd-sector-fact")
    if not text:
        return CheckResult(id="09", tier="T1", name="Sourced sector-context fact present",
                            passed=False, detail="no .cd-sector-fact block found")
    if not PCT_RE.search(text):
        return CheckResult(id="09", tier="T1", name="Sourced sector-context fact present",
                            passed=False, detail="no percentage figure — looks unsourced")
    return CheckResult(id="09", tier="T1", name="Sourced sector-context fact present",
                        passed=True, detail=f"{len(text)} chars, figure present")


def check_methodology(body: str) -> CheckResult:
    passed = bool(re.search(r'id="method"', body))
    return CheckResult(id="10", tier="T1", name="Methodology block present",
                        passed=passed, detail="found" if passed else "no id=\"method\" section")


def check_citation(body: str) -> CheckResult:
    m = re.search(r'class="cd-cite-text"[^>]*>([^<]{10,})<', body)
    passed = bool(m) and "CompanyDebt" in (m.group(1) if m else "")
    return CheckResult(id="11", tier="T1", name="Source/citation block present",
                        passed=passed, detail="found" if passed else "no populated .cd-cite-text")


def check_chart(body: str) -> CheckResult:
    passed = "cd-chart-panel" in body and "<svg" in body
    return CheckResult(id="12", tier="T1", name="Chart present",
                        passed=passed, detail="found" if passed else "no cd-chart-panel + <svg")


def check_kpi(body: str) -> CheckResult:
    passed = "cd-main-kpi__v" in body
    return CheckResult(id="13", tier="T1", name="KPI panel present",
                        passed=passed, detail="found" if passed else "no cd-main-kpi__v")


def check_internal_data_links(body: str) -> CheckResult:
    links = set(m.group(1) for m in INTERNAL_DATA_LINK_RE.finditer(body)) - {"/data/"}
    return CheckResult(id="14", tier="T1", name="Internal /data/ sibling links ≥ 2",
                        passed=len(links) >= 2, detail=f"{len(links)}: {', '.join(sorted(links)) or 'none'}")


H2_KEYWORD_STOP = {
    "the", "and", "for", "statistics", "insolvency", "insolvencies", "uk",
    "of", "in", "are", "is", "latest", "data",
}
H2_KEYWORD_SECTIONS = (
    "latest", "trend", "comparison", "pressure", "practitioner", "longterm",
    "annual", "rate", "about", "commercial", "findings", "procedure", "faq",
)
# "policy" and "spike" are deliberately excluded: a policy-update heading
# (e.g. a named tax/duty change) or a spike-correction heading (e.g. a named
# statistical distortion) legitimately won't contain the sector keyword every
# time, and each is inherently unique per topic — no cannibalization risk.


def check_h2_keyword_coverage(body: str) -> CheckResult:
    """Every content H2 (trend/comparison/pressure/annual/about — NOT the
    shared methodology/citation boilerplate, which is intentionally identical
    everywhere) must carry a word from this page's own H1. Every page in this
    family shares one generator, so a generic H2 like 'Monthly insolvencies
    since 2023' renders byte-identical across every sector page — a real
    search-cannibalization risk once there are dozens of these pages, not
    just a cosmetic issue."""
    h1m = re.search(r"<h1>(.*?)</h1>", body, re.S)
    h1_text = _strip_tags(h1m.group(1)).strip() if h1m else ""
    title_words = [
        w.lower() for w in re.findall(r"[A-Za-z]+", h1_text)
        if w.lower() not in H2_KEYWORD_STOP and len(w) > 2
    ]
    if not title_words:
        return CheckResult(id="18", tier="T1", name="Content H2s carry this page's own keyword",
                            passed=False, detail="no H1 keywords found to check against")
    missing = []
    for sec_id in H2_KEYWORD_SECTIONS:
        m = re.search(rf'<section[^>]*id="{sec_id}"[^>]*>(.*?)</section>', body, re.S)
        if not m:
            continue
        h2 = re.search(r"<h2>(.*?)</h2>", m.group(1), re.S)
        if not h2:
            continue
        text = _strip_tags(h2.group(1)).strip()
        if not any(w in text.lower() for w in title_words):
            missing.append(f"#{sec_id}: \"{text}\"")
    return CheckResult(
        id="18", tier="T1", name="Content H2s carry this page's own keyword",
        passed=len(missing) == 0,
        detail="clean" if not missing else f"{len(missing)} generic: {'; '.join(missing)}",
    )


def check_word_count(wc: int) -> CheckResult:
    return CheckResult(id="15", tier="T2", name="Word count ≥ 400", passed=wc >= 400,
                        detail=f"{wc} words", hard_fail=False)


def check_paragraph_length(body: str) -> CheckResult:
    long_count = sum(1 for p in re.findall(r"<p\b[^>]*>(.*?)</p>", body, re.S)
                      if len(_strip_tags(p).strip()) > 400)
    return CheckResult(id="16", tier="T2", name="No paragraph > 400 chars",
                        passed=long_count == 0, detail=f"{long_count} over-long", hard_fail=False)


def check_lead_no_strong(body: str) -> CheckResult:
    m = re.search(r"<p\b[^>]*>(.*?)</p>", body, re.S)
    has_strong = bool(m and re.search(r"<(?:strong|b)\b", m.group(1), re.I))
    return CheckResult(id="17", tier="T2", name="Lead paragraph: no <strong>/<b>",
                        passed=not has_strong, detail="clean" if not has_strong else "strong/b in lead")


def audit_file(path: Path) -> SectorPageAudit:
    raw = path.read_text(encoding="utf-8")
    body = re.sub(r"^<!--.*?-->\s*", "", raw, count=1, flags=re.S)  # strip leading sentinel comment
    body = re.sub(r"^\s*<!-- wp:html -->\s*", "", body)
    body = re.sub(r"\s*<!-- /wp:html -->\s*$", "", body)
    body = _strip_style(body)
    prose = _prose_text(body)
    wc = len(prose.split())
    slug = path.stem.split("_", 1)[1] if "_" in path.stem else path.stem

    audit = SectorPageAudit(path=str(path), slug=slug, word_count=wc)
    audit.checks = [
        check_sentinel(raw),
        check_single_h1(body),
        check_em_dashes(body),
        check_ai_fingerprints(prose),
        check_padded_evaluation(prose),
        check_generic_anchors(raw),
        check_banned_opening(body),
        check_practitioner_insight(body),
        check_sector_fact(body),
        check_methodology(body),
        check_citation(body),
        check_chart(body),
        check_kpi(body),
        check_internal_data_links(body),
        check_h2_keyword_coverage(body),
        check_word_count(wc),
        check_paragraph_length(body),
        check_lead_no_strong(body),
    ]
    return audit


def print_report(a: SectorPageAudit) -> None:
    verdict = "PASS" if a.gate_passed else "FAIL"
    print("=" * 80)
    print(f"{a.slug}  ({a.path})")
    print(f"  words={a.word_count}  score={a.score}/{a.max_score}  GATE: {verdict}")
    print()
    for c in a.checks:
        mark = "✓" if c.passed else "✗"
        hf = "" if c.hard_fail else " [soft]"
        print(f"  {mark} [{c.tier}] {c.id}. {c.name}{hf}")
        if not c.passed and c.detail:
            print(f"      └─ {c.detail}")
    print()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--drafts", default="drafts")
    ap.add_argument("--slug", help="Limit to files whose name contains this substring")
    ap.add_argument("--json")
    ap.add_argument("--quiet", action="store_true")
    ap.add_argument("--gate-format", action="store_true")
    args = ap.parse_args()

    drafts_dir = Path(args.drafts)
    files = sorted(f for f in drafts_dir.glob("*.html") if "sic_group_stats.py" in f.read_text(encoding="utf-8")[:400])
    if args.slug:
        files = [f for f in files if args.slug in f.name]
    if not files:
        print("No sector-statistics draft files matched.", file=sys.stderr)
        return 1

    audits = [audit_file(f) for f in files]
    if not args.quiet:
        for a in audits:
            print_report(a)

    if args.gate_format:
        for a in audits:
            for c in a.checks:
                if not c.passed and c.hard_fail:
                    print(f"HARD FAIL: {c.id}. {c.name} - {c.detail or '(no detail)'}")

    print("=" * 80)
    print("SUMMARY")
    print("=" * 80)
    for a in audits:
        print(f"{a.slug:<45}{a.score}/{a.max_score:<5}{'PASS' if a.gate_passed else 'FAIL':<6}{a.word_count} words")

    if args.json:
        Path(args.json).write_text(json.dumps([a.to_dict() for a in audits], indent=2, default=str), encoding="utf-8")
        print(f"\nJSON written to {args.json}")

    return 0 if all(a.gate_passed for a in audits) else 1


if __name__ == "__main__":
    sys.exit(main())
