"""Assemble the Company Dissolutions vs Insolvencies page.

Takes the Claude Design reference, injects live figures, and regenerates Chart A
(incorporations vs dissolutions) as an SVG built from the real 24-month
Companies House series (last 16 months, to match the design window). The
design's sample chart capped at 60k; real dissolutions reach ~90k, so the
y-axis is rescaled here.

Writes:
  - preview/company-dissolutions-vs-insolvencies.html  (standalone)
  - drafts/pending_company-dissolutions-vs-insolvencies.html  (wp:html block)

Usage:
    python scripts/datahub/pages/company_dissolutions_vs_insolvencies.py
"""

from __future__ import annotations

import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DATA = ROOT / "data"
DESIGN = ROOT / "design-handoff" / "company-dissolutions-vs-insolvencies.html"
PREVIEW_OUT = ROOT / "preview" / "company-dissolutions-vs-insolvencies.html"
DRAFT_OUT = ROOT / "drafts" / "79848_dissolutions-vs-insolvencies.html"

THEME_ASSETS = "/wp-content/themes/company-debt-webpigment/assets/data-hub"
HUB_URL = "/data/"
SENTINEL = ("<!-- CD-NO-AUTOEDIT: data_reference page generated by "
            "scripts/datahub/pages/company_dissolutions_vs_insolvencies.py. "
            "Internal-link and article-rewrite pipelines must skip this file. -->")

MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]
ABBR = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def month_label(period: str) -> str:
    y, m = period.split("-")
    return f"{MONTHS[int(m) - 1]} {y}"


def nice_max(value: float) -> float:
    if value <= 0:
        return 10
    mag = 10 ** math.floor(math.log10(value))
    f = value / mag
    step = 1.5 if f <= 1.2 else 2 if f <= 2 else 3 if f <= 3 else 5 if f <= 5 else 10
    return step * mag


def build_dual_line_svg(months: list[str], inc: list[int], dis: list[int]) -> str:
    """Two-series SVG line chart in the design's style, scaled to the data."""
    n = len(months)
    x0, x1, ybase, ytop = 60.0, 1176.0, 332.0, 68.0
    xspan, yspan = x1 - x0, ybase - ytop
    ymax = nice_max(max(max(inc), max(dis)) * 1.05)

    def x(i: int) -> float:
        return x0 + i * xspan / (n - 1)

    def y(v: float) -> float:
        return ybase - (v / ymax) * yspan

    parts = []
    # Gridlines + y labels (5 ticks)
    for t in range(5):
        val = ymax * t / 4
        gy = y(val)
        lab = "0" if t == 0 else f"{int(val / 1000)}k"
        parts.append(f'      <line class="cd-grid" x1="60" y1="{gy:.1f}" x2="1176" y2="{gy:.1f}"/>')
        parts.append(f'      <text class="cd-axis-y" x="48" y="{gy + 4:.1f}">{lab}</text>')

    def polyline(vals, cls):
        pts = " ".join(f"{x(i):.1f},{y(v):.1f}" for i, v in enumerate(vals))
        return f'      <polyline class="cd-line {cls}" points="{pts}"/>'

    parts.append(polyline(inc, "cd-line--p"))
    parts.append(polyline(dis, "cd-line--o"))

    def dots(vals, cls):
        return "\n".join(
            f'      <circle class="cd-dot {cls}" cx="{x(i):.1f}" cy="{y(v):.1f}" r="3.5"/>'
            for i, v in enumerate(vals)
        )

    parts.append(dots(inc, "cd-dot--p"))
    parts.append(dots(dis, "cd-dot--o"))

    for i, m in enumerate(months):
        parts.append(f'      <text class="cd-axis-x" x="{x(i):.1f}" y="356">{ABBR[int(m.split("-")[1]) - 1]}</text>')

    aria = (f"Line chart comparing new company incorporations with company dissolutions each month, "
            f"{month_label(months[0])} to {month_label(months[-1])}. "
            f"Incorporations and dissolutions both run between roughly "
            f"{min(min(inc), min(dis)):,} and {max(max(inc), max(dis)):,} a month.")
    head = (f'<svg class="cd-linechart" viewBox="0 0 1200 380" preserveAspectRatio="xMidYMid meet" '
            f'role="img" aria-label="{aria}">')
    return head + "\n" + "\n".join(parts) + "\n        </svg>"


def load_context() -> dict:
    md = json.loads((DATA / "insolvency-statistics" / "release_metadata.json").read_text(encoding="utf-8"))
    series = json.loads((DATA / "companies-house" / "monthly_flows_series.json").read_text(encoding="utf-8"))["months"]

    months = sorted(series)[-16:]
    inc = [series[m]["incorporations"] for m in months]
    dis = [series[m]["dissolutions"] for m in months]

    latest = months[-1]
    dissolutions = series[latest]["dissolutions"]
    incorporations = series[latest]["incorporations"]
    insolvencies = md["latest_figures_table"]["rows"][0]["latest"]
    ratio = round(dissolutions / insolvencies)
    pct = insolvencies / dissolutions * 100

    return {
        "months": months, "inc": inc, "dis": dis,
        "dissolutions": dissolutions, "incorporations": incorporations,
        "insolvencies": insolvencies,
        "ch_period": month_label(latest),
        "ins_period": md["latest_month_label"],
        "ratio": ratio,
        "pct_width": round(pct, 2),
        "pct_stat": round(pct, 1),
        "window": f"{month_label(months[0])} to {month_label(months[-1])}",
    }


def _sub(html: str, old: str, new: str, *, count: int = 1) -> str:
    if old not in html:
        raise SystemExit(f"Anchor not found (design changed?): {old[:70]}")
    return html.replace(old, new, count if count else -1)


def inject(html: str, c: dict) -> str:
    # KPI values
    html = _sub(html, '<p class="cd-kpi-card__v">59,296</p>', f'<p class="cd-kpi-card__v">{c["dissolutions"]:,}</p>')
    html = _sub(html, '<p class="cd-kpi-card__v">2,085</p>', f'<p class="cd-kpi-card__v">{c["insolvencies"]:,}</p>')
    html = _sub(html, '<p class="cd-kpi-card__v">28:1</p>', f'<p class="cd-kpi-card__v">{c["ratio"]}:1</p>')
    html = _sub(html, '<p class="cd-kpi-card__v">62,523</p>', f'<p class="cd-kpi-card__v">{c["incorporations"]:,}</p>')
    # Period labels (two CH cards share the same string)
    html = _sub(html, '<b>May 2026</b>Companies House', f'<b>{c["ch_period"]}</b>Companies House', count=0)
    html = _sub(html, '<b>England and Wales, April 2026</b>Insolvency Service',
                f'<b>England and Wales, {c["ins_period"]}</b>Insolvency Service')
    # Scale bar
    html = _sub(html, '<span class="cd-scalebar__v">59,296</span>', f'<span class="cd-scalebar__v">{c["dissolutions"]:,}</span>')
    html = _sub(html, 'style="width:3.52%"', f'style="width:{c["pct_width"]}%"')
    html = _sub(html, '<span class="cd-scalebar__v cd-scalebar__v--out">2,085</span>',
                f'<span class="cd-scalebar__v cd-scalebar__v--out">{c["insolvencies"]:,}</span>')
    html = _sub(html, 'Companies House, May 2026', f'Companies House, {c["ch_period"]}')
    html = _sub(html, 'Insolvency Service, April 2026', f'Insolvency Service, {c["ins_period"]}')
    html = _sub(html, 'about <b>28 companies</b>', f'about <b>{c["ratio"]} companies</b>')
    html = _sub(html, '<div class="v">3.5%</div>', f'<div class="v">{c["pct_stat"]}%</div>')
    # "Why" source line
    html = _sub(html, 'Of the 59,296 dissolutions recorded in May 2026',
                f'Of the {c["dissolutions"]:,} dissolutions recorded in {c["ch_period"]}')
    html = _sub(html, '2,085 formal insolvencies in April 2026',
                f'{c["insolvencies"]:,} formal insolvencies in {c["ins_period"]}', count=0)
    # Chart A source window
    html = _sub(html, 'February 2025 to May 2026', c["window"], count=0)
    # Chart A SVG
    new_svg = build_dual_line_svg(c["months"], c["inc"], c["dis"])
    html = re.sub(r'<svg class="cd-linechart".*?</svg>', lambda _: new_svg, html, count=1, flags=re.S)
    return html


def to_wordpress(html: str) -> str:
    # Demote the hero <header> and closing <footer> to <div>: the theme paints the
    # bare <header>/<footer> elements navy (background:var(--c-blue-dark),
    # position:sticky), which would put dark text on a dark band. As <div>s the
    # design's own scoped styles apply.
    html = html.replace('<header class="cd-hub-header cd-w-wide">',
                        '<div class="cd-hub-header cd-w-wide">').replace('</header>', '</div>', 1)
    html = re.sub(r'<footer\b', '<div', html, count=1).replace('</footer>', '</div>', 1)
    html = html.replace('src="assets/', f'src="{THEME_ASSETS}/')
    for rel, site in {
        'href="uk-insolvency-statistics.html"': 'href="/data/uk-insolvency-statistics/"',
        'href="winding-up-petition-tracker.html"': 'href="/data/winding-up-petition-tracker/"',
        'href="company-dissolutions-vs-insolvencies.html"': 'href="/data/dissolutions-vs-insolvencies/"',
        'href="payment-practices-late-payment.html"': 'href="/data/payment-practices-late-payment/"',
        'href="company-insolvency-data-hub.html"': f'href="{HUB_URL}"',
    }.items():
        html = html.replace(rel, site)
    # Strip any remaining retired company-insolvency/ segment from absolute
    # URLs the design hard-codes (cite URLs etc.) so they sit flat under /data/.
    html = html.replace("/data/company-insolvency/", "/data/")
    styles = re.findall(r"<style[^>]*>.*?</style>", html, re.S)
    main = re.search(r'<main class="cd-data-hub">.*?</main>', html, re.S)
    if not styles or not main:
        raise SystemExit("Could not extract <style> and <main>.")
    return "<!-- wp:html -->\n" + "\n".join([SENTINEL, *styles, main.group(0)]) + "\n<!-- /wp:html -->\n"


def main() -> int:
    c = load_context()
    design = DESIGN.read_text(encoding="utf-8")
    injected = inject(design, c)

    PREVIEW_OUT.parent.mkdir(parents=True, exist_ok=True)
    PREVIEW_OUT.write_text(injected, encoding="utf-8")
    DRAFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    DRAFT_OUT.write_text(to_wordpress(injected), encoding="utf-8")

    print("Dissolutions vs insolvencies assembled with live data:")
    print(f"  Dissolutions   {c['dissolutions']:,} ({c['ch_period']})")
    print(f"  Insolvencies   {c['insolvencies']:,} ({c['ins_period']})")
    print(f"  Incorporations {c['incorporations']:,}")
    print(f"  Ratio          {c['ratio']}:1   insolvencies = {c['pct_stat']}% of dissolutions")
    print(f"  Chart A        {len(c['months'])} months, {c['window']}")
    print(f"Wrote preview: {PREVIEW_OUT}")
    print(f"Wrote draft:   {DRAFT_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
