"""Assemble the insolvency data hub landing page.

Takes the Claude Design reference (design-handoff/company-insolvency-data-hub.html),
injects the four live headline figures from the data backbone, and writes:
  - preview/company-insolvency-data-hub.html  (standalone, for visual checking)
  - drafts/pending_company-insolvency-data-hub.html (WordPress wp:html block)

The draft has no WordPress post id yet (the page is not created on staging).
Rename to drafts/<id>_company-insolvency-data-hub.html once the page exists.

The copy-citation script and JSON-LD are NOT in the draft (KSES strips them);
they belong in the mu-plugin. Source Serif 4 must be enqueued for production.

Usage:
    python scripts/datahub/pages/company_insolvency_hub.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DATA = ROOT / "data"
DESIGN = ROOT / "design-handoff" / "company-insolvency-data-hub.html"
PREVIEW_OUT = ROOT / "preview" / "company-insolvency-data-hub.html"
DRAFT_OUT = ROOT / "drafts" / "79845_data.html"

THEME_ASSETS = "/wp-content/themes/company-debt-webpigment/assets/data-hub"
SENTINEL = ("<!-- CD-NO-AUTOEDIT: data_reference page generated by "
            "scripts/datahub/pages/company_insolvency_hub.py. "
            "Internal-link and article-rewrite pipelines must skip this file. -->")

MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]


def month_label(period: str) -> str:
    """'2026-05' -> 'May 2026'."""
    y, m = period.split("-")
    return f"{MONTHS[int(m) - 1]} {y}"


def load_figures() -> dict:
    md = json.loads((DATA / "insolvency-statistics" / "release_metadata.json").read_text(encoding="utf-8"))
    rate = json.loads((DATA / "insolvency-statistics" / "rate_series.json").read_text(encoding="utf-8"))
    gz = json.loads((DATA / "the-gazette" / "monthly_notice_series.json").read_text(encoding="utf-8"))
    ch = json.loads((DATA / "companies-house" / "flow_snapshot.json").read_text(encoding="utf-8"))

    ins_total = md["latest_figures_table"]["rows"][0]["latest"]
    ins_period = md["latest_month_label"]
    rate_val = next(v for v in reversed(rate["rate_per_10k"]) if v is not None)
    gz_month = max(gz["months"])
    petitions = gz["months"][gz_month]["metrics"]["winding_up_petitions"]
    active = next(o["value"] for o in ch["observations"] if o["metric_key"] == "active_companies_total")

    return {
        "ins_total": ins_total,
        "ins_period": ins_period,
        "rate": rate_val,
        "petitions": petitions,
        "pet_period": month_label(gz_month),
        "active": active,
        "act_period": month_label(ch["month"]),
        "series_year": ins_period.split()[-1],
    }


def _sub(html: str, old: str, new: str) -> str:
    """Replace exactly once; fail loudly if the anchor is missing (design drift)."""
    if old not in html:
        raise SystemExit(f"Anchor not found in design (did the design change?): {old[:70]}")
    return html.replace(old, new, 1)


def build_sector_cards() -> str:
    """The "By sector" group: the sector overview as a lead card (it is the
    overview of every industry, not a peer of the trade pages below it - see
    docs/data-hub/design-brief-2026-07.md), then every published trade-detail
    page. Read from sector_trade_links.rows(), the same registry the
    flagship's own sector table reads, rather than hardcoded here: this is
    exactly the list that went stale in an earlier design snapshot (marked
    "Planned" with only Construction present, missing the 9 trade pages built
    since), so it must never be a second hand-maintained copy again."""
    import sys as _sys
    _sys.path.insert(0, str(Path(__file__).resolve().parent))
    from sector_trade_links import rows as trade_rows  # noqa: E402

    overview = (
        '<a class="cd-dircard cd-dircard--feature" href="/data/company-insolvencies-by-sector/">\n'
        '          <div class="cd-dircard__top">\n'
        '            <h3 class="cd-dircard__title">Company Insolvencies by Sector</h3>\n'
        '            <span class="cd-badge cd-badge--latest">Latest</span>\n'
        '          </div>\n'
        '          <p class="cd-dircard__desc">Insolvency volumes ranked across every SIC industry section, with trends since 2016. Start here, then find your trade below.</p>\n'
        '          <span class="cd-dircard__arrow">View sector data <span aria-hidden="true">&rarr;</span></span>\n'
        '        </a>'
    )
    trade_cards = "\n        ".join(
        f'<a class="cd-dircard" href="/data/{r["slug"]}/">\n'
        f'          <div class="cd-dircard__top">\n'
        f'            <h3 class="cd-dircard__title">{r["trade"]}</h3>\n'
        f'            <span class="cd-badge cd-badge--latest">Latest</span>\n'
        f'          </div>\n'
        f'          <p class="cd-dircard__desc">{r["blurb"]}</p>\n'
        f'          <span class="cd-dircard__arrow">View data <span aria-hidden="true">&rarr;</span></span>\n'
        f'        </a>'
        for r in trade_rows()
    )
    return (
        '<!-- By sector -->\n'
        '    <section class="cd-section" aria-labelledby="grp-sector">\n'
        '      <div class="cd-grouphead"><h2 id="grp-sector">By sector</h2><span class="cd-grouphead__note">Overview, then individual trades</span></div>\n'
        '      <div class="cd-dir-grid cd-dir-grid--feature">\n'
        f'        {overview}\n'
        '      </div>\n'
        '      <div class="cd-dir-grid">\n'
        f'        {trade_cards}\n'
        '      </div>\n'
        '    </section>'
    )


def inject_data(html: str, f: dict) -> str:
    # KPI values
    html = _sub(html, '<p class="cd-kpi-card__v">2,085</p>',
                f'<p class="cd-kpi-card__v">{f["ins_total"]:,}</p>')
    html = _sub(html, '<p class="cd-kpi-card__v">51.8<sub>per 10,000</sub></p>',
                f'<p class="cd-kpi-card__v">{f["rate"]}<sub>per 10,000</sub></p>')
    html = _sub(html, '<p class="cd-kpi-card__v">482</p>',
                f'<p class="cd-kpi-card__v">{f["petitions"]:,}</p>')
    html = _sub(html, '<p class="cd-kpi-card__v">5,498,905</p>',
                f'<p class="cd-kpi-card__v">{f["active"]:,}</p>')
    # Period labels
    html = _sub(html, '<b>England and Wales, April 2026</b>Insolvency Service',
                f'<b>England and Wales, {f["ins_period"]}</b>Insolvency Service')
    html = _sub(html, '<b>England and Wales, to April 2026</b>Insolvency Service',
                f'<b>England and Wales, to {f["ins_period"]}</b>Insolvency Service')
    html = _sub(html, '<b>Advertised in May 2026</b>The Gazette',
                f'<b>Advertised in {f["pet_period"]}</b>The Gazette')
    html = _sub(html, '<b>The register, May 2026</b>Companies House',
                f'<b>The register, {f["act_period"]}</b>Companies House')
    # Colophon series year
    html = _sub(html, '<dt>Series</dt><dd>2026</dd>',
                f'<dt>Series</dt><dd>{f["series_year"]}</dd>')

    # "How we use the data and how to cite" card: the design links to
    # /data/company-insolvency/methodology/, which the generic rewrite below
    # turns into /data/methodology/ - a page that does not exist (404). There
    # is no standalone methodology page; each data page carries its own
    # #method section. Reroute to the flagship's, which is real and live,
    # rather than ship a dead link styled as "Latest".
    html = _sub(html, 'href="/data/company-insolvency/methodology/"',
                'href="/data/uk-insolvency-statistics/#method"')

    # "By sector" cards: replace the whole design block, which is a stale
    # snapshot (both cards marked "Planned", only Construction present) - see
    # build_sector_cards()'s docstring. Matched on the HTML comment through
    # the section's own closing tag, so it cannot accidentally swallow the
    # next section if the design's indentation shifts.
    html = re.sub(
        r"<!-- By sector -->.*?</section>",
        build_sector_cards(),
        html, count=1, flags=re.S,
    )
    return html


def _demote_landmarks(html: str) -> str:
    """The theme paints the bare <header> and <footer> elements navy
    (background:var(--c-blue-dark), position:sticky). The design uses
    <header class="cd-hub-header"> for the hero and a <footer> for the closing
    source note, so both would render dark text on a navy band. Demote them to
    <div> so the theme's tag rules never apply and the design's own scoped
    styles take over."""
    html = html.replace('<header class="cd-hub-header cd-w-wide">',
                        '<div class="cd-hub-header cd-w-wide">').replace('</header>', '</div>', 1)
    html = re.sub(r'<footer\b', '<div', html, count=1).replace('</footer>', '</div>', 1)
    return html


def to_wordpress(html: str) -> str:
    """Rewrite asset/link paths to site paths and wrap as a wp:html draft."""
    html = _demote_landmarks(html)
    html = html.replace('src="assets/', f'src="{THEME_ASSETS}/')
    # URL structure: the hub IS /data/ and every data page sits directly
    # beneath it as /data/<slug>/ (flat, no intermediate company-insolvency
    # segment). The flagship stats page keeps its /data/uk-insolvency-statistics/ URL.
    for rel, site in {
        'href="uk-insolvency-statistics.html"': 'href="/data/uk-insolvency-statistics/"',
        'href="winding-up-petition-tracker.html"': 'href="/data/winding-up-petition-tracker/"',
        'href="company-dissolutions-vs-insolvencies.html"': 'href="/data/dissolutions-vs-insolvencies/"',
        'href="payment-practices-late-payment.html"': 'href="/data/payment-practices-late-payment/"',
        'href="company-insolvency-data-hub.html"': 'href="/data/"',
    }.items():
        html = html.replace(rel, site)

    # Any remaining absolute nested URLs the design hard-codes (cite URLs,
    # planned sub-pages like methodology) — strip the retired
    # company-insolvency/ segment so everything sits flat under /data/.
    html = html.replace("/data/company-insolvency/", "/data/")

    styles = re.findall(r"<style[^>]*>.*?</style>", html, re.S)
    main = re.search(r'<main class="cd-data-hub">.*?</main>', html, re.S)
    if not styles or not main:
        raise SystemExit("Could not extract <style> and <main> from the design.")
    body = "\n".join([SENTINEL, *styles, main.group(0)])
    return "<!-- wp:html -->\n" + body + "\n<!-- /wp:html -->\n"


def main() -> int:
    f = load_figures()
    design = DESIGN.read_text(encoding="utf-8")
    injected = inject_data(design, f)

    PREVIEW_OUT.parent.mkdir(parents=True, exist_ok=True)
    PREVIEW_OUT.write_text(injected, encoding="utf-8")

    DRAFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    DRAFT_OUT.write_text(to_wordpress(injected), encoding="utf-8")

    print("Hub landing page assembled with live figures:")
    print(f"  Insolvencies   {f['ins_total']:,} ({f['ins_period']})")
    print(f"  Rate           {f['rate']} per 10,000")
    print(f"  Petitions      {f['petitions']:,} ({f['pet_period']})")
    print(f"  Active cos     {f['active']:,} ({f['act_period']})")
    print(f"Wrote preview: {PREVIEW_OUT}")
    print(f"Wrote draft:   {DRAFT_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
