"""Assemble the insolvency data hub landing page.

Takes the Claude Design reference (design-handoff/company-insolvency-data-hub.html),
injects the four live headline figures from the data backbone, and writes:
  - preview/company-insolvency-data-hub.html  (standalone, for visual checking)
  - drafts/pending_company-insolvency-data-hub.html (WordPress wp:html block)

The draft has no WordPress post id yet (the page is not created on staging).
Rename to drafts/<id>_company-insolvency-data-hub.html once the page exists.

The copy-citation script and JSON-LD are NOT in the draft (KSES strips them);
they belong in the mu-plugin. Source Serif 4 must be enqueued for production.

Usage:
    python scripts/datahub/pages/company_insolvency_hub.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DATA = ROOT / "data"
DESIGN = ROOT / "design-handoff" / "company-insolvency-data-hub.html"
PREVIEW_OUT = ROOT / "preview" / "company-insolvency-data-hub.html"
DRAFT_OUT = ROOT / "drafts" / "pending_company-insolvency-data-hub.html"

THEME_ASSETS = "/wp-content/themes/company-debt-webpigment/assets/data-hub"
SENTINEL = ("<!-- CD-NO-AUTOEDIT: data_reference page generated by "
            "scripts/datahub/pages/company_insolvency_hub.py. "
            "Internal-link and article-rewrite pipelines must skip this file. -->")

MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]


def month_label(period: str) -> str:
    """'2026-05' -> 'May 2026'."""
    y, m = period.split("-")
    return f"{MONTHS[int(m) - 1]} {y}"


def load_figures() -> dict:
    md = json.loads((DATA / "insolvency-statistics" / "release_metadata.json").read_text(encoding="utf-8"))
    rate = json.loads((DATA / "insolvency-statistics" / "rate_series.json").read_text(encoding="utf-8"))
    gz = json.loads((DATA / "the-gazette" / "monthly_notice_series.json").read_text(encoding="utf-8"))
    ch = json.loads((DATA / "companies-house" / "flow_snapshot.json").read_text(encoding="utf-8"))

    ins_total = md["latest_figures_table"]["rows"][0]["latest"]
    ins_period = md["latest_month_label"]
    rate_val = next(v for v in reversed(rate["rate_per_10k"]) if v is not None)
    gz_month = max(gz["months"])
    petitions = gz["months"][gz_month]["metrics"]["winding_up_petitions"]
    active = next(o["value"] for o in ch["observations"] if o["metric_key"] == "active_companies_total")

    return {
        "ins_total": ins_total,
        "ins_period": ins_period,
        "rate": rate_val,
        "petitions": petitions,
        "pet_period": month_label(gz_month),
        "active": active,
        "act_period": month_label(ch["month"]),
        "series_year": ins_period.split()[-1],
    }


def _sub(html: str, old: str, new: str) -> str:
    """Replace exactly once; fail loudly if the anchor is missing (design drift)."""
    if old not in html:
        raise SystemExit(f"Anchor not found in design (did the design change?): {old[:70]}")
    return html.replace(old, new, 1)


def inject_data(html: str, f: dict) -> str:
    # KPI values
    html = _sub(html, '<p class="cd-kpi-card__v">2,085</p>',
                f'<p class="cd-kpi-card__v">{f["ins_total"]:,}</p>')
    html = _sub(html, '<p class="cd-kpi-card__v">51.8<sub>per 10,000</sub></p>',
                f'<p class="cd-kpi-card__v">{f["rate"]}<sub>per 10,000</sub></p>')
    html = _sub(html, '<p class="cd-kpi-card__v">482</p>',
                f'<p class="cd-kpi-card__v">{f["petitions"]:,}</p>')
    html = _sub(html, '<p class="cd-kpi-card__v">5,498,905</p>',
                f'<p class="cd-kpi-card__v">{f["active"]:,}</p>')
    # Period labels
    html = _sub(html, '<b>England and Wales, April 2026</b>Insolvency Service',
                f'<b>England and Wales, {f["ins_period"]}</b>Insolvency Service')
    html = _sub(html, '<b>England and Wales, to April 2026</b>Insolvency Service',
                f'<b>England and Wales, to {f["ins_period"]}</b>Insolvency Service')
    html = _sub(html, '<b>Advertised in May 2026</b>The Gazette',
                f'<b>Advertised in {f["pet_period"]}</b>The Gazette')
    html = _sub(html, '<b>The register, May 2026</b>Companies House',
                f'<b>The register, {f["act_period"]}</b>Companies House')
    # Colophon series year
    html = _sub(html, '<dt>Series</dt><dd>2026</dd>',
                f'<dt>Series</dt><dd>{f["series_year"]}</dd>')
    return html


def to_wordpress(html: str) -> str:
    """Rewrite asset/link paths to site paths and wrap as a wp:html draft."""
    html = html.replace('src="assets/', f'src="{THEME_ASSETS}/')
    for rel, site in {
        'href="uk-insolvency-statistics.html"': 'href="/uk-insolvency-statistics/"',
        'href="winding-up-petition-tracker.html"': 'href="/winding-up-petition-tracker/"',
        'href="company-dissolutions-vs-insolvencies.html"': 'href="/company-dissolutions-vs-insolvencies/"',
        'href="company-insolvency-data-hub.html"': 'href="/data/company-insolvency/"',
    }.items():
        html = html.replace(rel, site)

    style = re.search(r"<style>.*?</style>", html, re.S)
    main = re.search(r'<main class="cd-data-hub">.*?</main>', html, re.S)
    if not style or not main:
        raise SystemExit("Could not extract <style> and <main> from the design.")
    body = "\n".join([SENTINEL, style.group(0), main.group(0)])
    return "<!-- wp:html -->\n" + body + "\n<!-- /wp:html -->\n"


def main() -> int:
    f = load_figures()
    design = DESIGN.read_text(encoding="utf-8")
    injected = inject_data(design, f)

    PREVIEW_OUT.parent.mkdir(parents=True, exist_ok=True)
    PREVIEW_OUT.write_text(injected, encoding="utf-8")

    DRAFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    DRAFT_OUT.write_text(to_wordpress(injected), encoding="utf-8")

    print("Hub landing page assembled with live figures:")
    print(f"  Insolvencies   {f['ins_total']:,} ({f['ins_period']})")
    print(f"  Rate           {f['rate']} per 10,000")
    print(f"  Petitions      {f['petitions']:,} ({f['pet_period']})")
    print(f"  Active cos     {f['active']:,} ({f['act_period']})")
    print(f"Wrote preview: {PREVIEW_OUT}")
    print(f"Wrote draft:   {DRAFT_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
