"""Assemble the Payment Practices & Late Payment page.

Takes the Claude Design reference and REPLACES its sample figures with real
ones throughout, not just the headline KPI cards. The design's placeholder
data is materially wrong, not just a stand-in with the right shape: its
6-period trend chart includes "H2 2026", a period that has not happened yet
as of this build (today is well inside H1 2026), and its "1 in 3 invoices
paid late" callout corresponds to a 33% late-payment rate against a real rate
of 22%. Regenerates:
  - Chart A: real 6-monthly average-days-to-pay trend, computed by
    scripts/datahub/sources/payment_practices_trend.py from the raw report
    export (not fabricated - see that script's docstring for the method)
  - Chart B: the within-30/31-60/61+ day stacked bar, from real percentages
  - The sector table: real per-sector figures, sectors with fewer than
    MIN_SECTOR_N reporting companies dropped (too thin to average reliably)
    and stated as dropped, not silently
  - The "X invoices paid late" callout, recomputed from the real percentage

KPI cards and the sector count use data/payment-practices/
payment_practices_summary.json (already correct on the currently-live page);
Chart A additionally needs the newer payment_practices_trend.json.

Writes:
  - preview/payment-practices-late-payment.html
  - drafts/79850_payment-practices-late-payment.html

Usage:
    python scripts/datahub/pages/payment_practices_late_payment.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DATA = ROOT / "data"
DESIGN = ROOT / "design-handoff" / "payment-practices-late-payment.html"
PREVIEW_OUT = ROOT / "preview" / "payment-practices-late-payment.html"
DRAFT_OUT = ROOT / "drafts" / "79850_payment-practices-late-payment.html"

THEME_ASSETS = "/wp-content/themes/company-debt-webpigment/assets/data-hub"
HUB_URL = "/data/"
SENTINEL = ("<!-- CD-NO-AUTOEDIT: data_reference page generated by "
            "scripts/datahub/pages/payment_practices_late_payment.py. "
            "Internal-link and article-rewrite pipelines must skip this file. -->")

MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]

# Below this many reporting companies, a sector's average is too thin to
# publish as a reliable figure (see payment_practices_summary.json's smallest
# sectors: extraterritorial n=5, households as employers n=1).
MIN_SECTOR_N = 20
# The 3 slowest rows get the design's "num--lead" emphasis, matching its
# own convention (see design-handoff/payment-practices-late-payment.html).
LEAD_ROWS = 3


def month_label(period: str) -> str:
    y, m = period.split("-")
    return f"{MONTHS[int(m) - 1]} {y}"


def build_column_chart(periods: list[dict]) -> str:
    """Chart A: reuses the same .cd-colchart/.cd-col markup as the petition
    tracker and dissolutions pages, values in days rather than counts."""
    vals = [p["average_days_to_pay"] for p in periods]
    ymax = max(vals) * 1.15
    cols = []
    for p in periods:
        h = p["average_days_to_pay"] / ymax * 100
        cols.append(
            '        <div class="cd-col">\n'
            f'          <div class="cd-col__track"><div class="cd-col__bar" style="height:{h:.1f}%">'
            f'<span class="cd-col__v">{p["average_days_to_pay"]:.0f}</span></div></div>\n'
            f'          <div class="cd-col__x">{p["label"]}</div>\n'
            '        </div>'
        )
    aria = (f"Column chart of the average number of days large companies take to pay an "
            f"invoice, by six-monthly reporting period, from {vals[0]:.0f} days in "
            f"{periods[0]['label']} to {vals[-1]:.0f} days in {periods[-1]['label']}.")
    return (f'<div class="cd-colchart" role="img" aria-label="{aria}">\n'
            + "\n".join(cols) + "\n        </div>")


def build_stack_bar(pct_30: float, pct_31_60: float, pct_60_plus: float) -> str:
    aria = (f"Stacked bar showing when reported invoices are paid: {pct_30:.0f} per cent "
            f"within 30 days, {pct_31_60:.0f} per cent in 31 to 60 days, and "
            f"{pct_60_plus:.0f} per cent at 61 days or more.")
    return (
        f'<div class="cd-stack" role="img" aria-label="{aria}">\n'
        f'        <div class="cd-stack__seg cd-stack__seg--a" style="width:{pct_30:.0f}%">{pct_30:.0f}%</div>\n'
        f'        <div class="cd-stack__seg cd-stack__seg--b" style="width:{pct_31_60:.0f}%">{pct_31_60:.0f}%</div>\n'
        f'        <div class="cd-stack__seg cd-stack__seg--c" style="width:{pct_60_plus:.0f}%">{pct_60_plus:.0f}%</div>\n'
        f'      </div>'
    )


def build_sector_rows(sectors: list[dict]) -> str:
    kept = [s for s in sectors if s["companies"] >= MIN_SECTOR_N]
    kept.sort(key=lambda s: s["average_days_to_pay_mean"], reverse=True)
    rows = []
    for i, s in enumerate(kept):
        lead = " num--lead" if i < LEAD_ROWS else ""
        rows.append(
            f'              <tr><td class="lab">{s["label"]}</td>'
            f'<td class="num{lead}">{s["average_days_to_pay_mean"]:.0f}</td>'
            f'<td class="num">{s["pct_invoices_paid_late_mean"]:.0f}%</td>'
            f'<td class="num">{s["pct_paid_within_30_days_mean"]:.0f}%</td></tr>'
        )
    return "\n".join(rows), len(kept), len(sectors) - len(kept)


def load_context() -> dict:
    summary = json.loads((DATA / "payment-practices" / "payment_practices_summary.json").read_text(encoding="utf-8"))
    trend = json.loads((DATA / "payment-practices" / "payment_practices_trend.json").read_text(encoding="utf-8"))
    h = summary["headline"]
    return {
        "avg_days": h["average_days_to_pay"]["mean"],
        "pct_late": h["pct_invoices_paid_late"]["mean"],
        "pct_within_30": h["pct_paid_within_30_days"]["mean"],
        "pct_31_60": h["pct_paid_31_to_60_days"]["mean"],
        "pct_60_plus": h["pct_paid_later_than_60_days"]["mean"],
        "companies_in_window": summary["reporting_companies_in_window"],
        "window_end": month_label(summary["latest_period"]["end"][:7]),
        "trend_periods": trend["periods"],
        "sectors": summary["sector_breakdown"],
    }


def _sub(html: str, old: str, new: str, label: str) -> str:
    if old not in html:
        raise SystemExit(f"Anchor not found ({label}) - did the design change?: {old[:80]}")
    return html.replace(old, new, 1)


def inject(html: str, c: dict) -> str:
    # KPI cards
    html = _sub(html, '<p class="cd-kpi-card__v">36 days</p>',
                f'<p class="cd-kpi-card__v">{c["avg_days"]:.1f} days</p>', "kpi-days")
    html = _sub(html, '<p class="cd-kpi-card__v">33%</p>',
                f'<p class="cd-kpi-card__v">{c["pct_late"]:.0f}%</p>', "kpi-late")
    html = _sub(html, '<p class="cd-kpi-card__v">54%</p>',
                f'<p class="cd-kpi-card__v">{c["pct_within_30"]:.0f}%</p>', "kpi-within30")
    # The design's 4th card ("~11,000 reports filed this period") does not
    # correspond to anything in the real data (all-time report count is
    # 110,537; the real per-window figure is a company count). Replaced with
    # the honest framing already used on the currently-live page.
    html = _sub(
        html,
        '<article class="cd-kpi-card">\n'
        '        <p class="cd-kpi-card__v">~11,000</p>\n'
        '        <p class="cd-kpi-card__k">Payment reports filed this period</p>\n'
        '        <p class="cd-kpi-card__src"><b>Large UK businesses in scope</b>Department for Business and Trade</p>',
        '<article class="cd-kpi-card">\n'
        f'        <p class="cd-kpi-card__v">{c["companies_in_window"]:,}</p>\n'
        '        <p class="cd-kpi-card__k">Companies in the latest data</p>\n'
        f'        <p class="cd-kpi-card__src"><b>Most recent report each, to {c["window_end"]}</b>Department for Business and Trade</p>',
        "kpi-companies",
    )

    # Chart A: real trend, replacing the placeholder block wholesale
    open_marker = '<div class="cd-colchart"'
    close_marker = '\n      </div>\n      <p class="cd-source"><b>Source: Department for Business and Trade, Payment Practices Reporting.</b> Average reported days to pay an invoice'
    i0 = html.index(open_marker)
    i1 = html.index(close_marker)
    html = html[:i0] + build_column_chart(c["trend_periods"]) + html[i1:]
    html = _sub(
        html,
        'Average reported days to pay an invoice, by six-monthly reporting period. Representative sample values pending the live series.',
        'Average reported days to pay an invoice, by six-monthly reporting period. Company Debt calculations from the DBT Payment Practices Reporting bulk export: most recently filed report per company per period, periods shown once their 30-day filing deadline plus a margin has passed.',
        "chartA-source",
    )

    # Chart B: real percentages
    old_stack = (
        '<div class="cd-stack" role="img" aria-label="Stacked bar showing when reported invoices are paid: 54 per cent within 30 days, 31 per cent in 31 to 60 days, and 15 per cent at 61 days or more.">\n'
        '        <div class="cd-stack__seg cd-stack__seg--a" style="width:54%">54%</div>\n'
        '        <div class="cd-stack__seg cd-stack__seg--b" style="width:31%">31%</div>\n'
        '        <div class="cd-stack__seg cd-stack__seg--c" style="width:15%">15%</div>\n'
        '      </div>'
    )
    html = _sub(html, old_stack, build_stack_bar(c["pct_within_30"], c["pct_31_60"], c["pct_60_plus"]), "chartB")
    # The "1 in 3" callout matched the design's 33% placeholder, not the real
    # 22%. Restated without the fraction framing (22% is not a clean "1 in
    # N") and without the em dash the design used.
    html = _sub(
        html,
        '<p class="cd-scale-callout">About <b>1 in 3 invoices</b> are paid outside agreed terms &mdash; cash that smaller suppliers are owed but cannot yet use.</p>',
        f'<p class="cd-scale-callout"><b>{c["pct_late"]:.0f}% of invoices</b> are paid outside agreed terms, cash that smaller suppliers are owed but cannot yet use.</p>',
        "chartB-callout",
    )
    html = _sub(
        html,
        'Share of reported invoices by time taken to pay. Paid outside agreed terms cuts across these bands. Representative sample values pending the live series.',
        'Share of reported invoices by time taken to pay. Paid outside agreed terms cuts across these bands. Company Debt calculations from the DBT Payment Practices Reporting bulk export.',
        "chartB-source",
    )

    # Sector table: replace the whole <tbody>, and note how many sectors
    # were dropped for a thin sample rather than dropping them silently.
    rows_html, kept_n, dropped_n = build_sector_rows(c["sectors"])
    html = re.sub(r'<tbody>.*?</tbody>', f'<tbody>\n{rows_html}\n        </tbody>', html, count=1, flags=re.S)
    dropped_note = (
        f" {dropped_n} sector{'s' if dropped_n != 1 else ''} with fewer than {MIN_SECTOR_N} reporting "
        f"companies excluded, too small a sample to average reliably."
        if dropped_n else ""
    )
    html = _sub(
        html,
        'Figures are self-reported by businesses above the reporting threshold and are representative sample values pending the live series.',
        f'Figures are self-reported by businesses above the reporting threshold. Company Debt calculations from the DBT Payment Practices Reporting bulk export, most recent report per company in the trailing window.{dropped_note}',
        "sector-source",
    )

    return html


def to_wordpress(html: str) -> str:
    html = html.replace('<header class="cd-hub-header cd-w-wide">',
                        '<div class="cd-hub-header cd-w-wide">').replace('</header>', '</div>', 1)
    html = re.sub(r'<footer\b', '<div', html, count=1).replace('</footer>', '</div>', 1)
    html = html.replace('src="assets/', f'src="{THEME_ASSETS}/')
    for rel, site in {
        'href="uk-insolvency-statistics.html"': 'href="/data/uk-insolvency-statistics/"',
        'href="winding-up-petition-tracker.html"': 'href="/data/winding-up-petition-tracker/"',
        'href="company-dissolutions-vs-insolvencies.html"': 'href="/data/dissolutions-vs-insolvencies/"',
        'href="payment-practices-late-payment.html"': 'href="/data/payment-practices-late-payment/"',
        'href="company-insolvency-data-hub.html"': f'href="{HUB_URL}"',
    }.items():
        html = html.replace(rel, site)
    html = html.replace("/data/company-insolvency/", "/data/")
    styles = re.findall(r"<style[^>]*>.*?</style>", html, re.S)
    main = re.search(r'<main class="cd-data-hub">.*?</main>', html, re.S)
    if not styles or not main:
        raise SystemExit("Could not extract <style> and <main>.")
    return "<!-- wp:html -->\n" + "\n".join([SENTINEL, *styles, main.group(0)]) + "\n<!-- /wp:html -->\n"


def main() -> int:
    c = load_context()
    design = DESIGN.read_text(encoding="utf-8")
    injected = inject(design, c)

    PREVIEW_OUT.parent.mkdir(parents=True, exist_ok=True)
    PREVIEW_OUT.write_text(injected, encoding="utf-8")
    DRAFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    DRAFT_OUT.write_text(to_wordpress(injected), encoding="utf-8")

    _, kept_n, dropped_n = build_sector_rows(c["sectors"])
    print("Payment practices page assembled with live data:")
    print(f"  Headline: {c['avg_days']:.1f} days, {c['pct_late']:.0f}% late, "
          f"{c['pct_within_30']:.0f}% within 30 days, {c['companies_in_window']:,} companies")
    print(f"  Trend: {c['trend_periods'][0]['label']} ({c['trend_periods'][0]['average_days_to_pay']}) "
          f"to {c['trend_periods'][-1]['label']} ({c['trend_periods'][-1]['average_days_to_pay']})")
    print(f"  Sectors: {kept_n} kept, {dropped_n} dropped (n < {MIN_SECTOR_N})")
    print(f"Wrote preview: {PREVIEW_OUT}")
    print(f"Wrote draft:   {DRAFT_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
