"""Generate single-procedure insolvency data pages for the data hub.

CVL, compulsory liquidation and administration each get their own
data_reference page. To stay visually consistent with the flagship dashboard
these pages REUSE the flagship's shared CSS and chrome (masthead, source strip,
methodology band, final CTA) and the shared line-chart engine, and only add the
procedure-specific hero, trend chart, recent-months table and citation.

Data: data/insolvency-statistics/monthly_series.json (per-procedure monthly
series since 2000) + source_long_run_*.csv (per-procedure rate per 10,000) +
release_metadata.json (latest month, publication/next-release dates).

The dashboard JS (chart range tabs + copy-citation) and per-page JSON-LD are
injected by the mu-plugin cd-insolvency-data-hub.php, not the draft.

Usage:
    python scripts/datahub/pages/procedure_stats.py                 # all three
    python scripts/datahub/pages/procedure_stats.py cvl-statistics  # one
"""

from __future__ import annotations

import csv
import glob
import json
import sys
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[3]
SCRIPTS = ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))

from build_insolvency_dashboard import (  # noqa: E402
    DASHBOARD_CSS,
    masthead_block,
    srcstrip_block,
    methodology_block,
    final_cta_block,
)
from build_insolvency_charts import build_line_chart, format_number, month_label  # noqa: E402

DATA = ROOT / "data" / "insolvency-statistics"
DRAFTS = ROOT / "drafts"
SENTINEL = ("<!-- CD-NO-AUTOEDIT: data_reference page generated by "
            "scripts/datahub/pages/procedure_stats.py. "
            "Internal-link and article-rewrite pipelines must skip this file. -->")

# Static, number-free copy per procedure. Live figures are injected at build.
PROCEDURES = {
    "cvl-statistics": {
        "wp_id": 79852,
        "key": "cvls",
        "rate_col": "cvl_rate_ew",
        "abbr": "CVL",
        "plural": "CVLs",
        "h1a": "UK Creditors' Voluntary",
        "h1b": "Liquidation (CVL) Statistics",
        "eyebrow": "Creditors' voluntary liquidation",
        "definition": ("A creditors' voluntary liquidation (CVL) is an insolvent "
                       "liquidation that a company's own directors and shareholders "
                       "begin, rather than one ordered by a court. It is the most "
                       "common way an insolvent UK company is wound up."),
        "trend_intro": ("CVLs are the largest single insolvency procedure, so the "
                        "monthly trend closely tracks the overall insolvency total. "
                        "Volumes climbed sharply as pandemic support unwound and "
                        "have stayed high since."),
        "notes": [
            "CVLs move with the broader economy: when more companies stop trading, "
            "more directors place them into liquidation.",
            "The count is a volume, not a failure rate. The rate per 10,000 companies "
            "is a 12-month rolling figure, not the chance of a company failing in the "
            "latest month, and it adjusts for the size of the active register, which "
            "has grown over time.",
        ],
        "citation": ("CompanyDebt. (2026). UK CVL Statistics. CompanyDebt.com. Data "
                     "sourced from the Insolvency Service and Companies House company "
                     "insolvency statistics."),
        "related": ('CVLs are the largest component of the '
                    '<a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>. '
                    'For the court-ordered route see '
                    '<a href="/data/compulsory-liquidation-statistics/">compulsory liquidation statistics</a>, '
                    'and for the industry split see '
                    '<a href="/data/company-insolvencies-by-sector/">insolvency statistics by sector</a>.'),
    },
    "compulsory-liquidation-statistics": {
        "wp_id": 79853,
        "key": "compulsory",
        "rate_col": "compliq_rate_ew",
        "abbr": "Compulsory liquidation",
        "plural": "compulsory liquidations",
        "h1a": "UK Compulsory Liquidation",
        "h1b": "Statistics",
        "eyebrow": "Compulsory liquidation",
        "definition": ("A compulsory liquidation is a court-ordered winding-up of a "
                       "company, normally after a creditor presents a winding-up "
                       "petition. HMRC is one of the most active petitioners."),
        "trend_intro": ("Because they require a court order, compulsory liquidations "
                        "lag the economic cycle and track how actively creditors are "
                        "pursuing debts. Volumes rose as HMRC resumed active "
                        "enforcement after the pandemic."),
        "notes": [
            "Compulsory liquidations follow legal action, so they reflect creditor "
            "enforcement and court activity as well as underlying trading "
            "conditions. The published statistics do not break the figures down by "
            "who brought the petition.",
            "The count is a volume, not a failure rate. The rate per 10,000 companies "
            "is a 12-month rolling figure, not the chance of a company failing in the "
            "latest month, and it adjusts for the size of the active register.",
        ],
        "citation": ("CompanyDebt. (2026). UK Compulsory Liquidation Statistics. "
                     "CompanyDebt.com. Data sourced from the Insolvency Service and "
                     "Companies House company insolvency statistics."),
        "related": ('The leading indicator for compulsory liquidations is '
                    '<a href="/data/winding-up-petition-tracker/">winding-up petition statistics</a>. '
                    'See also the <a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a> '
                    'and <a href="/data/cvl-statistics/">CVL statistics</a>.'),
    },
    "administration-statistics": {
        "wp_id": 79854,
        "key": "administrations",
        "rate_col": "admin_rate_ew",
        "abbr": "Administration",
        "plural": "administrations",
        "h1a": "UK Company Administration",
        "h1b": "Statistics",
        "eyebrow": "Administration",
        "definition": ("Administration is a procedure run by a licensed insolvency "
                       "practitioner that aims to rescue a company as a going concern, "
                       "or to get a better result for creditors than an immediate "
                       "liquidation. The company gains protection from creditor action "
                       "while a plan is put in place."),
        "trend_intro": ("Administration volumes are small and can swing sharply on a "
                        "single event. Connected real estate companies entering "
                        "administration in clusters lifted the figure three times in "
                        "the first half of 2026, in March, April and June, pushing "
                        "administrations across that period around 41% above 2025 "
                        "levels. Read short-term moves with care."),
        "notes": [
            "Monthly administration volumes are small, so a single cluster of "
            "connected companies can move the figure sharply. Read month-to-month "
            "changes with care, and do not treat a single cluster as evidence of a "
            "general trend in administrations.",
            "The count is a volume, not a failure rate. The rate per 10,000 companies "
            "is a 12-month rolling figure, not the chance of a company failing in the "
            "latest month, and it adjusts for the size of the active register.",
        ],
        "citation": ("CompanyDebt. (2026). UK Company Administration Statistics. "
                     "CompanyDebt.com. Data sourced from the Insolvency Service and "
                     "Companies House company insolvency statistics."),
        "related": ('Administrations are one procedure within the '
                    '<a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>. '
                    'See also <a href="/data/cvl-statistics/">CVL statistics</a> and '
                    '<a href="/data/company-insolvencies-by-sector/">company insolvencies by sector</a>.'),
    },
}


def load_common() -> dict:
    monthly = json.loads((DATA / "monthly_series.json").read_text(encoding="utf-8"))
    meta = json.loads((DATA / "release_metadata.json").read_text(encoding="utf-8"))
    csv_path = sorted(glob.glob(str(DATA / "source_long_run_*.csv")))[-1]
    with open(csv_path, encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    return {"months": monthly["months"], "series": monthly["series"], "meta": meta, "rows": rows}


def last_numeric(rows: list[dict], col: str):
    for r in reversed(rows):
        try:
            return float(r.get(col, ""))
        except (TypeError, ValueError):
            continue
    return None


def pct(n: float) -> str:
    return f"{n:+.1f}%"


def figures(cfg: dict, c: dict) -> dict:
    months, series = c["months"], c["series"]
    vals = series[cfg["key"]]
    total = series["total"]
    latest = vals[-1]
    latest_total = total[-1]
    share = round(latest / latest_total * 100)
    mom = (latest - vals[-2]) / vals[-2] * 100 if vals[-2] else 0.0
    yoy = (latest - vals[-13]) / vals[-13] * 100 if len(vals) > 13 and vals[-13] else 0.0
    rate = last_numeric(c["rows"], cfg["rate_col"])
    peak = max(vals)
    peak_month = month_label(months[vals.index(peak)])
    return {
        "latest": latest,
        "latest_total": latest_total,
        "share": share,
        "mom": mom,
        "yoy": yoy,
        "rate": rate,
        "twelve": sum(vals[-12:]),
        "peak": peak,
        "peak_month": peak_month,
        "month": c["meta"]["latest_month_label"],
        "prev_month": month_label(months[-2]),
    }


def hero_block(cfg: dict, f: dict, meta: dict) -> str:
    return dedent(f"""\
    <section class="cd-w-hero">
      <a class="cd-back" href="/data/"><span aria-hidden="true">&larr;</span> UK Company Insolvency Data</a>
      <div class="cd-hero">
      <div class="cd-hero__copy">
        <h1><span class="cd-h1__line" style="white-space: normal;">{cfg['h1a']}</span> <span class="cd-h1__line" style="white-space: normal;">{cfg['h1b']}</span></h1>
        <p class="cd-lede">In {f['month']} there were {format_number(f['latest'])} {cfg['plural']} in England and Wales, {f['share']}% of all company insolvencies. {cfg['definition']} This page tracks the monthly trend back to 2000, the rate per 10,000 companies and how the procedure sits within the wider insolvency total.</p>
        <dl class="cd-meta-grid">
          <div class="cd-meta-item"><span>Latest data</span><strong>{f['month']}</strong></div>
          <div class="cd-meta-item"><span>Published</span><strong>{meta['publication_date']}</strong></div>
          <div class="cd-meta-item"><span>Next release</span><strong>{meta['next_release_date']}</strong></div>
          <div class="cd-meta-item"><span>Source</span><strong>{meta['source_label']}</strong></div>
        </dl>
        <p class="cd-official-badge"><span aria-hidden="true"></span>{meta['status']}</p>
      </div>

      <aside class="cd-hero__panel" aria-label="Latest figures">
        <p class="cd-kpi-label">Latest figures · England and Wales</p>
        <div class="cd-main-kpi">
          <span class="cd-main-kpi__v">{format_number(f['latest'])}</span>
          <span class="cd-main-kpi__k">{cfg['plural']}, {f['month']}</span>
        </div>
        <div class="cd-change-row">
          <span><strong>{pct(f['mom'])}</strong> vs {f['prev_month']}</span>
          <span><strong>{pct(f['yoy'])}</strong> vs a year earlier</span>
        </div>
        <div class="cd-kpi-divider" aria-hidden="true"></div>
        <div class="cd-mini-kpi-grid">
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{f['share']}%</span><span class="cd-mini-kpi__k">Of all insolvencies</span><span class="cd-mini-kpi__n">{f['month']}</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{f['rate']}</span><span class="cd-mini-kpi__k">Rate per 10,000</span><span class="cd-mini-kpi__n">companies, E&amp;W</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{format_number(f['twelve'])}</span><span class="cd-mini-kpi__k">Last 12 months</span><span class="cd-mini-kpi__n">rolling volume</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{format_number(f['peak'])}</span><span class="cd-mini-kpi__k">Series peak</span><span class="cd-mini-kpi__n">{f['peak_month']}</span></div>
        </div>
      </aside>
      </div>
    </section>
    """)


def trend_block(cfg: dict, c: dict) -> str:
    months, vals = c["months"], c["series"][cfg["key"]]

    def chart(slice_from: int, view: str, refs=None) -> str:
        ms = months[slice_from:]
        vs = vals[slice_from:]
        return build_line_chart(
            ms, vs,
            chart_id=f"{cfg['key']}-{view}",
            title=f"Monthly UK {cfg['plural']}, England and Wales",
            desc=f"Monthly count of {cfg['plural']} in England and Wales.",
            reference_lines=refs,
        )

    try:
        i_covid = months.index("2021-01")
    except ValueError:
        i_covid = max(0, len(months) - 60)
    i_5y = max(0, len(months) - 60)
    refs = [{"period": "2009-01", "label": "2008-09"}, {"period": "2020-04", "label": "Covid"}]

    return dedent(f"""\
    <section class="cd-section cd-w-wide" id="trend">
      <div class="cd-section-head cd-section-head--inline">
        <div>
          <p class="cd-eyebrow">Trend</p>
          <h2>Monthly UK {cfg['plural']} since 2000</h2>
          <p class="cd-section-intro">{cfg['trend_intro']}</p>
        </div>
        <div class="cd-chart-controls" role="tablist" aria-label="Time range">
          <span class="cd-chart-controls__label">View range</span>
          <button type="button" class="cd-chart-tab is-active" data-cd-view="post_covid" aria-pressed="true">Post-Covid</button>
          <button type="button" class="cd-chart-tab" data-cd-view="5y" aria-pressed="false">5 years</button>
          <button type="button" class="cd-chart-tab" data-cd-view="since_2000" aria-pressed="false">Since 2000</button>
        </div>
      </div>
      <figure class="cd-chart-figure">
        <div class="cd-chart-panel cd-chart-panel--hero">
          <div class="cd-chart-view is-active" data-cd-view-pane="post_covid">{chart(i_covid, "post_covid")}</div>
          <div class="cd-chart-view" data-cd-view-pane="5y" hidden>{chart(i_5y, "5y")}</div>
          <div class="cd-chart-view" data-cd-view-pane="since_2000" hidden>{chart(0, "since_2000", refs)}</div>
        </div>
        <figcaption class="cd-figcaption"><strong>Monthly UK {cfg['plural']}, England and Wales, 2000 to {c['meta']['latest_month_label']}.</strong> Seasonally adjusted where the Insolvency Service has identified seasonality. Source: Insolvency Service / Companies House.</figcaption>
      </figure>
    </section>
    """)


def context_block(cfg: dict) -> str:
    notes = "".join(f"<p class=\"cd-side-note__d\">{n}</p>" for n in cfg["notes"])
    if cfg.get("related"):
        notes += f"<p class=\"cd-side-note__d\">{cfg['related']}</p>"
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="about">
      <div class="cd-section-head">
        <p class="cd-eyebrow">How to read this</p>
        <h2>What the {cfg['abbr'].lower() if cfg['abbr'].isupper() else cfg['eyebrow'].lower()} figures show</h2>
      </div>
      <div class="cd-side-notes">{notes}</div>
    </section>
    """)


def table_block(cfg: dict, c: dict, n: int = 13) -> str:
    months, vals, total = c["months"], c["series"][cfg["key"]], c["series"]["total"]
    body = []
    for i in range(len(months) - n, len(months)):
        share = round(vals[i] / total[i] * 100) if total[i] else 0
        body.append(
            f"<tr><th scope=\"row\">{month_label(months[i])}</th>"
            f"<td class=\"cd-num\">{format_number(vals[i])}</td>"
            f"<td class=\"cd-num\">{format_number(total[i])}</td>"
            f"<td class=\"cd-num\">{share}%</td></tr>"
        )
    rows_html = "".join(reversed(body))
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="recent">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Recent months</p>
        <h2>UK {cfg['plural']} over the last 12 months</h2>
      </div>
      <div class="cd-tablewrap">
        <table class="cd-table">
          <caption class="cd-table__caption">Monthly {cfg['plural']} in England and Wales, set against all company insolvencies and shown as a share of the total. Seasonally adjusted. Source: Insolvency Service / Companies House.</caption>
          <thead>
            <tr><th scope="col">Month</th><th scope="col" class="cd-num">{cfg['abbr']}</th><th scope="col" class="cd-num">All insolvencies</th><th scope="col" class="cd-num">Share</th></tr>
          </thead>
          <tbody>{rows_html}</tbody>
        </table>
      </div>
      <p class="cd-source-note">Seasonally adjusted, England and Wales. Source: Insolvency Service / Companies House.</p>
    </section>
    """)


def source_block(cfg: dict, meta: dict) -> str:
    cid = f"cd-citation-{cfg['key']}"
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="source">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Source</p>
        <h2>Source and citation</h2>
      </div>
      <div class="cd-cite-card">
        <div class="cd-cite-card__left">
          <dl>
            <dt>Primary source</dt><dd>Insolvency Service, Company Insolvency Statistics, {meta['latest_month_label']}.</dd>
            <dt>Supporting source</dt><dd>Companies House company register data.</dd>
            <dt>Publication date</dt><dd>{meta['publication_date']}</dd>
            <dt>Next scheduled release</dt><dd>{meta['next_release_date']}</dd>
            <dt>Status</dt><dd>{meta['status']}</dd>
          </dl>
        </div>
        <div class="cd-cite-card__right">
          <p class="cd-eyebrow">How to cite this page</p>
          <p class="cd-cite-text" id="{cid}">{cfg['citation']}</p>
          <button type="button" class="cd-cite-copy" aria-label="Copy citation to clipboard" data-cd-copy="#{cid}">Copy citation</button>
        </div>
      </div>
    </section>
    """)


def assemble(slug: str, c: dict) -> str:
    cfg = PROCEDURES[slug]
    f = figures(cfg, c)
    meta = c["meta"]
    body = "\n".join([
        f"<style>{DASHBOARD_CSS}</style>",
        '<div class="cd-data-hub">',
        masthead_block(),
        hero_block(cfg, f, meta),
        srcstrip_block(),
        trend_block(cfg, c),
        context_block(cfg),
        table_block(cfg, c),
        methodology_block(include_industry_limit=False),
        source_block(cfg, meta),
        final_cta_block(),
        '</div>',
    ])
    return SENTINEL + "\n<!-- wp:html -->\n" + body + "\n<!-- /wp:html -->\n"


def main(argv: list[str]) -> int:
    targets = argv or list(PROCEDURES)
    c = load_common()
    DRAFTS.mkdir(parents=True, exist_ok=True)
    for slug in targets:
        if slug not in PROCEDURES:
            print(f"unknown slug: {slug}")
            return 2
        cfg = PROCEDURES[slug]
        out = DRAFTS / f"{cfg['wp_id']}_{slug}.html"
        out.write_text(assemble(slug, c), encoding="utf-8")
        f = figures(cfg, c)
        print(f"wrote {out.name}: latest={f['latest']} share={f['share']}% rate={f['rate']} ({f['month']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
