"""Generate the sector-breakdown and construction insolvency data pages.

Both reuse the flagship's shared CSS + chrome (masthead, source strip,
methodology, CTA) and the shared chart engine, like procedure_stats.py.

Data:
  - data/insolvency-statistics/sector_breakdown.json  (latest rolling-12m by SIC
    section; drives the ranked bar chart)
  - data/insolvency-statistics/sector_series.json     (annual + monthly by
    section over the full published span, incl. Construction sub-sectors; built by
    scripts/datahub/parse_sector_series.py)

Industry data is published quarterly (Jan/Apr/Jul/Oct) and is annual +
last-3-years monthly, so these are annual-trend pages, not monthly like the
procedure pages.

Usage:
    python scripts/datahub/pages/sector_pages.py
    python scripts/datahub/pages/sector_pages.py company-insolvencies-by-sector
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[3]
SCRIPTS = ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))

from build_insolvency_dashboard import (  # noqa: E402
    DASHBOARD_CSS, masthead_block, srcstrip_block, methodology_block, final_cta_block,
)
from build_insolvency_charts import build_line_chart, build_sector_bars, format_number  # noqa: E402

MONTH_FULL = ["January", "February", "March", "April", "May", "June",
              "July", "August", "September", "October", "November", "December"]


def month_full(period: str) -> str:
    """'2026-05' -> 'May 2026'."""
    y, m = period.split("-")
    return f"{MONTH_FULL[int(m) - 1]} {y}"


DATA = ROOT / "data" / "insolvency-statistics"
DRAFTS = ROOT / "drafts"
SENTINEL = ("<!-- CD-NO-AUTOEDIT: data_reference page generated by "
            "scripts/datahub/pages/sector_pages.py. "
            "Internal-link and article-rewrite pipelines must skip this file. -->")

WP_ID = {
    "company-insolvencies-by-sector": 79855,
    "construction-insolvency-statistics": 79856,
}

# Detail pages that drill into a single trade, grouped under the SIC section
# they belong to. Read from the sic_group_stats registry rather than restated
# here, so a new sector page appears in the drill-down automatically instead of
# relying on someone remembering to update a second list. Construction is the
# exception: it is a section-level page with its own builder in this module.
CONSTRUCTION_DETAIL = {
    "section": "F",
    "slug": "construction-insolvency-statistics",
    "label": "Construction",
}


def detail_pages_by_section() -> dict[str, list[dict]]:
    """{section code: [{slug, label}, ...]} for every sector detail page."""
    from sic_group_stats import SECTORS  # noqa: E402  (late: avoids a cycle)

    grouped: dict[str, list[dict]] = {
        CONSTRUCTION_DETAIL["section"]: [
            {"slug": CONSTRUCTION_DETAIL["slug"], "label": CONSTRUCTION_DETAIL["label"]}
        ]
    }
    for slug, cfg in SECTORS.items():
        grouped.setdefault(cfg["parent_section_code"], []).append(
            {"slug": slug, "label": cfg["eyebrow"]}
        )
    return grouped


def detail_links_block(ser: dict) -> str:
    """Plain links from the section-level ranking down to the individual
    trades. The table above this is SIC-section level (21 sections); the detail
    pages are SIC groups sitting inside those sections, so the mapping is one
    section to many trades and the links have to be grouped to make sense of
    it. Sections are ordered by size, matching the ranking above."""
    grouped = detail_pages_by_section()
    li = len(ser["annual_years"]) - 1
    section_label = {s["code"]: s["label"] for s in ser["sections"]}
    section_size = {s["code"]: (s["annual"][li] or 0) for s in ser["sections"]}
    ordered = sorted(grouped, key=lambda c: section_size.get(c, 0), reverse=True)

    items = ""
    for code in ordered:
        pages = sorted(grouped[code], key=lambda p: p["label"])
        links = ", ".join(
            f'<a href="/data/{p["slug"]}/">{p["label"].lower()}</a>' for p in pages
        )
        items += (
            f'<div class="cd-note-item"><h3>{section_label.get(code, code)}</h3>'
            f'<p class="cd-side-note__d">{links}</p></div>'
        )
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="detail">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Drill down</p>
        <h2>Insolvency statistics for individual sectors</h2>
        <p class="cd-section-intro">The figures above are section level, which is as far as the official ranking goes. These pages go a level deeper into a single trade, with its own monthly and annual figures, the split by insolvency procedure and what the numbers mean for a director in that sector. They are grouped below by the section each one sits inside.</p>
      </div>
      <div class="cd-side-notes">{items}</div>
    </section>""")


def load():
    return (
        json.loads((DATA / "sector_breakdown.json").read_text(encoding="utf-8")),
        json.loads((DATA / "sector_series.json").read_text(encoding="utf-8")),
        json.loads((DATA / "release_metadata.json").read_text(encoding="utf-8")),
    )


def meta_grid(meta: dict) -> str:
    return dedent(f"""\
        <dl class="cd-meta-grid">
          <div class="cd-meta-item"><span>Latest data</span><strong>{meta['latest_month_label']}</strong></div>
          <div class="cd-meta-item"><span>Published</span><strong>{meta['publication_date']}</strong></div>
          <div class="cd-meta-item"><span>Industry update</span><strong>Quarterly</strong></div>
          <div class="cd-meta-item"><span>Source</span><strong>{meta['source_label']}</strong></div>
        </dl>""")


def source_block(slug: str, meta: dict, citation: str) -> str:
    cid = f"cd-citation-{slug}"
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="source">
      <div class="cd-section-head"><p class="cd-eyebrow">Source</p><h2>Source and citation</h2></div>
      <div class="cd-cite-card">
        <div class="cd-cite-card__left">
          <dl>
            <dt>Primary source</dt><dd>Insolvency Service, Company Insolvency Statistics, {meta['latest_month_label']} (Table A1b, by industry).</dd>
            <dt>Supporting source</dt><dd>Companies House company register data.</dd>
            <dt>Publication date</dt><dd>{meta['publication_date']}</dd>
            <dt>Industry breakdown</dt><dd>Published quarterly (January, April, July, October).</dd>
            <dt>Status</dt><dd>{meta['status']}</dd>
          </dl>
        </div>
        <div class="cd-cite-card__right">
          <p class="cd-eyebrow">How to cite this page</p>
          <p class="cd-cite-text" id="{cid}">{citation}</p>
          <button type="button" class="cd-cite-copy" aria-label="Copy citation to clipboard" data-cd-copy="#{cid}">Copy citation</button>
        </div>
      </div>
    </section>""")


# ── Company insolvencies by sector ────────────────────────────────────────

def build_sector(brk: dict, ser: dict, meta: dict) -> str:
    secs = brk["sections"]
    top = secs[0]
    # 21 real SIC sections A-U (exclude the 'V / All others' catch-all bucket).
    n_sections = len([s for s in ser["sections"] if len(s["code"]) == 1 and "A" <= s["code"] <= "U"])
    years = ser["annual_years"]
    li = len(years) - 1

    # Annual-trend table: top 10 sections by latest annual, with 2016/2020/latest.
    ranked = sorted(
        [s for s in ser["sections"] if s["code"] != "Total" and s["annual"][li]],
        key=lambda s: s["annual"][li], reverse=True,
    )[:10]
    y2020 = years.index(2020) if 2020 in years else 0
    rows = []
    for s in ranked:
        a0, a20, aL = s["annual"][0], s["annual"][y2020], s["annual"][li]
        chg = f"{((aL - a0) / a0 * 100):+.0f}%" if a0 else "n/a"
        rows.append(
            f"<tr><th scope=\"row\">{s['label']}</th>"
            f"<td class=\"cd-num\">{format_number(a0)}</td>"
            f"<td class=\"cd-num\">{format_number(a20)}</td>"
            f"<td class=\"cd-num\">{format_number(aL)}</td>"
            f"<td class=\"cd-num\">{chg}</td></tr>"
        )
    trend_rows = "".join(rows)

    hero = dedent(f"""\
    <section class="cd-w-hero">
      <a class="cd-back" href="/data/"><span aria-hidden="true">&larr;</span> UK Company Insolvency Data</a>
      <div class="cd-hero">
      <div class="cd-hero__copy">
        <h1><span class="cd-h1__line" style="white-space: normal;">UK Company Insolvencies</span> <span class="cd-h1__line" style="white-space: normal;">by Sector</span></h1>
        <p class="cd-lede">Across the 12 months to {brk['window_end']}, {top['label_short'].lower()} recorded the most company insolvencies of any industry, with {format_number(top['count'])} cases ({top['share_pct']}% of those with a known sector). This page ranks all {n_sections} industry sections and tracks how each has changed since 2016. Industry figures are not failure rates: larger sectors hold more companies, so they tend to record more insolvencies.</p>
        {meta_grid(meta)}
        <p class="cd-official-badge"><span aria-hidden="true"></span>{meta['status']}</p>
      </div>
      <aside class="cd-hero__panel" aria-label="Latest figures">
        <p class="cd-kpi-label">12 months to {brk['window_end']} · England and Wales</p>
        <div class="cd-main-kpi">
          <span class="cd-main-kpi__v">{top['label_short']}</span>
          <span class="cd-main-kpi__k">most insolvencies of any sector</span>
        </div>
        <div class="cd-change-row">
          <span><strong>{format_number(top['count'])}</strong> cases</span>
          <span><strong>{top['share_pct']}%</strong> of known-sector total</span>
        </div>
        <div class="cd-kpi-divider" aria-hidden="true"></div>
        <div class="cd-mini-kpi-grid">
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{n_sections}</span><span class="cd-mini-kpi__k">Industry sections</span><span class="cd-mini-kpi__n">tracked</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{format_number(brk['total_known_sector'])}</span><span class="cd-mini-kpi__k">Known-sector cases</span><span class="cd-mini-kpi__n">12 months</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{secs[1]['label_short']}</span><span class="cd-mini-kpi__k">2nd highest</span><span class="cd-mini-kpi__n">{secs[1]['share_pct']}% of total</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{secs[2]['label_short']}</span><span class="cd-mini-kpi__k">3rd highest</span><span class="cd-mini-kpi__n">{secs[2]['share_pct']}% of total</span></div>
        </div>
      </aside>
      </div>
    </section>""")

    chart = dedent(f"""\
    <section class="cd-section cd-w-wide" id="ranking">
      <div class="cd-section-head"><p class="cd-eyebrow">Ranking</p><h2>UK company insolvencies by industry, latest 12 months</h2>
        <p class="cd-section-intro">Company insolvencies by SIC industry section over the 12 months to {brk['window_end']}, highest to lowest. Cases with no recorded sector are excluded.</p></div>
      <figure class="cd-chart-figure">
        <div class="cd-chart-panel">{build_sector_bars(brk, chart_id="sector-bars", top_n=12)}</div>
        <figcaption class="cd-figcaption"><strong>Company insolvencies by industry section, 12 months to {brk['window_end']}, England and Wales.</strong> Not seasonally adjusted. Source: Insolvency Service (Table A1b).</figcaption>
      </figure>
    </section>""")

    trend = dedent(f"""\
    <section class="cd-section cd-w-standard" id="trend">
      <div class="cd-section-head"><p class="cd-eyebrow">Trend</p><h2>How sector insolvencies have changed since 2016</h2>
        <p class="cd-section-intro">Annual company insolvencies for the ten largest sectors, England and Wales. The 2020 dip reflects pandemic support; the climb since tracks its withdrawal and the return of creditor enforcement. Construction leads every year, covered in full in the <a href="/data/construction-insolvency-statistics/">construction insolvency statistics</a>; headline totals are in the <a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a> and the procedure split in <a href="/data/cvl-statistics/">CVL statistics</a>.</p></div>
      <div class="cd-tablewrap">
        <table class="cd-table">
          <caption class="cd-table__caption">Annual company insolvencies by industry section, England and Wales, not seasonally adjusted. Source: Insolvency Service (Table A1b).</caption>
          <thead><tr><th scope="col">Sector</th><th scope="col" class="cd-num">2016</th><th scope="col" class="cd-num">2020</th><th scope="col" class="cd-num">{years[li]}</th><th scope="col" class="cd-num">2016 to {years[li]}</th></tr></thead>
          <tbody>{trend_rows}</tbody>
        </table>
      </div>
      <p class="cd-source-note">Not seasonally adjusted, England and Wales. Industry data is published quarterly. Source: Insolvency Service (Table A1b).</p>
    </section>""")

    citation = ("CompanyDebt. (2026). UK Company Insolvencies by Sector. CompanyDebt.com. "
                "Data sourced from the Insolvency Service company insolvency statistics by industry (Table A1b).")
    body = "\n".join([
        f"<style>{DASHBOARD_CSS}</style>", '<div class="cd-data-hub">',
        masthead_block(), hero, srcstrip_block(), chart, trend,
        detail_links_block(ser),
        methodology_block(), source_block("company-insolvencies-by-sector", meta, citation),
        final_cta_block(), '</div>',
    ])
    return SENTINEL + "\n<!-- wp:html -->\n" + body + "\n<!-- /wp:html -->\n"


# ── Construction insolvency statistics ─────────────────────────────────────

def build_construction(brk: dict, ser: dict, meta: dict) -> str:
    f = ser["construction"]["section"]
    years = ser["annual_years"]
    li = len(years) - 1
    months = ser["monthly_months"]
    latest_annual = f["annual"][li]
    peak = max(v for v in f["annual"] if v is not None)
    peak_year = years[f["annual"].index(peak)]
    total_2025 = ser["total"]["annual"][li]
    share = round(latest_annual / total_2025 * 100) if total_2025 else 0
    # rank among sections in latest 12m breakdown
    rank = next((i + 1 for i, s in enumerate(brk["sections"]) if s["code"] == "F"), 1)

    # Monthly construction line chart. The span is taken from the data, not
    # hardcoded, so the chart and the prose around it stay in step after each
    # monthly refresh extends the series.
    monthly_from_year = months[0][:4]
    monthly_to = month_full(months[-1])
    monthly_span = f"from January {monthly_from_year} to {monthly_to}"
    line = build_line_chart(
        months, f["monthly"], chart_id="construction-monthly",
        title="Monthly construction company insolvencies, England and Wales",
        desc=f"Monthly company insolvencies in the construction sector, England and Wales, {monthly_span}.",
    )

    # Sub-sector divisions (41/42/43) latest annual.
    divs = [s for s in ser["construction"]["subsectors"] if s["level"] == "division"]
    sub_rows = "".join(
        f"<tr><th scope=\"row\">{s['label']}</th>"
        f"<td class=\"cd-num\">{format_number(s['annual'][0])}</td>"
        f"<td class=\"cd-num\">{format_number(s['annual'][li])}</td></tr>"
        for s in divs if s["annual"][li]
    )

    # Annual trend table (construction total, all years).
    annual_cells = "".join(
        f"<tr><th scope=\"row\">{y}</th><td class=\"cd-num\">{format_number(f['annual'][i])}</td></tr>"
        for i, y in enumerate(years)
    )

    hero = dedent(f"""\
    <section class="cd-w-hero">
      <a class="cd-back" href="/data/"><span aria-hidden="true">&larr;</span> UK Company Insolvency Data</a>
      <div class="cd-hero">
      <div class="cd-hero__copy">
        <h1><span class="cd-h1__line" style="white-space: normal;">UK Construction Insolvency</span> <span class="cd-h1__line" style="white-space: normal;">Statistics</span></h1>
        <p class="cd-lede">Construction has the most company insolvencies of any UK industry. There were {format_number(latest_annual)} construction company insolvencies in {years[li]}, around {share}% of all company insolvencies that year. This page tracks the construction trend since {years[0]}, the monthly series from January {monthly_from_year} to {monthly_to} and the split across building, civil engineering and specialised trades.</p>
        {meta_grid(meta)}
        <p class="cd-official-badge"><span aria-hidden="true"></span>{meta['status']}</p>
      </div>
      <aside class="cd-hero__panel" aria-label="Latest figures">
        <p class="cd-kpi-label">Construction (SIC section F) · England and Wales</p>
        <div class="cd-main-kpi">
          <span class="cd-main-kpi__v">{format_number(latest_annual)}</span>
          <span class="cd-main-kpi__k">construction insolvencies, {years[li]}</span>
        </div>
        <div class="cd-change-row">
          <span><strong>#{rank}</strong> highest of any sector</span>
          <span><strong>{share}%</strong> of all insolvencies</span>
        </div>
        <div class="cd-kpi-divider" aria-hidden="true"></div>
        <div class="cd-mini-kpi-grid">
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{format_number(f['annual'][0])}</span><span class="cd-mini-kpi__k">In 2016</span><span class="cd-mini-kpi__n">start of series</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{format_number(peak)}</span><span class="cd-mini-kpi__k">Series peak</span><span class="cd-mini-kpi__n">{peak_year}</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{format_number(f['annual'][years.index(2020)])}</span><span class="cd-mini-kpi__k">In 2020</span><span class="cd-mini-kpi__n">Covid support</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{len(divs)}</span><span class="cd-mini-kpi__k">Sub-sectors</span><span class="cd-mini-kpi__n">building, civil, trades</span></div>
        </div>
      </aside>
      </div>
    </section>""")

    chart = dedent(f"""\
    <section class="cd-section cd-w-wide" id="trend">
      <div class="cd-section-head"><p class="cd-eyebrow">Trend</p><h2>Monthly construction insolvencies since {monthly_from_year}</h2>
        <p class="cd-section-intro">Company insolvencies in the construction sector, England and Wales. Monthly figures run from January {monthly_from_year} to {monthly_to}; the annual totals below give the same period at a glance. Construction is the largest sector across the <a href="/data/company-insolvencies-by-sector/">company insolvencies by sector</a> data and the <a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>; supplier cash-flow pressure is tracked in the <a href="/data/payment-practices-late-payment/">late payment statistics</a>.</p></div>
      <figure class="cd-chart-figure">
        <div class="cd-chart-panel cd-chart-panel--longrun">{line}</div>
        <figcaption class="cd-figcaption"><strong>Monthly construction company insolvencies, England and Wales, {monthly_span}.</strong> Not seasonally adjusted. Source: Insolvency Service (Table A1b).</figcaption>
      </figure>
    </section>""")

    subs = dedent(f"""\
    <section class="cd-section cd-w-standard" id="subsectors">
      <div class="cd-section-head"><p class="cd-eyebrow">Sub-sectors</p><h2>Construction insolvencies by sub-sector</h2>
        <p class="cd-section-intro">Construction divides into the construction of buildings, civil engineering and specialised construction activities (the largest, covering trades such as electrical and plumbing).</p></div>
      <div class="cd-tablewrap">
        <table class="cd-table">
          <caption class="cd-table__caption">Construction company insolvencies by sub-sector, England and Wales, not seasonally adjusted. Source: Insolvency Service (Table A1b).</caption>
          <thead><tr><th scope="col">Sub-sector</th><th scope="col" class="cd-num">2016</th><th scope="col" class="cd-num">{years[li]}</th></tr></thead>
          <tbody>{sub_rows}</tbody>
        </table>
      </div>
    </section>""")

    annual = dedent(f"""\
    <section class="cd-section cd-w-standard" id="annual">
      <div class="cd-section-head"><p class="cd-eyebrow">Annual</p><h2>Construction insolvencies by year, 2016 to {years[li]}</h2></div>
      <div class="cd-tablewrap">
        <table class="cd-table">
          <caption class="cd-table__caption">Annual construction company insolvencies, England and Wales, not seasonally adjusted. Source: Insolvency Service (Table A1b).</caption>
          <thead><tr><th scope="col">Year</th><th scope="col" class="cd-num">Construction insolvencies</th></tr></thead>
          <tbody>{annual_cells}</tbody>
        </table>
      </div>
      <p class="cd-source-note">Not seasonally adjusted, England and Wales. Industry data is published quarterly. Source: Insolvency Service (Table A1b).</p>
    </section>""")

    citation = ("CompanyDebt. (2026). UK Construction Insolvency Statistics. CompanyDebt.com. "
                "Data sourced from the Insolvency Service company insolvency statistics by industry (Table A1b).")
    body = "\n".join([
        f"<style>{DASHBOARD_CSS}</style>", '<div class="cd-data-hub">',
        masthead_block(), hero, srcstrip_block(), chart, subs, annual,
        methodology_block(), source_block("construction-insolvency-statistics", meta, citation),
        final_cta_block(), '</div>',
    ])
    return SENTINEL + "\n<!-- wp:html -->\n" + body + "\n<!-- /wp:html -->\n"


BUILDERS = {
    "company-insolvencies-by-sector": build_sector,
    "construction-insolvency-statistics": build_construction,
}


def main(argv: list[str]) -> int:
    targets = argv or list(BUILDERS)
    brk, ser, meta = load()
    DRAFTS.mkdir(parents=True, exist_ok=True)
    for slug in targets:
        if slug not in BUILDERS:
            print(f"unknown slug: {slug}")
            return 2
        out = DRAFTS / f"{WP_ID[slug]}_{slug}.html"
        out.write_text(BUILDERS[slug](brk, ser, meta), encoding="utf-8")
        print(f"wrote {out.name} ({out.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
