"""Generate single-SIC-sector insolvency data pages for the data hub.

Reusable engine for any sector with a clean 3-digit SIC group in Table 1c
(the Insolvency Service's by-industry table): one config entry, one page. This
is the generic version of the bespoke Construction page in sector_pages.py —
use this for every new sector instead of hand-rolling a builder, unless the
sector needs a bespoke sub-sector breakdown like Construction has.

Leads with the CURRENT picture (year-to-date vs the same months last year,
rolling 12 months, latest single month) rather than the last full calendar
year — Table 1c publishes the industry breakdown monthly (through the latest
headline month), not quarterly as earlier drafts of this page claimed; only
the supplementary procedure-split tables are quarterly. The full-year annual
total is still shown, but as trailing context, not the headline.

To stay visually consistent with the rest of the family, pages reuse the
flagship's shared CSS/chrome (masthead, source strip, methodology, final CTA)
and the shared line-chart engine.

Data: data/insolvency-statistics/sector_series.json "groups" (all ~272
3-digit SIC groups, annual since 2016 + monthly since 2023; built by
scripts/datahub/parse_sector_series.py) + release_metadata.json.

Usage:
    python scripts/datahub/pages/sic_group_stats.py                            # all
    python scripts/datahub/pages/sic_group_stats.py furniture-insolvency-statistics
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[3]
SCRIPTS = ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))

from build_insolvency_dashboard import (  # noqa: E402
    DASHBOARD_CSS, masthead_block, srcstrip_block, methodology_block, final_cta_block,
)
from build_insolvency_charts import build_line_chart, format_number  # noqa: E402

DATA = ROOT / "data" / "insolvency-statistics"
DRAFTS = ROOT / "drafts"
SENTINEL = ("<!-- CD-NO-AUTOEDIT: data_reference page generated by "
            "scripts/datahub/pages/sic_group_stats.py. "
            "Internal-link and article-rewrite pipelines must skip this file. -->")

MONTH_FULL = ["January", "February", "March", "April", "May", "June",
              "July", "August", "September", "October", "November", "December"]


def month_full(period: str) -> str:
    """'2026-05' -> 'May 2026'."""
    y, m = period.split("-")
    return f"{MONTH_FULL[int(m) - 1]} {y}"


# Static, number-free copy per sector. Live figures are computed at build time
# from sector_series.json "groups" by sic_code. Add a new sector by adding an
# entry here + a WP page (scripts/datahub/create_staging_pages.py) + the
# cc_builder/mu-plugin registration (see docs/data-hub/page-specs.md).
#
# "pressure" entries are editorial judgement (general, well-established sector
# economics), NOT sourced statistics — do not add a specific number to one of
# these unless it has been verified against a primary source and wired through
# figures()/sector_fact() like every other number on the page. A plausible
# invented figure is worse than no figure.
SECTORS = {
    "furniture-insolvency-statistics": {
        "wp_id": 80098,
        "sic_code": "310",
        "division_code": "31",
        "parent_section_code": "C",
        "parent_section_label": "manufacturing",
        "h1a": "UK Furniture Manufacturing",
        "h1b": "Insolvency Statistics",
        "h1_subtitle": "Latest detailed figures for England and Wales",
        "eyebrow": "Furniture manufacturing",
        "keyword": "furniture manufacturing",
        "singular": "furniture manufacturer",
        "plural": "furniture-manufacturing companies",
        "scope_description": ("household, office, kitchen and shop furniture and "
                              "mattress manufacturing"),
        "exclusion_note": "Furniture retailers and wholesalers are recorded separately.",
        "notes": [
            "Furniture manufacturing is a small sector by company count, so monthly "
            "figures can move sharply on a handful of cases. Read short-term changes "
            "with care and prefer the year-to-date or 12-month rolling total.",
            "The count is a volume, not a failure rate. It is not adjusted for how "
            "many furniture manufacturers are registered, so it cannot be read as a "
            "sector-wide risk of insolvency.",
            "This is manufacturing only (SIC 310). Furniture wholesalers and retailers "
            "sit under separate, broader SIC codes and are not included here.",
        ],
        "practitioner_view": [
            "In the cases we see, pressure commonly builds through reduced orders, "
            "fixed production costs and supplier terms that consume working capital "
            "before directors seek advice.",
            "Furniture is also one of the first big-ticket purchases households defer "
            "when confidence dips, so demand can weaken well before the wider economy "
            "turns down.",
        ],
        "pressure": [
            {
                "h3": "Discretionary consumer demand",
                "body": ("Furniture is a considered, big-ticket purchase, so household "
                         "spending on it is one of the first things cut when confidence "
                         "or disposable income comes under pressure, ahead of more "
                         "routine spending categories."),
            },
            {
                "h3": "Imported materials and currency exposure",
                "body": ("Many manufacturers depend on imported timber, hardware, "
                         "fabrics, foam or completed components, leaving margins "
                         "exposed to freight costs and exchange-rate movements."),
            },
        ],
        "citation": ("CompanyDebt. (2026). UK Furniture Manufacturing Insolvency "
                     "Statistics. CompanyDebt.com. Data sourced from the Insolvency "
                     "Service company insolvency statistics by industry (Table 1c)."),
        "related": ('Furniture manufacturing sits within the wider '
                    '<a href="/data/company-insolvencies-by-sector/">company insolvencies by sector</a> '
                    'data, alongside manufacturing generally. See also the '
                    '<a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>.'),
    },
    "restaurant-insolvency-statistics": {
        "wp_id": 80134,
        "sic_code": "561",
        "division_code": "56",
        "parent_section_code": "I",
        "parent_section_label": "accommodation and food service",
        "h1a": "UK Restaurant",
        "h1b": "Insolvency Statistics",
        "h1_subtitle": "Latest detailed figures for England and Wales",
        "eyebrow": "Restaurants",
        "keyword": "restaurant",
        "singular": "restaurant",
        "plural": "restaurants and mobile food service businesses",
        "scope_description": ("restaurants, cafes and mobile or takeaway food "
                              "service businesses"),
        "exclusion_note": "Pubs, bars and other beverage-serving venues are recorded separately (SIC group 563).",
        "notes": [
            "Restaurants are one of the largest sectors on this site by insolvency "
            "count, so the monthly trend is more stable than a small sector's, but "
            "single-month moves can still reflect one-off closures rather than a "
            "shift in conditions.",
            "The count is a volume, not a failure rate. It is not adjusted for how "
            "many restaurants are registered, so it cannot be read as a sector-wide "
            "risk of insolvency.",
            "This is restaurants and mobile food service only (SIC 561). Pubs, bars "
            "and hotels sit under separate SIC codes and are not included here.",
        ],
        "practitioner_view": [
            "In the cases we see, restaurant insolvency rarely starts with one "
            "disastrous month. More often, the business absorbs rising food, "
            "wage and energy costs for too long, then uses tax arrears, "
            "supplier credit or short-term borrowing to cover the gap.",
            "By the time directors seek advice, the dining room may still look "
            "busy. The more useful test is whether each week's trading leaves "
            "enough cash to meet the next payroll, VAT payment, rent demand and "
            "supplier run. Early advice matters because the available options "
            "narrow quickly once suppliers place accounts on stop, HMRC begins "
            "enforcement action or a landlord takes steps to recover the "
            "premises.",
        ],
        "pressure_heading": "Why restaurant insolvencies remain high",
        "pressure": [
            {
                "h3": "Labour costs have risen again",
                "body": [
                    ("The National Living Wage increased by 4.1% to £12.71 an "
                     "hour from April 2026. Restaurants are labour-intensive "
                     "businesses, so the change raises the wage floor across "
                     "every opening hour and can affect pay differentials "
                     "further up the payroll too."),
                    ("Employer National Insurance also remains at 15%, with "
                     "contributions generally starting above the £5,000 "
                     "annual secondary threshold. Payroll costs rise before a "
                     "restaurant knows whether it can recover them through "
                     "higher menu prices or extra covers."),
                ],
            },
            {
                "h3": "Food, energy and other operating costs remain difficult",
                "body": [
                    ("ONS survey data shows these pressures are widespread "
                     "across accommodation and food services: in early May "
                     "2026, 78% of businesses in the wider sector reported at "
                     "least one challenge affecting turnover, with half "
                     "citing the cost of materials, half citing labour costs "
                     "and 44% citing economic uncertainty."),
                    ("The same survey found 62% had seen the prices of goods "
                     "or services they buy increase in April 2026, and by "
                     "late June, 88% expressed some concern about energy "
                     "prices, the highest proportion of any industry. These "
                     "figures cover accommodation and food services "
                     "generally, not restaurants alone, but provide current "
                     "context for the figures above."),
                ],
            },
            {
                "h3": "Menu prices cannot rise without affecting demand",
                "body": [
                    ("Passing higher costs to customers is not a complete "
                     "solution. A menu increase may protect the margin on "
                     "each dish while reducing how often customers visit or "
                     "what they order."),
                    ("That leaves operators balancing two risks: holding "
                     "prices too low to cover the cost of trading, or "
                     "raising them far enough to weaken demand. In March "
                     "2026, 34% of accommodation and food service businesses "
                     "reported increasing the prices they charged, the "
                     "highest proportion of any industry in that survey "
                     "wave."),
                ],
            },
            {
                "h3": "Fixed costs continue through quiet trading",
                "body": [
                    ("Food orders and staff rotas can be adjusted to a "
                     "degree. Rent, business rates, finance payments and "
                     "many utility costs cannot. A few quiet weeks can "
                     "remove the cash buffer needed for the next payroll, "
                     "VAT payment or supplier run."),
                    ("Footfall-dependent sites are especially exposed: a "
                     "restaurant can have a sound concept and regular "
                     "customers, but still be unviable under the rent, debt "
                     "or cost structure attached to that particular site."),
                ],
            },
        ],
        "parent_rate_current": "268", "parent_rate_year": 2025,
        "parent_rate_peak": "314", "parent_rate_peak_year": 2023,
        "commercial_transition": [
            ("A fall in industry insolvencies does not make an individual "
             "cash-flow problem less urgent. If a restaurant cannot meet "
             "payroll, VAT, rent or supplier payments as they fall due, the "
             "useful question is whether the underlying trade is viable "
             "before debt repayments and arrears."),
            ('Acting early gives directors more scope to negotiate a '
             '<a href="/hmrc/time-to-pay-hmrc/">Time to Pay arrangement</a> '
             'with HMRC, agree terms with landlords and suppliers, or '
             'consider a formal rescue procedure such as a '
             '<a href="/company-rescue-solutions/company-voluntary-arrangement/">Company Voluntary Arrangement</a> '
             'or <a href="/company-administration/">administration</a>.'),
            ('Once a <a href="/winding-up-petitions/dealing-with-an-hmrc-winding-up-petition/">winding-up petition</a>, '
             'forfeiture action or supplier stoppage begins, those choices '
             'narrow quickly, and '
             '<a href="/liquidation/creditors-voluntary-liquidation/">creditors\' voluntary liquidation</a> '
             'may be the only realistic route left.'),
        ],
        "citation": ("CompanyDebt. (2026). UK Restaurant Insolvency Statistics. "
                     "CompanyDebt.com. Data sourced from the Insolvency Service "
                     "company insolvency statistics by industry (Table 1c)."),
        "related": ('Restaurants sit within the wider '
                    '<a href="/data/company-insolvencies-by-sector/">company insolvencies by sector</a> '
                    'data, alongside accommodation and food service generally. See also '
                    'the <a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>.'),
    },
    "road-haulage-insolvency-statistics": {
        "wp_id": 80136,
        "sic_code": "494",
        "division_code": "49",
        "parent_section_code": "H",
        "parent_section_label": "transportation and storage",
        "h1a": "UK Road Haulage",
        "h1b": "Insolvency Statistics",
        "h1_subtitle": "Latest detailed figures for England and Wales",
        "eyebrow": "Road haulage",
        "keyword": "road haulage",
        "singular": "haulage company",
        "plural": "road haulage and removals companies",
        "scope_description": "freight transport by road and removal services",
        "exclusion_note": "Storage, warehousing and postal or courier activities are recorded separately.",
        "notes": [
            "Monthly road haulage insolvencies can move because of registration "
            "timing or a small number of related company failures, not "
            "necessarily because of a change in trading conditions that same "
            "month. Prefer the year-to-date or 12-month rolling total for the "
            "steadier read.",
            "The count is a volume, not a failure rate. It is not adjusted for how "
            "many haulage companies are registered, so it cannot be read as a "
            "sector-wide risk of insolvency.",
            "This is road freight and removals only (SIC 494). Storage, "
            "warehousing, postal and courier activities sit under separate SIC "
            "codes and are not included here.",
        ],
        "practitioner_view": [
            "In the cases we see, a haulage company can be busy and still run "
            "out of cash. The warning signs are often visible in the gap "
            "between work completed and money collected: fuel cards are close "
            "to their limits, VAT or PAYE has been used to fund the next week, "
            "and vehicle repairs are being deferred because there is no spare "
            "cash.",
            "The immediate trigger may be a slow-paying customer, a failed "
            "engine or a fuel-price movement, but the underlying problem is "
            "usually that the margin and working-capital buffer were already "
            "too small to absorb it.",
            "Directors should focus on cash generated per vehicle and per "
            "contract, not turnover alone: a route that keeps a truck moving "
            "but does not cover fuel, driver time, finance, maintenance and "
            "overhead is increasing the problem rather than solving it.",
        ],
        "pressure_heading": "Why road haulage companies remain under pressure",
        "pressure_intro": [
            "Haulage is a high-turnover business that can produce very little "
            "spare cash. Fuel, drivers, vehicle finance, insurance and "
            "maintenance have to be paid before or during the job, while the "
            "customer may not pay the invoice until weeks later.",
            "Growth does not always solve this: taking on more work can "
            "increase the cash tied up in diesel, wages and subcontractors "
            "before the extra revenue reaches the bank.",
        ],
        "pressure": [
            {
                "h3": "Freight activity weakened in 2025",
                "body": [
                    ("Demand conditions softened during 2025. GB-registered "
                     "HGVs lifted 1.53 billion tonnes of goods, 3% less than "
                     "in 2024. Goods moved fell 4% to 162 billion "
                     "tonne-kilometres, while vehicle kilometres fell 2% to "
                     "19.0 billion."),
                    ("Lower freight activity does not affect every operator "
                     "equally, but it can make fleet utilisation and contract "
                     "pricing more difficult: a vehicle that is financed, "
                     "insured and staffed still needs enough loaded miles to "
                     "cover those costs. HGVs also ran empty for 31% of total "
                     "vehicle kilometres in 2025, a reminder of how much fleet "
                     "time can generate cost without carrying a paying load."),
                    ("These DfT figures cover GB-registered HGVs operating in "
                     "the UK and are sector context, not part of the England "
                     "and Wales insolvency count."),
                ],
            },
            {
                "h3": "Fuel costs can change faster than contract rates",
                "body": [
                    ("Fuel remains one of the sector's least controllable "
                     "costs. The official UK pump-price series shows diesel "
                     "rising from around 140.82p per litre on 2 February 2026 "
                     "to 192.14p on 13 April, before falling to 164.77p by 6 "
                     "July."),
                    ("The fall from the April peak brought some relief, but "
                     "the speed of the movement is the important point: an "
                     "operator may price a contract or set a fuel surcharge "
                     "before knowing what diesel will cost when the work is "
                     "completed."),
                    ("In late June 2026, 86% of transportation and storage "
                     "businesses expressed some concern about fuel prices, "
                     "the highest proportion of any industry in that ONS "
                     "survey. That figure covers transportation and storage "
                     "generally, and the retail pump price is not "
                     "necessarily what every operator pays on a bulk "
                     "contract."),
                ],
            },
            {
                "h3": "Driver recruitment and retention still carry a cost",
                "body": [
                    ("The acute driver shortage has eased from its 2021 peak, "
                     "but it has not disappeared. In the fourth quarter of "
                     "2025, 26% of HGV businesses reported driver vacancies, "
                     "compared with 24% a year earlier."),
                    ("Among businesses with vacancies, 42% cited better pay "
                     "or benefits elsewhere, 38% cited drivers leaving the "
                     "industry and 33% cited retirement, and almost a "
                     "quarter said driver availability had caused a missed "
                     "delivery in the previous week."),
                    ("Driver cost is therefore not only the wage itself: an "
                     "unfilled shift can leave a financed vehicle idle or "
                     "force the operator to use a more expensive temporary "
                     "or subcontracted alternative."),
                ],
            },
            {
                "h3": "Payment timing creates a working-capital gap",
                "body": [
                    ("The cash-flow problem begins when the operator pays "
                     "for the job before being paid for the job. Fuel, "
                     "wages, tolls and subcontractor charges are immediate "
                     "or frequent, while customer invoices may remain "
                     "outstanding for weeks."),
                    ("A profitable contract can still create a cash "
                     "shortage if the business takes on more work without "
                     "enough working capital. Slow payment by one large "
                     "customer can be particularly damaging where that "
                     "customer accounts for a substantial share of the "
                     "fleet's mileage."),
                ],
            },
            {
                "h3": "Vehicle finance, repairs and downtime continue regardless of revenue",
                "body": [
                    ("A truck that is off the road stops earning, but most "
                     "of its costs continue. Finance, insurance, "
                     "operator-licence obligations and some staffing costs "
                     "remain while the operator also pays for the repair."),
                    ("Smaller fleets have less room to absorb that "
                     "interruption. Losing one vehicle from a three-truck "
                     "fleet is a very different event from losing one from "
                     "a fleet of 100, even where the repair bill is "
                     "identical."),
                ],
            },
        ],
        "longer_term_narrative": [
            "Road haulage insolvencies rose from 138 in 2016 to 282 in 2019. "
            "Recorded failures fell to 203 in 2020, when pandemic support "
            "and restrictions disrupted the normal insolvency cycle, before "
            "rising sharply to 417 in 2022 and a peak of 501 in 2023.",
            "Insolvencies then fell to 472 in 2024 and 407 in 2025. The "
            "two-year fall is significant, but 2025 still recorded 125 more "
            "failures than 2019.",
        ],
        "policy_update": {
            "heading": "Current policy update: HGV Vehicle Excise Duty relief",
            "paras": [
                ('Most eligible HGVs renewing their Vehicle Excise Duty '
                 'between 1 July 2026 and 30 June 2027 qualify for a '
                 '<a href="https://www.gov.uk/government/publications/12-month-vehicle-excise-duty-ved-holiday-for-heavy-goods-vehicles-hgvs/temporary-vehicle-excise-duty-rates-for-heavy-goods-vehicles">temporary annual rate of £1</a>. '
                 'The government introduced the 12-month measure in '
                 'recognition of the sector\'s exposure to higher fuel '
                 'costs.'),
                ("This reduces one fixed fleet cost, but it does not remove "
                 "the larger pressures from diesel, wages, finance, repairs "
                 "and customer payment terms. It should be read as targeted "
                 "relief, not evidence that the sector's financial problems "
                 "have been resolved, and it does not explain insolvencies "
                 "registered before it takes effect."),
            ],
        },
        "commercial_transition": [
            ("Falling sector insolvencies do not make an individual "
             "cash-flow problem less urgent. If the company cannot meet "
             "fuel-card payments, payroll, VAT, vehicle finance or supplier "
             "bills as they fall due, the first question is whether its "
             "routes and contracts are viable before debt repayments and "
             "arrears."),
            ('Acting early gives directors more scope to renegotiate '
             'payment terms, dispose of underused vehicles, approach HMRC '
             'about a <a href="/hmrc/time-to-pay-hmrc/">Time to Pay '
             'arrangement</a>, or consider a formal rescue procedure such '
             'as a <a href="/company-rescue-solutions/company-voluntary-arrangement/">Company '
             'Voluntary Arrangement</a> or '
             '<a href="/company-administration/">administration</a>.'),
            ('Once fuel cards are withdrawn, vehicles are repossessed or a '
             '<a href="/winding-up-petitions/dealing-with-an-hmrc-winding-up-petition/">winding-up petition</a> '
             'is issued, the available options narrow quickly, and '
             '<a href="/liquidation/creditors-voluntary-liquidation/">creditors\' '
             'voluntary liquidation</a> may then be the only realistic '
             'route left.'),
        ],
        "citation": ("CompanyDebt. (2026). UK Road Haulage Insolvency Statistics. "
                     "CompanyDebt.com. Data sourced from the Insolvency Service "
                     "company insolvency statistics by industry (Table 1c)."),
        "related": ('Road haulage sits within the wider '
                    '<a href="/data/company-insolvencies-by-sector/">company insolvencies by sector</a> '
                    'data, alongside transportation and storage generally. See also the '
                    '<a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>.'),
    },
    "recruitment-agency-insolvency-statistics": {
        "wp_id": 80137,
        "sic_code": "781",
        "division_code": "78",
        "parent_section_code": "N",
        "parent_section_label": "administrative and support services",
        "h1a": "UK Recruitment Agency",
        "h1b": "Insolvency Statistics",
        "h1_subtitle": "Latest detailed figures for England and Wales",
        "eyebrow": "Recruitment agencies",
        "keyword": "recruitment agency",
        "singular": "recruitment agency",
        "plural": "permanent-placement recruitment agencies",
        "scope_description": "recruitment agencies placing candidates into permanent roles",
        "exclusion_note": "Temporary and agency staffing businesses are recorded separately (SIC group 782).",
        "notes": [
            "Recruitment agency insolvencies can move sharply on a small number of "
            "cases, since it is a mid-sized sector. Prefer the year-to-date or "
            "12-month rolling total for the steadier read.",
            "The count is a volume, not a failure rate. It is not adjusted for how "
            "many agencies are registered, so it cannot be read as a sector-wide "
            "risk of insolvency.",
            "This is permanent-placement recruitment only (SIC 781). Temporary "
            "staffing agencies sit under a separate SIC code and are covered on "
            "their own page.",
        ],
        "practitioner_view": [
            "In the cases we see, recruitment agencies scale their cost base, "
            "particularly consultant headcount, to match a hiring boom, then are "
            "exposed when client hiring slows and fee income drops away almost "
            "immediately.",
            "Placement fee income is inherently lumpy. An agency with a handful of "
            "large clients can see a material share of its pipeline disappear when "
            "just one of them pauses hiring.",
        ],
        "pressure": [
            {
                "h3": "Direct exposure to hiring confidence",
                "body": ("Placement fee income depends entirely on clients actively "
                         "hiring, so it falls away almost immediately when clients "
                         "freeze recruitment, with little notice and no way to "
                         "recover the lost pipeline."),
            },
            {
                "h3": "Thin working capital buffers",
                "body": ("Agencies are typically light on fixed assets and cash "
                         "between placements, so a run of quiet months can exhaust "
                         "reserves faster than in sectors with more physical assets "
                         "to fall back on."),
            },
        ],
        "citation": ("CompanyDebt. (2026). UK Recruitment Agency Insolvency "
                     "Statistics. CompanyDebt.com. Data sourced from the Insolvency "
                     "Service company insolvency statistics by industry (Table 1c)."),
        "related": ('Recruitment agencies sit within the wider '
                    '<a href="/data/company-insolvencies-by-sector/">company insolvencies by sector</a> '
                    'data, alongside administrative and support services generally. See also '
                    '<a href="/data/temporary-staffing-agency-insolvency-statistics/">temporary staffing agency insolvency statistics</a> '
                    'and the <a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>.'),
    },
    "temporary-staffing-agency-insolvency-statistics": {
        "wp_id": 80138,
        "sic_code": "782",
        "division_code": "78",
        "parent_section_code": "N",
        "parent_section_label": "administrative and support services",
        "h1a": "UK Temporary Staffing Agency",
        "h1b": "Insolvency Statistics",
        "h1_subtitle": "Latest detailed figures for England and Wales",
        "eyebrow": "Temporary staffing agencies",
        "keyword": "temporary staffing agency",
        "singular": "temporary staffing agency",
        "plural": "temporary and agency staffing businesses",
        "scope_description": "temporary and agency staffing businesses",
        "exclusion_note": "Permanent-placement recruitment agencies are recorded separately (SIC group 781).",
        "notes": [
            "Temporary staffing is a smaller sector by insolvency count, so monthly "
            "figures can move sharply on a handful of cases. Prefer the "
            "year-to-date or 12-month rolling total for the steadier read.",
            "The count is a volume, not a failure rate. It is not adjusted for how "
            "many staffing agencies are registered, so it cannot be read as a "
            "sector-wide risk of insolvency.",
            "This is temporary and agency staffing only (SIC 782). Permanent-"
            "placement recruitment agencies sit under a separate SIC code and are "
            "covered on their own page.",
        ],
        "practitioner_view": [
            "In the cases we see, the defining pressure is the payroll funding "
            "gap: agencies must pay temporary workers weekly, often before the "
            "client invoice for that work has even been raised, let alone paid.",
            "That gap is usually bridged with invoice finance. When a funder "
            "tightens terms or a large client's payment slips, the agency can be "
            "funding a payroll it has no immediate way to recover.",
        ],
        "pressure": [
            {
                "h3": "The payroll funding gap",
                "body": ("Temporary workers are typically paid weekly, well ahead "
                         "of when client invoices for that work are settled, so "
                         "agencies carry a permanent funding gap that widens as "
                         "volumes grow."),
            },
            {
                "h3": "Volatile, fast-moving client demand",
                "body": ("Temporary staffing is often the first cost a client cuts "
                         "when demand softens and the first they restore when it "
                         "picks up, making booked volumes swing faster than in most "
                         "other sectors."),
            },
        ],
        "citation": ("CompanyDebt. (2026). UK Temporary Staffing Agency Insolvency "
                     "Statistics. CompanyDebt.com. Data sourced from the Insolvency "
                     "Service company insolvency statistics by industry (Table 1c)."),
        "related": ('Temporary staffing sits within the wider '
                    '<a href="/data/company-insolvencies-by-sector/">company insolvencies by sector</a> '
                    'data, alongside administrative and support services generally. See also '
                    '<a href="/data/recruitment-agency-insolvency-statistics/">recruitment agency insolvency statistics</a> '
                    'and the <a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>.'),
    },
    "motor-vehicle-repair-insolvency-statistics": {
        "wp_id": 80139,
        "sic_code": "452",
        "division_code": "45",
        "parent_section_code": "G",
        "parent_section_label": "wholesale and retail trade and repair of motor vehicles",
        "h1a": "UK Motor Vehicle Repair",
        "h1b": "Insolvency Statistics",
        "h1_subtitle": "Latest detailed figures for England and Wales",
        "eyebrow": "Motor vehicle repair",
        "keyword": "motor vehicle repair",
        "singular": "garage",
        "plural": "motor vehicle repair and maintenance businesses",
        "scope_description": "garages and workshops carrying out motor vehicle maintenance and repair",
        "exclusion_note": "Sale of motor vehicles and parts is recorded separately.",
        "notes": [
            "Motor vehicle repair insolvencies can move on a handful of cases "
            "month to month. Prefer the year-to-date or 12-month rolling total for "
            "the steadier read.",
            "The count is a volume, not a failure rate. It is not adjusted for how "
            "many garages are registered, so it cannot be read as a sector-wide "
            "risk of insolvency.",
            "This is repair and maintenance only (SIC 452). Sale of vehicles and "
            "parts sits under separate SIC codes and is not included here.",
        ],
        "practitioner_view": [
            "In the cases we see, independent garages are being squeezed between "
            "rising parts and equipment costs and competition from manufacturer-"
            "franchised dealers, who hold newer, higher-margin warranty work.",
            "The shift toward electric and increasingly complex vehicles adds a "
            "capital cost independents often cannot spread as easily as a "
            "multi-site franchised group.",
        ],
        "pressure": [
            {
                "h3": "Rising parts and equipment costs",
                "body": ("Genuine parts, diagnostic equipment and the specialist "
                         "tooling needed for newer and electric vehicles have risen "
                         "in cost faster than many independent garages can pass on "
                         "through labour rates."),
            },
            {
                "h3": "Competition from franchised dealers",
                "body": ("Manufacturer warranty and servicing schemes pull newer, "
                         "higher-margin vehicle work toward franchised dealers, "
                         "leaving independent garages more reliant on older, "
                         "lower-margin repair work."),
            },
        ],
        "citation": ("CompanyDebt. (2026). UK Motor Vehicle Repair Insolvency "
                     "Statistics. CompanyDebt.com. Data sourced from the Insolvency "
                     "Service company insolvency statistics by industry (Table 1c)."),
        "related": ('Motor vehicle repair sits within the wider '
                    '<a href="/data/company-insolvencies-by-sector/">company insolvencies by sector</a> '
                    'data, alongside wholesale and retail trade generally. See also the '
                    '<a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>.'),
    },
    "cleaning-company-insolvency-statistics": {
        "wp_id": 80140,
        "sic_code": "812",
        "division_code": "81",
        "parent_section_code": "N",
        "parent_section_label": "administrative and support services",
        "h1a": "UK Cleaning Company",
        "h1b": "Insolvency Statistics",
        "h1_subtitle": "Latest detailed figures for England and Wales",
        "eyebrow": "Cleaning contractors",
        "keyword": "cleaning company",
        "singular": "cleaning contractor",
        "plural": "commercial and industrial cleaning contractors",
        "scope_description": "commercial and industrial cleaning contractors",
        "exclusion_note": "Domestic cleaning services and waste collection are recorded under separate SIC codes.",
        "notes": [
            "Cleaning company insolvencies can move on a handful of cases month to "
            "month. Prefer the year-to-date or 12-month rolling total for the "
            "steadier read.",
            "The count is a volume, not a failure rate. It is not adjusted for how "
            "many cleaning contractors are registered, so it cannot be read as a "
            "sector-wide risk of insolvency.",
            "This is commercial and industrial cleaning only (SIC 812). Domestic "
            "cleaning and waste collection sit under separate SIC codes and are "
            "not included here.",
        ],
        "practitioner_view": [
            "In the cases we see, cleaning contracting is almost entirely a labour "
            "cost business, so minimum wage and employer National Insurance "
            "increases hit the cost base directly, with very little else to trim.",
            "Multi-year contracts are the specific trap. A price agreed before a "
            "cost increase often cannot be revisited until renewal, leaving a "
            "contractor committed to an unprofitable rate for months or years.",
        ],
        "pressure": [
            {
                "h3": "Labour cost is almost the entire cost base",
                "body": ("Cleaning is overwhelmingly a labour cost business, so "
                         "minimum wage and employer National Insurance increases "
                         "hit margins directly, with little scope to absorb them "
                         "elsewhere in the cost structure."),
            },
            {
                "h3": "Fixed-price contracts agreed before costs rose",
                "body": ("Multi-year cleaning contracts are often priced years in "
                         "advance and cannot be repriced until renewal, so a "
                         "contractor can be locked into a rate that stopped "
                         "covering its costs long before the contract ends."),
            },
        ],
        "citation": ("CompanyDebt. (2026). UK Cleaning Company Insolvency "
                     "Statistics. CompanyDebt.com. Data sourced from the Insolvency "
                     "Service company insolvency statistics by industry (Table 1c)."),
        "related": ('Cleaning contractors sit within the wider '
                    '<a href="/data/company-insolvencies-by-sector/">company insolvencies by sector</a> '
                    'data, alongside administrative and support services generally. See also the '
                    '<a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>.'),
    },
    "hotel-insolvency-statistics": {
        "wp_id": 80141,
        "sic_code": "551",
        "division_code": "55",
        "parent_section_code": "I",
        "parent_section_label": "accommodation and food service",
        "h1a": "UK Hotel",
        "h1b": "Insolvency Statistics",
        "h1_subtitle": "Latest detailed figures for England and Wales",
        "eyebrow": "Hotels",
        "keyword": "hotel",
        "singular": "hotel",
        "plural": "hotels and similar accommodation businesses",
        "scope_description": "hotels and similar short-stay accommodation",
        "exclusion_note": "Restaurants, pubs and self-catering or holiday accommodation are recorded separately.",
        "notes": [
            "Hotel insolvencies are a smaller sector by count, so monthly figures "
            "can move sharply on a handful of cases. Prefer the year-to-date or "
            "12-month rolling total for the steadier read.",
            "The count is a volume, not a failure rate. It is not adjusted for how "
            "many hotels are registered, so it cannot be read as a sector-wide "
            "risk of insolvency.",
            "This is hotels and similar accommodation only (SIC 551). Restaurants, "
            "pubs and self-catering accommodation sit under separate SIC codes "
            "and are not included here.",
        ],
        "practitioner_view": [
            "In the cases we see, hotels carry more fixed cost than most "
            "hospitality formats: property, energy and a baseline of staffing "
            "continue through quiet periods regardless of occupancy.",
            "Many hotels also carry debt from refurbishment cycles that has to be "
            "serviced whether the rooms are full or not, which turns a soft "
            "occupancy quarter into a cash-flow problem faster than in a "
            "lower-cost format.",
        ],
        "pressure": [
            {
                "h3": "High fixed operating costs",
                "body": ("Property, energy and a baseline level of staffing "
                         "continue regardless of occupancy, so hotels carry more "
                         "fixed cost than most other hospitality formats and less "
                         "room to cut back when trade is quiet."),
            },
            {
                "h3": "Discretionary, debt-funded demand",
                "body": ("Leisure and business travel are both discretionary "
                         "spend that softens quickly when confidence drops, while "
                         "refurbishment debt still has to be serviced regardless "
                         "of how full the hotel is."),
            },
        ],
        "citation": ("CompanyDebt. (2026). UK Hotel Insolvency Statistics. "
                     "CompanyDebt.com. Data sourced from the Insolvency Service "
                     "company insolvency statistics by industry (Table 1c)."),
        "related": ('Hotels sit within the wider '
                    '<a href="/data/company-insolvencies-by-sector/">company insolvencies by sector</a> '
                    'data, alongside accommodation and food service generally. See also '
                    '<a href="/data/restaurant-insolvency-statistics/">restaurant insolvency statistics</a> '
                    'and the <a href="/data/uk-insolvency-statistics/">UK company insolvency statistics</a>.'),
    },
}


def load() -> dict:
    ser = json.loads((DATA / "sector_series.json").read_text(encoding="utf-8"))
    meta = json.loads((DATA / "release_metadata.json").read_text(encoding="utf-8"))
    return {"ser": ser, "meta": meta}


def group_by_code(ser: dict, code: str) -> dict:
    return next(g for g in ser["groups"] if g["code"] == code)


def section_by_code(ser: dict, code: str) -> dict:
    return next(s for s in ser["sections"] if s["code"] == code)


def trough_year(annual: list, years: list) -> int:
    vals = [v for v in annual if v is not None]
    idx = annual.index(min(vals))
    return years[idx]


def ytd_sum(monthly: list, months: list, year: int, upto_month: int) -> int:
    return sum(
        (monthly[i] or 0) for i, m in enumerate(months)
        if int(m.split("-")[0]) == year and int(m.split("-")[1]) <= upto_month
    )


def change_phrase(current: int, prior: int | None, unchanged_vs: str = "", value_vs: str = "") -> str:
    """'up slightly from 63' / 'unchanged from the previous 12 months' /
    'down from 90', generic across every sector page — never hand-authored
    per sector. unchanged_vs/value_vs let the diff==0 case read naturally
    ("unchanged from the previous 12 months") instead of repeating the same
    number twice ("unchanged from 144 for the previous 12 months")."""
    if prior is None:
        return "no comparable prior period"
    diff = current - prior
    if diff == 0:
        return f"unchanged{unchanged_vs or f' from {format_number(prior)}'}"
    pct = abs(diff) / prior * 100 if prior else None
    size = "slightly " if pct is not None and pct < 5 else ""
    word = "up" if diff > 0 else "down"
    return f"{word} {size}from {format_number(prior)}{value_vs}"


def figures(cfg: dict, c: dict) -> dict:
    ser = c["ser"]
    g = group_by_code(ser, cfg["sic_code"])
    months = ser["monthly_months"]
    years = ser["annual_years"]
    li = len(years) - 1

    latest_month = months[-1]
    latest_year, latest_mo = (int(x) for x in latest_month.split("-"))
    prior_year = latest_year - 1

    ytd_current = ytd_sum(g["monthly"], months, latest_year, latest_mo)
    ytd_prior = ytd_sum(g["monthly"], months, prior_year, latest_mo)

    rolling_current = sum(v or 0 for v in g["monthly"][-12:])
    rolling_prior = sum(v or 0 for v in g["monthly"][-24:-12]) if len(g["monthly"]) >= 24 else None

    latest_val = g["monthly"][-1]
    same_month_prior_period = f"{prior_year}-{latest_mo:02d}"
    same_month_prior_val = (
        g["monthly"][months.index(same_month_prior_period)]
        if same_month_prior_period in months else None
    )
    prev_month_val = g["monthly"][-2] if len(g["monthly"]) > 1 else None
    prev_month_label = month_full(months[-2]) if len(months) > 1 else ""

    latest_annual = g["annual"][li]
    prior_annual = g["annual"][li - 1] if li > 0 else None
    peak = max(v for v in g["annual"] if v is not None)
    peak_year = years[g["annual"].index(peak)]

    # Fixed pre-pandemic reference year (2019, not sector-derived) — a
    # meaningful baseline ("the last normal year"), unlike an arbitrary
    # "since the series began" comparison.
    pre_pandemic_year = 2019
    pre_pandemic_val = g["annual"][years.index(pre_pandemic_year)] if pre_pandemic_year in years else None
    vs_pre_pandemic_pct = (
        (latest_annual - pre_pandemic_val) / pre_pandemic_val * 100
        if pre_pandemic_val else None
    )

    return {
        "group": g, "years": years, "li": li, "months": months,
        "latest_month": latest_month, "latest_year": latest_year, "latest_mo": latest_mo,
        "prior_year": prior_year,
        "ytd_current": ytd_current, "ytd_prior": ytd_prior,
        "ytd_change_phrase": change_phrase(ytd_current, ytd_prior),
        "rolling_current": rolling_current, "rolling_prior": rolling_prior,
        "rolling_change_phrase": change_phrase(
            rolling_current, rolling_prior,
            unchanged_vs=" from the previous 12 months", value_vs=" for the previous 12 months",
        ),
        "latest_val": latest_val, "prev_month_val": prev_month_val, "prev_month_label": prev_month_label,
        "same_month_prior_val": same_month_prior_val,
        "latest_annual": latest_annual, "prior_annual": prior_annual,
        "annual_change_phrase": change_phrase(latest_annual, prior_annual),
        "peak": peak, "peak_year": peak_year,
        "base_val": g["annual"][0], "base_year": years[0],
        "pre_pandemic_year": pre_pandemic_year, "pre_pandemic_val": pre_pandemic_val,
        "vs_pre_pandemic_pct": vs_pre_pandemic_pct,
    }


def sector_fact(cfg: dict, c: dict, f: dict) -> dict:
    """Data-driven comparison of the sector to its parent SIC section: entirely
    computed from sector_series.json, no per-sector authoring needed. Generic
    across every future sector page in this family. Leads with the
    year-to-date comparison (the current story); the multi-year annual band
    is kept as supporting context, not the headline claim."""
    ser = c["ser"]
    years = f["years"]
    months = f["months"]
    parent = section_by_code(ser, cfg["parent_section_code"])
    g = f["group"]

    parent_ytd_current = ytd_sum(parent["monthly"], months, f["latest_year"], f["latest_mo"])
    parent_ytd_prior = ytd_sum(parent["monthly"], months, f["prior_year"], f["latest_mo"])
    share_ytd_current = round(f["ytd_current"] / parent_ytd_current * 100, 1) if parent_ytd_current else None
    share_ytd_prior = round(f["ytd_prior"] / parent_ytd_prior * 100, 1) if parent_ytd_prior else None
    sector_change_pct = (f["ytd_current"] - f["ytd_prior"]) / f["ytd_prior"] * 100 if f["ytd_prior"] else None
    parent_change_pct = (parent_ytd_current - parent_ytd_prior) / parent_ytd_prior * 100 if parent_ytd_prior else None

    jan_period = f"{f['latest_year']}-01"
    jan_label = month_full(jan_period).split()[0] if jan_period in months else "January"
    latest_month_name = month_full(f["latest_month"])
    ytd_label = f"{jan_label} to {latest_month_name}"
    ytd_label_and = f"{jan_label} and {latest_month_name}"

    shares = [
        round(g["annual"][i] / parent["annual"][i] * 100, 1)
        for i in range(len(years)) if parent["annual"][i]
    ]
    share_min, share_max = min(shares), max(shares)
    band_note = (
        f"a narrow {share_min}% to {share_max}% band"
        if (share_max - share_min) < 5
        else f"a {share_min}% to {share_max}% range"
    )

    g_trough = trough_year(g["annual"], years)
    p_trough = trough_year(parent["annual"], years)
    t_trough = trough_year(ser["total"]["annual"], years)
    pandemic_years = (2020, 2021)
    if g_trough in pandemic_years:
        trough_note = (
            f"Recorded insolvencies reached their series low of {format_number(g['annual'][years.index(g_trough)])} "
            f"in {g_trough}, when pandemic restrictions and government support distorted normal "
            f"insolvency patterns."
        )
    else:
        trough_note = (
            f"Recorded insolvencies reached their series low of "
            f"{format_number(g['annual'][years.index(g_trough)])} in {g_trough}."
        )
    if g_trough == p_trough != t_trough:
        if g_trough == f["base_year"]:
            # The trough is simply the first year of the series (a growing
            # sector, not a dip) — "a year after/before" would be nonsensical
            # here, since there is no earlier data point to compare against.
            trough_note += (
                f" {cfg['parent_section_label'].capitalize()} overall shows the same "
                f"pattern: {g_trough} was its lowest year too, both series having "
                f"climbed fairly steadily since the data begins."
            )
        else:
            gap = g_trough - t_trough
            plural = "s" if abs(gap) != 1 else ""
            timing = f"{gap} year{plural} after" if gap > 0 else f"{abs(gap)} year{plural} before"
            trough_note += (
                f" That was in step with {cfg['parent_section_label']} overall, which "
                f"also troughed in {g_trough}, {timing} the wider economy's {t_trough} low."
            )

    return {
        "parent_label": cfg["parent_section_label"],
        "ytd_label": ytd_label,
        "ytd_label_and": ytd_label_and,
        "parent_ytd_current": parent_ytd_current,
        "parent_ytd_prior": parent_ytd_prior,
        "share_ytd_current": share_ytd_current,
        "share_ytd_prior": share_ytd_prior,
        "sector_change_pct": sector_change_pct,
        "parent_change_pct": parent_change_pct,
        "trough_note": trough_note,
        "band_note": band_note,
        "share_stat": (
            f"{cfg['plural'].capitalize()} accounted for {share_ytd_current}% of all "
            f"{cfg['parent_section_label']} company insolvencies in the {ytd_label} period "
            f"({format_number(f['ytd_current'])} of {format_number(parent_ytd_current)} cases), "
            f"{'up' if share_ytd_current >= share_ytd_prior else 'down'} from "
            f"{share_ytd_prior}% over the same months of {f['prior_year']}."
        ),
        "annual_context": (
            f"Over the full {f['base_year']} to {years[f['li']]} annual series, "
            f"{cfg['eyebrow'].lower()}'s share of {cfg['parent_section_label']} insolvencies "
            f"has held to {band_note}, despite {cfg['parent_section_label']} overall "
            f"swinging much further year to year."
        ),
    }


def hero_block(cfg: dict, f: dict, meta: dict, sf: dict) -> str:
    if f["vs_pre_pandemic_pct"] is not None:
        pp_word = "above" if f["vs_pre_pandemic_pct"] >= 0 else "below"
        pp_value = f"{abs(round(f['vs_pre_pandemic_pct']))}% {pp_word} {f['pre_pandemic_year']}"
        pp_note = (
            f"The {f['years'][f['li']]} total of {format_number(f['latest_annual'])} remained "
            f"well {pp_word} the pre-pandemic total of {format_number(f['pre_pandemic_val'])} "
            f"in {f['pre_pandemic_year']}"
        )
    else:
        pp_value = "n/a"
        pp_note = "No pre-pandemic (2019) comparison is available for this series."
    return dedent(f"""\
    <section class="cd-w-hero">
      <a class="cd-back" href="/data/"><span aria-hidden="true">&larr;</span> UK Company Insolvency Data</a>
      <div class="cd-hero">
      <div class="cd-hero__copy">
        <h1><span class="cd-h1__line">{cfg['h1a']}</span> <span class="cd-h1__line">{cfg['h1b']}</span></h1>
        <p class="cd-hero__subtitle">{cfg['h1_subtitle']}</p>
        <p class="cd-lede">There were {format_number(f['ytd_current'])} insolvencies among {cfg['plural']} in England and Wales between {sf['ytd_label_and']}, compared with {format_number(f['ytd_prior'])} in the same period of {f['prior_year']}. The rolling 12-month total was {format_number(f['rolling_current'])}, {f['rolling_change_phrase']}.</p>
        <p class="cd-lede">The data covers SIC Division {cfg['division_code']} and Group {cfg['sic_code']}: {cfg['scope_description']}. {cfg['exclusion_note']}</p>
        <dl class="cd-meta-grid">
          <div class="cd-meta-item"><span>Latest data</span><strong>{meta['latest_month_label']}</strong></div>
          <div class="cd-meta-item"><span>Published</span><strong>{meta['publication_date']}</strong></div>
          <div class="cd-meta-item"><span>Industry update</span><strong>Monthly</strong></div>
          <div class="cd-meta-item"><span>Source</span><strong>{meta['source_label']}</strong></div>
        </dl>
        <p class="cd-official-badge"><span aria-hidden="true"></span>{meta['status']}</p>
      </div>
      <aside class="cd-hero__panel" aria-label="Latest figures">
        <p class="cd-kpi-label">{cfg['eyebrow']} (SIC {cfg['sic_code']}) &middot; England and Wales</p>
        <div class="cd-main-kpi">
          <span class="cd-main-kpi__v">{format_number(f['ytd_current'])}</span>
          <span class="cd-main-kpi__k">insolvencies, {sf['ytd_label']}</span>
        </div>
        <div class="cd-change-row">
          <span><strong>{f['ytd_change_phrase']}</strong> in {f['prior_year']}</span>
        </div>
        <div class="cd-kpi-divider" aria-hidden="true"></div>
        <div class="cd-mini-kpi-grid">
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{format_number(f['rolling_current'])}</span><span class="cd-mini-kpi__k">Rolling 12 months</span><span class="cd-mini-kpi__n">to {meta['latest_month_label']}, {f['rolling_change_phrase']}</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{pp_value}</span><span class="cd-mini-kpi__k">Longer-term context</span><span class="cd-mini-kpi__n">{f['years'][f['li']]} vs {f['pre_pandemic_year']}</span></div>
          <div class="cd-mini-kpi"><span class="cd-mini-kpi__v">{sf['share_ytd_current']}%</span><span class="cd-mini-kpi__k">Of {sf['parent_label']} insolvencies</span><span class="cd-mini-kpi__n">{sf['ytd_label']}</span></div>
        </div>
      </aside>
      </div>
    </section>""")


def pre_pandemic_phrase(f: dict) -> tuple[str, str]:
    """(short value for a KPI card, full sentence) comparing the latest full
    year to 2019 — a fixed, meaningful baseline ("the last normal year"),
    reused by the hero and the latest-figures summary so the two never drift."""
    if f["vs_pre_pandemic_pct"] is None:
        return "n/a", "No pre-pandemic (2019) comparison is available for this series."
    word = "above" if f["vs_pre_pandemic_pct"] >= 0 else "below"
    value = f"{abs(round(f['vs_pre_pandemic_pct']))}% {word} {f['pre_pandemic_year']}"
    sentence = (
        f"The {f['years'][f['li']]} total of {format_number(f['latest_annual'])} remained "
        f"well {word} the pre-pandemic total of {format_number(f['pre_pandemic_val'])} "
        f"in {f['pre_pandemic_year']}."
    )
    return value, sentence


def latest_figures_block(cfg: dict, f: dict, sf: dict) -> str:
    """A compact, scannable summary immediately below the hero — every figure
    already stated elsewhere on the page, gathered into one table so a reader
    doesn't have to hunt through prose for it."""
    pp_value, pp_sentence = pre_pandemic_phrase(f)
    direction = "falling" if f["ytd_current"] < f["ytd_prior"] else (
        "rising" if f["ytd_current"] > f["ytd_prior"] else "flat"
    )
    same_month_prior_period = f"{f['prior_year']}-{f['latest_mo']:02d}"
    same_month_prior_label = month_full(same_month_prior_period)
    rolling_to_label = f"To {month_full(f['latest_month'])}"
    rows = [
        (f"{cfg['eyebrow']} insolvencies", format_number(f['ytd_current']),
         f"{format_number(f['ytd_prior'])} in the same period of {f['prior_year']}",
         sf['ytd_label'], "England and Wales"),
        ("Rolling 12-month insolvencies", format_number(f['rolling_current']),
         f"{format_number(f['rolling_prior'])} in the preceding 12 months" if f['rolling_prior'] is not None else "n/a",
         rolling_to_label, "England and Wales"),
        ("Latest monthly figure", format_number(f['latest_val']),
         f"{format_number(f['prev_month_val'])} in {f['prev_month_label']}; "
         f"{format_number(f['same_month_prior_val'])} in {same_month_prior_label}",
         month_full(f['latest_month']), "England and Wales"),
        ("Full-year insolvencies", format_number(f['latest_annual']),
         f"{format_number(f['prior_annual'])} in {f['years'][f['li'] - 1]}" if f['prior_annual'] is not None else "n/a",
         str(f['years'][f['li']]), "England and Wales"),
        ("Series peak", format_number(f['peak']), "n/a", str(f['peak_year']), "England and Wales"),
    ]
    rows_html = "".join(
        f"<tr><th scope=\"row\">{measure}</th><td class=\"cd-num\">{val}</td>"
        f"<td class=\"cd-num\">{cmp_}</td><td>{period}</td><td>{geo}</td></tr>"
        for measure, val, cmp_, period, geo in rows
    )
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="latest">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Latest data</p>
        <h2>Latest {cfg['keyword']} insolvency figures</h2>
      </div>
      <div class="cd-tablewrap">
        <table class="cd-table">
          <caption class="cd-table__caption">Latest {cfg['keyword']} insolvency figures, England and Wales. Source: Insolvency Service (Table 1c).</caption>
          <thead><tr><th scope="col">Measure</th><th scope="col" class="cd-num">Latest figure</th><th scope="col" class="cd-num">Comparison</th><th scope="col">Period</th><th scope="col">Geography</th></tr></thead>
          <tbody>{rows_html}</tbody>
        </table>
      </div>
      <p class="cd-source-note">The latest figures point in the same direction across the year-to-date and rolling measures: insolvencies are {direction} modestly. {pp_sentence}</p>
    </section>""")


def chart_block(cfg: dict, c: dict, f: dict) -> str:
    ser = c["ser"]
    g = f["group"]
    months = f["months"]
    line = build_line_chart(
        months, g["monthly"], chart_id=f"{cfg['sic_code']}-monthly",
        title=f"Monthly insolvencies among {cfg['plural']}, England and Wales",
        desc=f"Monthly company insolvencies among {cfg['plural']}, England and Wales, since January 2023.",
    )
    return dedent(f"""\
    <section class="cd-section cd-w-wide" id="trend">
      <div class="cd-section-head"><p class="cd-eyebrow">Trend</p><h2>{cfg['keyword'].capitalize()} insolvencies by month</h2>
        <p class="cd-section-intro">{month_full(f['latest_month'])} recorded {format_number(f['latest_val'])} insolvencies, against {format_number(f['prev_month_val'])} in {f['prev_month_label']} and {format_number(f['same_month_prior_val'])} in {month_full(f'{f["prior_year"]}-{f["latest_mo"]:02d}')}. One month does not establish a trend, but the year-to-date and rolling 12-month totals above are the steadier read; this chart is the detail behind them.</p>
        <p class="cd-section-intro">{cfg['related']}</p></div>
      <figure class="cd-chart-figure">
        <div class="cd-chart-panel cd-chart-panel--longrun">{line}</div>
        <figcaption class="cd-figcaption"><strong>Monthly insolvencies among {cfg['plural']}, England and Wales, since January 2023.</strong> Not seasonally adjusted. Source: Insolvency Service (Table 1c).</figcaption>
      </figure>
    </section>""")


def comparison_block(cfg: dict, f: dict, sf: dict) -> str:
    direction = "rising" if f["ytd_current"] > f["ytd_prior"] else (
        "falling" if f["ytd_current"] < f["ytd_prior"] else "flat"
    )
    heading_verb = {"rising": "rising", "falling": "falling", "flat": "changing"}[direction]
    sector_pct = f"{sf['sector_change_pct']:+.1f}%" if sf["sector_change_pct"] is not None else "n/a"
    parent_pct = f"{sf['parent_change_pct']:+.1f}%" if sf["parent_change_pct"] is not None else "n/a"
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="comparison">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Comparison</p>
        <h2>Are {cfg['keyword']} insolvencies {heading_verb} in {f['latest_year']}?</h2>
      </div>
      <div class="cd-side-notes">
        <p class="cd-side-note__d cd-sector-fact">Insolvencies among {cfg['plural']} were broadly {direction} in the {sf['ytd_label']} period, with {format_number(f['ytd_current'])} cases compared with {format_number(f['ytd_prior'])} during the same months of {f['prior_year']} ({sector_pct}). That contrasts with {sf['parent_label']} overall, where insolvencies moved {parent_pct} over the same comparison.</p>
        <p class="cd-side-note__d">{sf['share_stat']}</p>
      </div>
      <div class="cd-tablewrap">
        <table class="cd-table">
          <caption class="cd-table__caption">{cfg['eyebrow'].capitalize()} vs {sf['parent_label']} overall, {sf['ytd_label']}, England and Wales. Source: Insolvency Service (Table 1c).</caption>
          <thead><tr><th scope="col">Measure</th><th scope="col" class="cd-num">{cfg['eyebrow'].capitalize()}</th><th scope="col" class="cd-num">{sf['parent_label'].capitalize()} overall</th></tr></thead>
          <tbody>
            <tr><th scope="row">{sf['ytd_label']} insolvencies</th><td class="cd-num">{format_number(f['ytd_current'])}</td><td class="cd-num">{format_number(sf['parent_ytd_current'])}</td></tr>
            <tr><th scope="row">Same period {f['prior_year']}</th><td class="cd-num">{format_number(f['ytd_prior'])}</td><td class="cd-num">{format_number(sf['parent_ytd_prior'])}</td></tr>
            <tr><th scope="row">Change</th><td class="cd-num">{sector_pct}</td><td class="cd-num">{parent_pct}</td></tr>
            <tr><th scope="row">Share of {sf['parent_label']}</th><td class="cd-num">{sf['share_ytd_current']}%</td><td class="cd-num">n/a</td></tr>
          </tbody>
        </table>
      </div>
      <p class="cd-source-note">Not seasonally adjusted, England and Wales. Source: Insolvency Service (Table 1c).</p>
    </section>""")


def pressure_block(cfg: dict) -> str:
    if not cfg.get("pressure"):
        return ""

    def body_paras(body):
        paras = body if isinstance(body, list) else [body]
        return "".join(f'<p class="cd-side-note__d">{p}</p>' for p in paras)

    items = "".join(
        f'<div class="cd-note-item"><h3>{p["h3"]}</h3>{body_paras(p["body"])}</div>'
        for p in cfg["pressure"]
    )
    heading = cfg.get("pressure_heading") or f"Why {cfg['plural']} are under pressure"
    intro_paras = "".join(f'<p class="cd-section-intro">{p}</p>' for p in cfg.get("pressure_intro", []))
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="pressure">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Context</p>
        <h2>{heading}</h2>
        {intro_paras}
        <p class="cd-section-intro">General sector conditions, not a claim about any individual company. Read alongside the figures above, not as their explanation.</p>
      </div>
      <div class="cd-side-notes">{items}</div>
    </section>""")


def practitioner_block(cfg: dict) -> str:
    """The earned-'we' practitioner callout, standalone (not nested inside
    the pressure factors, which are general sector economics rather than
    caseload observation — the two read differently and shouldn't be
    conflated in one box)."""
    if not cfg.get("practitioner_view"):
        return ""
    paras = "".join(
        f'<p class="cd-side-note__d cd-side-note__insight">{p}</p>' for p in cfg["practitioner_view"]
    )
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="practitioner">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Practitioner view</p>
        <h2>What we see in {cfg['keyword']} insolvency cases</h2>
      </div>
      <div class="cd-side-notes">{paras}</div>
    </section>""")


def sector_rate_block(cfg: dict, f: dict) -> str:
    """Optional: the parent SIC section's official insolvency rate per 10,000
    businesses (Insolvency Service Business Insolvency Demography). Only
    renders when a sector's cfg carries VERIFIED rate figures — never
    fabricated, and never presented as a rate for the sector itself, only
    for the parent section it sits within."""
    if not cfg.get("parent_rate_current"):
        return ""
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="rate">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Context</p>
        <h2>How {cfg['keyword']} insolvencies compare with {cfg['parent_section_label']} overall</h2>
      </div>
      <div class="cd-side-notes">
        <p class="cd-side-note__d">{cfg['parent_section_label'].capitalize()} had the highest company insolvency rate among the largest UK industries in {cfg['parent_rate_year']}, at {cfg['parent_rate_current']} insolvencies per 10,000 businesses. The sector has recorded the highest rate every year since 2015, although the rate has fallen from its {cfg['parent_rate_peak_year']} peak of {cfg['parent_rate_peak']} per 10,000.</p>
        <p class="cd-side-note__d">This rate covers {cfg['parent_section_label']} as a whole and must not be read as a {cfg['keyword']}-only failure rate. It does, however, show that {cfg['keyword']} businesses operate within a sector where formal insolvency remains unusually common.</p>
      </div>
      <p class="cd-source-note">Source: Insolvency Service, Business Insolvency Demography. This figure is quoted directly from the publication, not a Company Debt calculation.</p>
    </section>""")


def commercial_block(cfg: dict) -> str:
    paras = cfg.get("commercial_transition")
    if not paras:
        return ""
    paras_html = "".join(f'<p class="cd-side-note__d">{p}</p>' for p in paras)
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="commercial">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Next steps</p>
        <h2>What to do if your {cfg['singular']} cannot pay its debts</h2>
      </div>
      <div class="cd-side-notes">{paras_html}</div>
    </section>""")


def longer_term_block(cfg: dict) -> str:
    """Optional: a standalone historical-narrative section (rise / pandemic
    interruption / post-support surge / recent improvement) for sectors whose
    annual pattern has enough distinct phases to be worth spelling out
    separately from the bare annual table. Free-authored per sector (the
    phase structure varies too much to template generically) — renders as a
    no-op when a sector doesn't set it."""
    paras = cfg.get("longer_term_narrative")
    if not paras:
        return ""
    paras_html = "".join(f'<p class="cd-side-note__d">{p}</p>' for p in paras)
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="longterm">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Context</p>
        <h2>What the longer-term {cfg['keyword']} insolvency trend shows</h2>
      </div>
      <div class="cd-side-notes">{paras_html}</div>
    </section>""")


def policy_update_block(cfg: dict) -> str:
    """Optional: a short current-policy callout (e.g. a tax or duty change
    relevant to the sector). Free-authored per sector, sourced, dated — not
    presented as an explanation for past insolvency figures."""
    pu = cfg.get("policy_update")
    if not pu:
        return ""
    paras_html = "".join(f'<p class="cd-side-note__d">{p}</p>' for p in pu["paras"])
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="policy">
      <div class="cd-section-head">
        <p class="cd-eyebrow">Policy update</p>
        <h2>{pu['heading']}</h2>
      </div>
      <div class="cd-side-notes">{paras_html}</div>
    </section>""")


def annual_narrative(cfg: dict, f: dict) -> str:
    """Data-driven rise/peak/recent-trend story for the annual series —
    generic across every sector, not hand-authored per page."""
    g, years, li = f["group"], f["years"], f["li"]
    peak, peak_year = f["peak"], f["peak_year"]
    base_val, base_year = f["base_val"], f["base_year"]
    latest_year, latest = years[li], f["latest_annual"]
    parts = []
    if peak_year != base_year:
        parts.append(
            f"{cfg['eyebrow']} insolvencies rose from {format_number(base_val)} in "
            f"{base_year} to a peak of {format_number(peak)} in {peak_year}."
        )
    if peak_year != latest_year and peak:
        pct = (latest - peak) / peak * 100
        word = "fallen" if pct < 0 else "risen"
        parts.append(
            f"Since then, insolvencies have {word} {abs(round(pct))}% to "
            f"{format_number(latest)} in {latest_year}."
        )
    _, pp_sentence = pre_pandemic_phrase(f)
    parts.append(pp_sentence)
    return " ".join(parts)


def annual_block(cfg: dict, c: dict, f: dict, sf: dict) -> str:
    g = f["group"]
    rows = "".join(
        f"<tr><th scope=\"row\">{y}</th><td class=\"cd-num\">{format_number(g['annual'][i])}</td></tr>"
        for i, y in enumerate(f["years"])
    )
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="annual">
      <div class="cd-section-head"><p class="cd-eyebrow">Annual</p><h2>{cfg['keyword'].capitalize()} insolvencies by year, {f['base_year']} to {f['years'][f['li']]}</h2>
        <p class="cd-section-intro">{annual_narrative(cfg, f)}</p>
        <p class="cd-section-intro">{sf['trough_note']}</p></div>
      <div class="cd-tablewrap">
        <table class="cd-table">
          <caption class="cd-table__caption">Annual company insolvencies among {cfg['plural']}, England and Wales, not seasonally adjusted. Source: Insolvency Service (Table 1c).</caption>
          <thead><tr><th scope="col">Year</th><th scope="col" class="cd-num">Insolvencies</th></tr></thead>
          <tbody>{rows}</tbody>
        </table>
      </div>
      <p class="cd-source-note">Not seasonally adjusted, England and Wales. Source: Insolvency Service (Table 1c).</p>
    </section>""")


def context_block(cfg: dict) -> str:
    notes = "".join(f"<p class=\"cd-side-note__d\">{n}</p>" for n in cfg["notes"])
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="about">
      <div class="cd-section-head">
        <p class="cd-eyebrow">How to read this</p>
        <h2>How to interpret the {cfg['keyword']} figures</h2>
      </div>
      <div class="cd-side-notes">{notes}</div>
    </section>""")


def source_block(slug: str, cfg: dict, meta: dict) -> str:
    cid = f"cd-citation-{slug}"
    return dedent(f"""\
    <section class="cd-section cd-w-standard" id="source">
      <div class="cd-section-head"><p class="cd-eyebrow">Source</p><h2>Source and citation</h2></div>
      <div class="cd-cite-card">
        <div class="cd-cite-card__left">
          <dl>
            <dt>Primary source</dt><dd>Insolvency Service, Company Insolvency Statistics, {meta['latest_month_label']} (Table 1c, by industry).</dd>
            <dt>Supporting source</dt><dd>Companies House company register data.</dd>
            <dt>Publication date</dt><dd>{meta['publication_date']}</dd>
            <dt>Industry breakdown</dt><dd>Table 1c total by industry is published monthly, through the latest headline month. The supplementary breakdown by insolvency procedure is published quarterly.</dd>
            <dt>Status</dt><dd>{meta['status']}</dd>
          </dl>
        </div>
        <div class="cd-cite-card__right">
          <p class="cd-eyebrow">How to cite this page</p>
          <p class="cd-cite-text" id="{cid}">{cfg['citation']}</p>
          <button type="button" class="cd-cite-copy" aria-label="Copy citation to clipboard" data-cd-copy="#{cid}">Copy citation</button>
        </div>
      </div>
    </section>""")


def assemble(slug: str, c: dict) -> str:
    cfg = SECTORS[slug]
    f = figures(cfg, c)
    sf = sector_fact(cfg, c, f)
    meta = c["meta"]
    body = "\n".join([
        f"<style>{DASHBOARD_CSS}</style>", '<div class="cd-data-hub">',
        masthead_block(), hero_block(cfg, f, meta, sf), srcstrip_block(),
        latest_figures_block(cfg, f, sf),
        comparison_block(cfg, f, sf), chart_block(cfg, c, f),
        longer_term_block(cfg),
        pressure_block(cfg), practitioner_block(cfg), policy_update_block(cfg),
        annual_block(cfg, c, f, sf), sector_rate_block(cfg, f),
        context_block(cfg), commercial_block(cfg),
        methodology_block(), source_block(slug, cfg, meta), final_cta_block(),
        '</div>',
    ])
    return SENTINEL + "\n<!-- wp:html -->\n" + body + "\n<!-- /wp:html -->\n"


def main(argv: list[str]) -> int:
    targets = argv or list(SECTORS)
    c = load()
    DRAFTS.mkdir(parents=True, exist_ok=True)
    for slug in targets:
        if slug not in SECTORS:
            print(f"unknown slug: {slug}")
            return 2
        cfg = SECTORS[slug]
        out = DRAFTS / f"{cfg['wp_id']}_{slug}.html"
        out.write_text(assemble(slug, c), encoding="utf-8")
        f = figures(cfg, c)
        print(f"wrote {out.name}: YTD {f['ytd_current']} vs {f['ytd_prior']}, "
              f"rolling12 {f['rolling_current']}, full-year {f['latest_annual']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
