"""Assemble the Winding-Up Petition Tracker page.

Takes the Claude Design reference and injects live Gazette figures, regenerating
both charts from the real monthly notice series (last 16 months, to match the
design window):
  - Chart A: CSS column chart of winding-up petitions advertised per month
  - Chart B: SVG line chart of petitions vs winding-up orders

KPIs, the notice table and the caveat/credibility figures come from the latest
month's metrics.

Writes:
  - preview/winding-up-petition-tracker.html
  - drafts/pending_winding-up-petition-tracker.html

Usage:
    python scripts/datahub/pages/winding_up_petition_tracker.py
"""

from __future__ import annotations

import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DATA = ROOT / "data"
DESIGN = ROOT / "design-handoff" / "winding-up-petition-tracker.html"
PREVIEW_OUT = ROOT / "preview" / "winding-up-petition-tracker.html"
DRAFT_OUT = ROOT / "drafts" / "79847_winding-up-petition-tracker.html"

THEME_ASSETS = "/wp-content/themes/company-debt-webpigment/assets/data-hub"
HUB_URL = "/data/company-insolvency/"
SENTINEL = ("<!-- CD-NO-AUTOEDIT: data_reference page generated by "
            "scripts/datahub/pages/winding_up_petition_tracker.py. "
            "Internal-link and article-rewrite pipelines must skip this file. -->")

MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]
ABBR = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def month_label(p: str) -> str:
    y, m = p.split("-")
    return f"{MONTHS[int(m) - 1]} {y}"


def y_max(maxv: int) -> int:
    return math.ceil(maxv * 1.05 / 100) * 100


def build_column_chart(months: list[str], vals: list[int], ymax: int) -> str:
    cols = []
    for i, (m, v) in enumerate(zip(months, vals)):
        h = v / ymax * 100
        mm = int(m.split("-")[1])
        yr = m.split("-")[0][2:]
        small = f"<small>&rsquo;{yr}</small>" if (i == 0 or mm == 1) else ""
        cols.append(
            '        <div class="cd-col">\n'
            f'          <div class="cd-col__track"><div class="cd-col__bar" style="height:{h:.1f}%"><span class="cd-col__v">{v:,}</span></div></div>\n'
            f'          <span class="cd-col__x">{ABBR[mm - 1]}{small}</span>\n'
            '        </div>'
        )
    aria = (f"Column chart of winding-up petitions advertised each month from "
            f"{month_label(months[0])} to {month_label(months[-1])}, ending at {vals[-1]:,} in {month_label(months[-1])}.")
    return f'<div class="cd-colchart" role="img" aria-label="{aria}">\n' + "\n".join(cols)


def build_line_svg(months: list[str], pet: list[int], orders: list[int], ymax: int) -> str:
    n = len(months)
    x0, x1, ybase, ytop = 56.0, 1176.0, 332.0, 24.0
    xspan, yspan = x1 - x0, ybase - ytop

    def x(i):
        return x0 + i * xspan / (n - 1)

    def y(v):
        return ybase - (v / ymax) * yspan

    parts = []
    for t in range(5):
        val = ymax * t / 4
        gy = y(val)
        parts.append(f'      <line class="cd-grid" x1="56" y1="{gy:.1f}" x2="1176" y2="{gy:.1f}"/>')
        parts.append(f'      <text class="cd-axis-y" x="44" y="{gy + 4:.1f}">{int(val)}</text>')

    def poly(vals, cls):
        pts = " ".join(f"{x(i):.1f},{y(v):.1f}" for i, v in enumerate(vals))
        return f'      <polyline class="cd-line {cls}" points="{pts}"/>'

    parts.append(poly(pet, "cd-line--p"))
    parts.append(poly(orders, "cd-line--o"))
    for vals, cls in ((pet, "cd-dot--p"), (orders, "cd-dot--o")):
        for i, v in enumerate(vals):
            parts.append(f'      <circle class="cd-dot {cls}" cx="{x(i):.1f}" cy="{y(v):.1f}" r="3.5"/>')
    for i, m in enumerate(months):
        parts.append(f'      <text class="cd-axis-x" x="{x(i):.1f}" y="356">{ABBR[int(m.split("-")[1]) - 1]}</text>')

    aria = (f"Line chart comparing winding-up petitions advertised with winding-up orders made each month, "
            f"{month_label(months[0])} to {month_label(months[-1])}. Orders track below petitions throughout, "
            f"ending at {orders[-1]:,} orders against {pet[-1]:,} petitions.")
    return (f'<svg class="cd-linechart" viewBox="0 0 1200 380" preserveAspectRatio="xMidYMid meet" '
            f'role="img" aria-label="{aria}">\n' + "\n".join(parts) + "\n        </svg>")


def load_context() -> dict:
    series = json.loads((DATA / "the-gazette" / "monthly_notice_series.json").read_text(encoding="utf-8"))["months"]
    months = sorted(series)[-16:]
    pet = [series[m]["metrics"]["winding_up_petitions"] for m in months]
    orders = [series[m]["metrics"]["winding_up_orders"] for m in months]
    latest = months[-1]
    lm = series[latest]["metrics"]
    return {
        "months": months, "pet": pet, "orders": orders,
        "ymax": y_max(max(max(pet), max(orders))),
        "period": month_label(latest),
        "window": f"{month_label(months[0])} to {month_label(months[-1])}",
        "m": lm,
        "total": series[latest]["total_corporate_insolvency_notices"],
    }


def inject(html: str, c: dict) -> str:
    # Chart A: splice in the regenerated column chart
    open_marker = '<div class="cd-colchart"'
    src_marker = '<p class="cd-source"><b>Source: The Gazette.</b> Petition notices advertised'
    i0, i1 = html.index(open_marker), html.index(src_marker)
    colchart = build_column_chart(c["months"], c["pet"], c["ymax"])
    html = html[:i0] + colchart + "\n        </div>\n      </div>\n      " + html[i1:]

    # Chart B: regenerate the SVG line chart
    html = re.sub(r'<svg class="cd-linechart".*?</svg>',
                  lambda _: build_line_svg(c["months"], c["pet"], c["orders"], c["ymax"]),
                  html, count=1, flags=re.S)

    # Window label + drop the sample-data disclaimer
    html = html.replace("February 2025 to May 2026", c["window"])
    html = html.replace(" Monthly values shown in the charts are representative sample data pending the full notice history.", "")

    # The latest-month figures already match the design; the page is data-current.
    return html


def to_wordpress(html: str) -> str:
    html = html.replace('src="assets/', f'src="{THEME_ASSETS}/')
    html = html.replace('href="company-insolvency-data-hub.html"', f'href="{HUB_URL}"')
    style = re.search(r"<style>.*?</style>", html, re.S)
    main = re.search(r'<main class="cd-data-hub">.*?</main>', html, re.S)
    if not style or not main:
        raise SystemExit("Could not extract <style> and <main>.")
    return "<!-- wp:html -->\n" + "\n".join([SENTINEL, style.group(0), main.group(0)]) + "\n<!-- /wp:html -->\n"


def main() -> int:
    c = load_context()
    design = DESIGN.read_text(encoding="utf-8")
    injected = inject(design, c)

    PREVIEW_OUT.parent.mkdir(parents=True, exist_ok=True)
    PREVIEW_OUT.write_text(injected, encoding="utf-8")
    DRAFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    DRAFT_OUT.write_text(to_wordpress(injected), encoding="utf-8")

    print("Winding-up petition tracker assembled with live data:")
    print(f"  Window: {c['window']} ({len(c['months'])} months)")
    print(f"  Latest ({c['period']}): petitions {c['m']['winding_up_petitions']:,}, "
          f"orders {c['m']['winding_up_orders']:,}, dismissals {c['m']['winding_up_petition_dismissals']:,}")
    print(f"  Chart y-axis max: {c['ymax']:,}")
    print(f"  Petitions range: {min(c['pet']):,}-{max(c['pet']):,}")
    print(f"Wrote preview: {PREVIEW_OUT}")
    print(f"Wrote draft:   {DRAFT_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
